import type { CharacterStage, KanaCard, KanaPronunciationExample } from './types';

export const CHARACTER_STAGES: CharacterStage[] = ['observe', 'recall', 'write', 'writeQuiz', 'quiz'];
export const stageText: Record<CharacterStage, { title: string; desc: string }> = {
  observe: { title: '1. 관찰', desc: '모양, 읽기, 의미를 10초 동안 함께 봅니다.' },
  recall:  { title: '2. 가리기 인출', desc: '글자를 보지 않고 읽기와 뜻을 먼저 떠올립니다.' },
  write:   { title: '3. 손으로 쓰기', desc: '획수와 규칙을 말하면서 캔버스에 크게 씁니다.' },
  writeQuiz: { title: '4. 손쓰기 퀴즈', desc: '읽기와 뜻만 보고 직접 쓴 뒤 채점합니다.' },
  quiz:    { title: '5. 즉시 테스트', desc: '정답을 고르고 다음 복습 강도를 결정합니다.' },
};

export const kanjiRules = [
  '위에서 아래로',
  '왼쪽에서 오른쪽으로',
  '가로획을 세로획보다 먼저',
  '가운데를 먼저 쓰고 양쪽을 나중에',
  '바깥틀을 먼저, 안쪽을 쓰고, 닫는 획은 마지막',
];

export function kanaAudioPath(mode: 'hiragana' | 'katakana', reading: string): string {
  return `audio/kana/v2/${mode}/${reading}.m4a`;
}

export const HIRAGANA: KanaCard[] = [
  ['あ','a',3],['い','i',2],['う','u',2],['え','e',2],['お','o',3],
  ['か','ka',3],['き','ki',4],['く','ku',1],['け','ke',3],['こ','ko',2],
  ['さ','sa',3],['し','shi',1],['す','su',2],['せ','se',3],['そ','so',1],
  ['た','ta',4],['ち','chi',2],['つ','tsu',1],['て','te',1],['と','to',2],
  ['な','na',4],['に','ni',3],['ぬ','nu',2],['ね','ne',2],['の','no',1],
  ['は','ha',3],['ひ','hi',1],['ふ','fu',4],['へ','he',1],['ほ','ho',4],
  ['ま','ma',3],['み','mi',2],['む','mu',3],['め','me',2],['も','mo',3],
  ['や','ya',3],['ゆ','yu',2],['よ','yo',2],
  ['ら','ra',2],['り','ri',2],['る','ru',1],['れ','re',2],['ろ','ro',1],
  ['わ','wa',2],['を','wo',3],['ん','n',1],
].map(([char, reading, strokeCount]) => ({
  id: `h-${char}`,
  mode: 'hiragana',
  char: String(char),
  reading: String(reading),
  meaning: '히라가나',
  strokeCount: Number(strokeCount),
  hint: '둥근 흐름을 유지하며 크게 쓰고, 마지막 획에서 소리와 모양을 함께 말하세요.',
  audioPath: kanaAudioPath('hiragana', String(reading)),
}));

export const KATAKANA: KanaCard[] = [
  ['ア','a',2],['イ','i',2],['ウ','u',3],['エ','e',3],['オ','o',3],
  ['カ','ka',2],['キ','ki',3],['ク','ku',2],['ケ','ke',3],['コ','ko',2],
  ['サ','sa',3],['シ','shi',3],['ス','su',2],['セ','se',2],['ソ','so',2],
  ['タ','ta',3],['チ','chi',3],['ツ','tsu',3],['テ','te',3],['ト','to',2],
  ['ナ','na',2],['ニ','ni',2],['ヌ','nu',2],['ネ','ne',4],['ノ','no',1],
  ['ハ','ha',2],['ヒ','hi',2],['フ','fu',1],['ヘ','he',1],['ホ','ho',4],
  ['マ','ma',2],['ミ','mi',3],['ム','mu',2],['メ','me',2],['モ','mo',3],
  ['ヤ','ya',2],['ユ','yu',2],['ヨ','yo',3],
  ['ラ','ra',2],['リ','ri',2],['ル','ru',2],['レ','re',1],['ロ','ro',3],
  ['ワ','wa',2],['ヲ','wo',3],['ン','n',2],
].map(([char, reading, strokeCount]) => ({
  id: `k-${char}`,
  mode: 'katakana',
  char: String(char),
  reading: String(reading),
  meaning: '가타카나',
  strokeCount: Number(strokeCount),
  hint: '직선과 각을 분명히 쓰고, シ/ツ·ソ/ン처럼 방향이 헷갈리는 글자는 첫 획 방향을 말하세요.',
  audioPath: kanaAudioPath('katakana', String(reading)),
}));

export const HIRAGANA_EXAMPLES: Record<string, KanaPronunciationExample> = {
  a: { word: 'あいさつ', reading: 'あいさつ', meaning: '인사' },
  i: { word: 'いぬ', reading: 'いぬ', meaning: '개' },
  u: { word: 'うみ', reading: 'うみ', meaning: '바다' },
  e: { word: 'えき', reading: 'えき', meaning: '역' },
  o: { word: 'おちゃ', reading: 'おちゃ', meaning: '차' },
  ka: { word: 'かさ', reading: 'かさ', meaning: '우산' },
  ki: { word: 'きく', reading: 'きく', meaning: '듣다' },
  ku: { word: 'くも', reading: 'くも', meaning: '구름' },
  ke: { word: 'けさ', reading: 'けさ', meaning: '오늘 아침' },
  ko: { word: 'こえ', reading: 'こえ', meaning: '목소리' },
  sa: { word: 'さくら', reading: 'さくら', meaning: '벚꽃' },
  shi: { word: 'しお', reading: 'しお', meaning: '소금' },
  su: { word: 'すし', reading: 'すし', meaning: '초밥' },
  se: { word: 'せんせい', reading: 'せんせい', meaning: '선생님' },
  so: { word: 'そら', reading: 'そら', meaning: '하늘' },
  ta: { word: 'たこ', reading: 'たこ', meaning: '문어' },
  chi: { word: 'ちず', reading: 'ちず', meaning: '지도' },
  tsu: { word: 'つき', reading: 'つき', meaning: '달' },
  te: { word: 'て', reading: 'て', meaning: '손' },
  to: { word: 'とり', reading: 'とり', meaning: '새' },
  na: { word: 'なつ', reading: 'なつ', meaning: '여름' },
  ni: { word: 'にほん', reading: 'にほん', meaning: '일본' },
  nu: { word: 'ぬの', reading: 'ぬの', meaning: '천' },
  ne: { word: 'ねこ', reading: 'ねこ', meaning: '고양이' },
  no: { word: 'のり', reading: 'のり', meaning: '김' },
  ha: { word: 'はな', reading: 'はな', meaning: '꽃' },
  hi: { word: 'ひと', reading: 'ひと', meaning: '사람' },
  fu: { word: 'ふね', reading: 'ふね', meaning: '배' },
  he: { word: 'へや', reading: 'へや', meaning: '방' },
  ho: { word: 'ほし', reading: 'ほし', meaning: '별' },
  ma: { word: 'まち', reading: 'まち', meaning: '마을' },
  mi: { word: 'みみ', reading: 'みみ', meaning: '귀' },
  mu: { word: 'むし', reading: 'むし', meaning: '벌레' },
  me: { word: 'め', reading: 'め', meaning: '눈' },
  mo: { word: 'もり', reading: 'もり', meaning: '숲' },
  ya: { word: 'やま', reading: 'やま', meaning: '산' },
  yu: { word: 'ゆき', reading: 'ゆき', meaning: '눈' },
  yo: { word: 'よる', reading: 'よる', meaning: '밤' },
  ra: { word: 'らいねん', reading: 'らいねん', meaning: '내년' },
  ri: { word: 'りんご', reading: 'りんご', meaning: '사과' },
  ru: { word: 'るす', reading: 'るす', meaning: '부재중' },
  re: { word: 'れい', reading: 'れい', meaning: '예시' },
  ro: { word: 'ろく', reading: 'ろく', meaning: '여섯' },
  wa: { word: 'わたし', reading: 'わたし', meaning: '나' },
  wo: { word: 'ほんをよむ', reading: 'ほんをよむ', meaning: '책을 읽다' },
  n: { word: 'パン', reading: 'パン', meaning: '빵' },
};

export const KATAKANA_EXAMPLES: Record<string, KanaPronunciationExample> = {
  a: { word: 'アイス', reading: 'アイス', meaning: '아이스크림' },
  i: { word: 'インク', reading: 'インク', meaning: '잉크' },
  u: { word: 'ウイスキー', reading: 'ウイスキー', meaning: '위스키' },
  e: { word: 'エアコン', reading: 'エアコン', meaning: '에어컨' },
  o: { word: 'オレンジ', reading: 'オレンジ', meaning: '오렌지' },
  ka: { word: 'カメラ', reading: 'カメラ', meaning: '카메라' },
  ki: { word: 'キロ', reading: 'キロ', meaning: '킬로' },
  ku: { word: 'クラス', reading: 'クラス', meaning: '수업' },
  ke: { word: 'ケーキ', reading: 'ケーキ', meaning: '케이크' },
  ko: { word: 'コーヒー', reading: 'コーヒー', meaning: '커피' },
  sa: { word: 'サラダ', reading: 'サラダ', meaning: '샐러드' },
  shi: { word: 'シャツ', reading: 'シャツ', meaning: '셔츠' },
  su: { word: 'スキー', reading: 'スキー', meaning: '스키' },
  se: { word: 'セーター', reading: 'セーター', meaning: '스웨터' },
  so: { word: 'ソファ', reading: 'ソファ', meaning: '소파' },
  ta: { word: 'タクシー', reading: 'タクシー', meaning: '택시' },
  chi: { word: 'チーズ', reading: 'チーズ', meaning: '치즈' },
  tsu: { word: 'ツアー', reading: 'ツアー', meaning: '투어' },
  te: { word: 'テレビ', reading: 'テレビ', meaning: '텔레비전' },
  to: { word: 'トマト', reading: 'トマト', meaning: '토마토' },
  na: { word: 'ナイフ', reading: 'ナイフ', meaning: '나이프' },
  ni: { word: 'ニュース', reading: 'ニュース', meaning: '뉴스' },
  nu: { word: 'ヌードル', reading: 'ヌードル', meaning: '누들' },
  ne: { word: 'ネクタイ', reading: 'ネクタイ', meaning: '넥타이' },
  no: { word: 'ノート', reading: 'ノート', meaning: '노트' },
  ha: { word: 'ハンバーガー', reading: 'ハンバーガー', meaning: '햄버거' },
  hi: { word: 'ヒーター', reading: 'ヒーター', meaning: '히터' },
  fu: { word: 'フォーク', reading: 'フォーク', meaning: '포크' },
  he: { word: 'ヘルメット', reading: 'ヘルメット', meaning: '헬멧' },
  ho: { word: 'ホテル', reading: 'ホテル', meaning: '호텔' },
  ma: { word: 'マスク', reading: 'マスク', meaning: '마스크' },
  mi: { word: 'ミルク', reading: 'ミルク', meaning: '우유' },
  mu: { word: 'ムービー', reading: 'ムービー', meaning: '영화' },
  me: { word: 'メール', reading: 'メール', meaning: '메일' },
  mo: { word: 'モデル', reading: 'モデル', meaning: '모델' },
  ya: { word: 'ヤード', reading: 'ヤード', meaning: '야드' },
  yu: { word: 'ユニフォーム', reading: 'ユニフォーム', meaning: '유니폼' },
  yo: { word: 'ヨガ', reading: 'ヨガ', meaning: '요가' },
  ra: { word: 'ラジオ', reading: 'ラジオ', meaning: '라디오' },
  ri: { word: 'リモコン', reading: 'リモコン', meaning: '리모컨' },
  ru: { word: 'ルール', reading: 'ルール', meaning: '규칙' },
  re: { word: 'レストラン', reading: 'レストラン', meaning: '레스토랑' },
  ro: { word: 'ロボット', reading: 'ロボット', meaning: '로봇' },
  wa: { word: 'ワイン', reading: 'ワイン', meaning: '와인' },
  wo: { word: 'ヲタク', reading: 'ヲタク', meaning: '오타쿠' },
  n: { word: 'パン', reading: 'パン', meaning: '빵' },
};
