/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/bootstrap-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 초기 관리자 계정 설정 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        token: string;
                    };
                };
            };
            responses: {
                /** @description 관리자 설정 완료 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericDataResponse"];
                    };
                };
                /** @description 초기화 토큰 거부 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원 및 로그인 현황 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 회원 관리 데이터 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericListResponse"];
                    };
                };
                /** @description 관리자 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description 관리자 권한 필요 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 관리자 대시보드 HTML */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 대시보드 HTML */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/weekly-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주간 리포트 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 주간 리포트 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericDataResponse"];
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description 리포트 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        /** 주간 리포트 즉시 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 생성 결과 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericCreatedResponse"];
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audio/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 승인된 Google TTS 오디오 배치 실행 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "x-audio-batch-approval"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default false */
                        execute?: boolean;
                        dry_run?: boolean;
                        batch?: number;
                        /** @enum {string} */
                        provider?: "google";
                        /** @enum {string} */
                        level?: "N5" | "N4" | "N3";
                        force_regenerate?: boolean;
                    };
                };
            };
            responses: {
                /** @description 큐 실행 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericDataResponse"];
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audio/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TTS provider 운영 연결 상태 확인 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description provider 상태 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericDataResponse"];
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audio/qa/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 30개 QA 샘플 오디오 일괄 생성 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "x-audio-batch-approval"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider?: "cloudflare" | "google" | "voicevox";
                        force?: boolean;
                    };
                };
            };
            responses: {
                /** @description QA 샘플 생성 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericDataResponse"];
                    };
                };
                /** @description 인증 필요 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenericDataResponse: {
            data?: unknown;
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        ProblemDetail: {
            type: string;
            title: string;
            status: number;
            detail: string;
        };
        GenericListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        SourcesListResponse: {
            data: {
                [key: string]: unknown;
            }[];
        };
        CurriculumListResponse: {
            data: {
                [key: string]: unknown;
            }[];
        };
        CurriculumWeekResponse: {
            data: {
                [key: string]: unknown;
            };
        };
        ContentVersionResponse: {
            data: {
                version: string;
                generatedAt: string;
                tables: {
                    [key: string]: {
                        count: number;
                        updatedAt: number | null;
                    };
                };
            };
        };
        VocabListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        VocabSearchResponse: {
            data: {
                [key: string]: unknown;
            }[];
        };
        VocabSingleResponse: {
            data: {
                [key: string]: unknown;
            };
        };
        GrammarListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        GrammarSingleResponse: {
            data: {
                [key: string]: unknown;
            };
        };
        KanjiListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        KanjiSingleResponse: {
            data: {
                [key: string]: unknown;
            };
        };
        SentencesListResponse: {
            data: {
                [key: string]: unknown;
            }[];
            meta?: {
                limit: number;
                hasMore: boolean;
                nextCursor?: string;
            };
        };
        SentencesSearchResponse: {
            data: {
                [key: string]: unknown;
            }[];
        };
        SentencesSingleResponse: {
            data: {
                [key: string]: unknown;
            };
        };
        GenericCreatedResponse: {
            data?: unknown;
        };
        NaturalTranslateResponse: {
            data: {
                sourceText: string;
                translatedText: string;
                readingHint?: string;
                nuanceKo?: string;
                alternatives?: string[];
                model: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
