export type AudioSurface =
  | 'kana'
  | 'vocab'
  | 'kanji'
  | 'sentence'
  | 'example'
  | 'listening'
  | 'qa';

/** Pronunciation is generated by Google only; R2 is never a playback source. */
export type AudioPolicySource = 'google';

export interface AudioPlaybackPolicy {
  surface: AudioSurface;
  primary: AudioPolicySource;
  fallback: null;
  preferGoogleVoice: true;
  slow: boolean;
  descriptionKo: string;
}

export const AUDIO_PLAYBACK_POLICIES: Record<AudioSurface, AudioPlaybackPolicy> = {
  kana: {
    surface: 'kana',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: true,
    descriptionKo: '문자 발음은 Google 음성만 사용한다. R2와 다른 provider는 사용하지 않는다.',
  },
  vocab: {
    surface: 'vocab',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: false,
    descriptionKo: '단어 발음은 Google 음성만 사용한다. R2 fallback은 허용하지 않는다.',
  },
  kanji: {
    surface: 'kanji',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: true,
    descriptionKo: '한자 읽기는 Google 음성만 사용하고 느린 재생을 허용한다.',
  },
  sentence: {
    surface: 'sentence',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: false,
    descriptionKo: '문장/예문은 Google 음성만 사용한다. R2 음원은 사용하지 않는다.',
  },
  example: {
    surface: 'example',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: false,
    descriptionKo: '예문은 Google 음성만 사용한다. R2 음원은 사용하지 않는다.',
  },
  listening: {
    surface: 'listening',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: false,
    descriptionKo: '청해 퀴즈는 Google 음성만 사용한다. R2 음원은 사용하지 않는다.',
  },
  qa: {
    surface: 'qa',
    primary: 'google',
    fallback: null,
    preferGoogleVoice: true,
    slow: false,
    descriptionKo: 'TTS QA도 Google 음성만 사용한다. 고정 R2 QA 샘플은 사용하지 않는다.',
  },
};

export function getAudioPlaybackPolicy(surface: AudioSurface | undefined): AudioPlaybackPolicy {
  return AUDIO_PLAYBACK_POLICIES[surface ?? 'vocab'];
}

export function usesGoogleAudio(surface: AudioSurface | undefined): boolean {
  return getAudioPlaybackPolicy(surface).primary === 'google';
}
