export type LocalizedText = Readonly<{ ko: string; ja: string; en: string }>;

export const localized = (ko: string, ja: string, en: string): LocalizedText => ({ ko, ja, en });

export interface VocabularySpec {
  word: string;
  sentence: string;
  answer: LocalizedText;
  distractors: readonly [LocalizedText, LocalizedText, LocalizedText];
}

export interface GrammarSpec {
  sentence: string;
  answer: LocalizedText;
  distractors: readonly [LocalizedText, LocalizedText, LocalizedText];
  explanation: LocalizedText;
}

export interface KanjiSpec {
  word: string;
  reading: string;
  meaning: LocalizedText;
  distractors: readonly [string, string, string];
}

export interface ListeningSpec {
  audioScriptJa: string;
  question: LocalizedText;
  answer: LocalizedText;
  distractors: readonly [LocalizedText, LocalizedText, LocalizedText];
  explanation: LocalizedText;
}

const t = localized;

export const N2_VOCABULARY_SPECS: readonly VocabularySpec[] = [
  { word: '改めて', sentence: '計画の内容を改めて検討した。', answer: t('다시 한번', 'もう一度', 'once again'), distractors: [t('처음으로', '初めて', 'for the first time'), t('다른 기회에', '別の機会に', 'on another occasion'), t('세심하게', '念入りに', 'carefully')] },
  { word: '満たす', sentence: '条件を満たす応募者に連絡します。', answer: t('조건에 맞다', '条件に合う', 'meet the conditions'), distractors: [t('조건을 확인하다', '条件を確認する', 'check the conditions'), t('조건을 능가하다', '条件を上回る', 'exceed the conditions'), t('조건을 정비하다', '条件を整える', 'arrange the conditions')] },
  { word: '具体的', sentence: '新しい制度について具体的な説明をお願いします。', answer: t('자세하고 명확한', '詳しくはっきりした', 'detailed and clear'), distractors: [t('실용성을 중시한', '実用的な', 'practical'), t('개별 사례에 한정된', '個別的な', 'individualized'), t('객관적 입장의', '客観的な', 'objective')] },
  { word: '可能性', sentence: 'この薬には眠くなる可能性がある。', answer: t('일어날 수 있음', '起こり得ること', 'a chance of occurring'), distractors: [t('반드시 일어나는 필연성', '必ず起こる必然性', 'inevitability'), t('현실화하기 쉬운 정도', '実現のしやすさ', 'feasibility'), t('예측이 맞을 확실성', '予測の確実性', 'certainty of a forecast')] },
  { word: '予測', sentence: '過去のデータから来年の売上げを予測する。', answer: t('미리 예상하다', 'あらかじめ見当をつける', 'forecast in advance'), distractors: [t('현재 수치를 측정하다', '現在の数値を測定する', 'measure current figures'), t('과거 원인을 추론하다', '過去の原因を推測する', 'infer a past cause'), t('현재 자료를 집계하다', '現在の資料を集計する', 'aggregate current data')] },
  { word: '負担', sentence: '修理にかかる費用は会社が負担する。', answer: t('비용을 맡다', '費用を受け持つ', 'bear the cost'), distractors: [t('비용을 나누어 청구하다', '費用を分割請求する', 'bill the cost in installments'), t('비용을 일단 대납하다', '費用を一時的に立て替える', 'advance the cost temporarily'), t('비용의 일부를 보상하다', '費用の一部を補償する', 'reimburse part of the cost')] },
  { word: '受け入れる', sentence: 'チームは彼の新しい提案を受け入れた。', answer: t('인정하여 채택하다', '認めて採用する', 'accept and adopt'), distractors: [t('검토 대상으로만 남겨 두다', '検討対象として保留する', 'retain for consideration'), t('일부를 수정해 돌려보내다', '一部を修正して返す', 'return with revisions'), t('내용에는 동의하지만 채택을 보류하다', '内容に同意しつつ採用を保留する', 'agree but defer adoption')] },
  { word: '中断', sentence: '機械の点検のため、作業を一時中断した。', answer: t('도중에서 잠시 멈추다', '途中で一時止める', 'pause temporarily'), distractors: [t('작업 시작을 뒤로 미루다', '作業の開始を後ろに延ばす', 'postpone the start'), t('작업을 완전히 취소하다', '作業を完全に中止する', 'cancel permanently'), t('작업 공정을 줄여 진행하다', '作業工程を短縮して続ける', 'continue with fewer steps')] },
  { word: '整理', sentence: '会議の前に関連資料を整理しておいた。', answer: t('분류하여 정돈하다', '分類して整える', 'sort and arrange'), distractors: [t('핵심 내용만 요약하다', '要点だけを要約する', 'summarize key points'), t('현재 순서 그대로 보관하다', '現在の順番のまま保管する', 'archive in the current order'), t('필요한 자료만 선별하다', '必要な資料だけを選別する', 'select only needed materials')] },
  { word: '貢献', sentence: 'その企業は雇用を増やし、地域に貢献している。', answer: t('도움이 되다', '役に立つ', 'contribute usefully'), distractors: [t('지역과 공동 사업을 운영하다', '地域と共同事業を運営する', 'run a joint local project'), t('지역의 지원을 받다', '地域から支援を受ける', 'receive local support'), t('지역에 고용 결과를 보고하다', '地域に雇用結果を報告する', 'report employment results locally')] },
  { word: 'あいまい', sentence: '担当者の返事はあいまいで、結論が分からなかった。', answer: t('분명하지 않은', 'はっきりしない', 'unclear'), distractors: [t('추상적인 말로만 된', '抽象的な言葉だけの', 'abstractly worded'), t('개략만 담은', '概略だけを述べた', 'only outlining'), t('완곡하게 표현한', '遠回しに表現した', 'indirectly phrased')] },
  { word: '避ける', sentence: '通勤ラッシュの混雑を避けるため、早く家を出た。', answer: t('가까이하지 않다', '近づかないようにする', 'keep away from'), distractors: [t('혼잡을 여러 시간대로 분산하다', '混雑を複数の時間帯に分散する', 'spread congestion across times'), t('혼잡의 정도를 완화하다', '混雑の程度を緩和する', 'ease congestion'), t('혼잡 구간을 빨리 통과하다', '混雑区間を早く通過する', 'pass quickly through congestion')] },
  { word: '取り消す', sentence: '予定が変わったので、セミナーの申し込みを取り消した。', answer: t('무효로 하다', '無効にする', 'cancel'), distractors: [t('신청 내용을 수정하다', '申し込みの内容を修正する', 'revise the application'), t('신청의 처리를 연기하다', '申し込みの処理を延期する', 'defer processing'), t('신청을 다시 제출하다', '申し込みを再提出する', 'resubmit the application')] },
  { word: '需要', sentence: '環境に優しい商品の需要が増えている。', answer: t('필요로 하는 사람의 요구', '必要とする人の求め', 'consumer demand'), distractors: [t('시장에 공급된 상품의 양', '市場に供給された商品量', 'market supply'), t('실제로 판매된 상품의 양', '実際に販売された商品量', 'sales volume'), t('보관 중인 상품의 수량', '保管中の商品数', 'inventory level')] },
  { word: '共有', sentence: '作業の進み具合をチーム全員で共有した。', answer: t('여러 사람이 같은 정보를 갖다', '複数の人が同じ情報を持つ', 'share the same information'), distractors: [t('정보를 하나의 문서로 집약하다', '情報を一つの文書に集約する', 'consolidate information'), t('정보를 외부에 공개하다', '情報を外部に公開する', 'publish information externally'), t('정보를 후임자에게 인계하다', '情報を後任者に引き継ぐ', 'hand information to a successor')] },
] as const;

export const N1_VOCABULARY_SPECS: readonly VocabularySpec[] = [
  { word: '顕著', sentence: '対策後、問い合わせ数に顕著な増加が見られた。', answer: t('뚜렷하게 눈에 띄는', 'はっきり目立つ', 'clearly noticeable'), distractors: [t('급격하게 변화한', '急激に変化した', 'rapidly changed'), t('넓은 범위에 퍼진', '広範囲に及んだ', 'widespread'), t('분석상 확실한', '分析上確実な', 'analytically certain')] },
  { word: '妥当', sentence: '第三者の意見も含めると、その判断は妥当だ。', answer: t('적절하고 합리적인', '適切で合理的な', 'appropriate and reasonable'), distractors: [t('법적 요건만 충족한', '法的要件だけを満たす', 'merely legally valid'), t('실행 가능성이 높은', '実行可能性が高い', 'highly feasible'), t('양쪽 의견을 균등하게 반영한', '両者の意見を均等に反映した', 'evenly balanced')] },
  { word: '懸念', sentence: '専門家は、急な制度変更が混乱を招くと懸念している。', answer: t('좋지 않은 결과를 우려하다', '悪い結果を心配する', 'fear an adverse outcome'), distractors: [t('부정적 결과를 예측만 하다', '悪い結果を予測するだけ', 'merely predict an adverse outcome'), t('변경의 의도를 의심하다', '変更の意図を疑う', 'doubt the intent of the change'), t('혼란 가능성을 공식 경고하다', '混乱の可能性を正式に警告する', 'formally warn of possible confusion')] },
  { word: '踏襲', sentence: '新しい代表も、前任者の基本方針を踏襲すると表明した。', answer: t('기존 방식을 이어받다', '従来の方式を受け継ぐ', 'follow an established approach'), distractors: [t('기존 방침을 참고만 하다', '従来の方針を参考にするだけ', 'only consult the old policy'), t('기존 방침의 일부를 개정하다', '従来の方針を一部改定する', 'partially revise the policy'), t('기존 방침을 공식 규정으로 문서화하다', '従来の方針を正式規程にする', 'codify the policy')] },
  { word: '遂行', sentence: '予期せぬ問題が生じたが、チームは任務を遂行した。', answer: t('끝까지 실행하다', '最後までやり遂げる', 'carry through to completion'), distractors: [t('임무의 진척만 관리하다', '任務の進捗だけを管理する', 'only manage progress'), t('임무를 다른 팀에 위임하다', '任務を別のチームに委任する', 'delegate the mission'), t('중단된 임무를 재개하다', '中断した任務を再開する', 'resume the mission')] },
  { word: '模索', sentence: '自治体は空き家を活用する新たな方法を模索している。', answer: t('해결책을 찾으려 시도하다', '解決策を探り求める', 'search for a solution'), distractors: [t('기존 방안들을 비교 평가하다', '既存案を比較評価する', 'compare existing options'), t('현재 방식의 효과를 검증하다', '現行方式の効果を検証する', 'verify the current method'), t('후보 하나를 시범 채택하다', '候補の一つを試行採用する', 'pilot one candidate')] },
  { word: '是正', sentence: '監査後、会社は不適切な管理手順を是正した。', answer: t('잘못된 상태를 바로잡다', '間違った状態を正す', 'correct an improper state'), distractors: [t('절차의 수치만 조정하다', '手順の数値だけを調整する', 'adjust only parameters'), t('부족한 절차를 보완하다', '不足する手順を補完する', 'supplement missing steps'), t('부서별 절차를 표준화하다', '部門別の手順を標準化する', 'standardize procedures')] },
  { word: '促進', sentence: '研究機関と企業の交流を促進する制度が始まった。', answer: t('더 빨리 진행되도록 돕다', 'より早く進むよう促す', 'encourage faster progress'), distractors: [t('교류 대상의 범위를 넓히다', '交流対象の範囲を広げる', 'broaden participation'), t('교류의 현재 속도를 유지하다', '交流の現在の速度を保つ', 'maintain the current pace'), t('교류 진행 상황을 관찰하다', '交流の進捗を監視する', 'monitor progress')] },
  { word: '把握', sentence: '会議の前に、各部署の進捗を正確に把握しておきたい。', answer: t('정확히 이해하다', '正確につかむ', 'grasp accurately'), distractors: [t('진행 상황을 요약하다', '進捗を要約する', 'summarize progress'), t('진행 상황을 추론하다', '進捗を推定する', 'infer progress'), t('진행 상황을 기록하다', '進捗を記録する', 'record progress')] },
  { word: '脆弱', sentence: '調査で、旧システムの脆弱な部分が明らかになった。', answer: t('약하고 손상되기 쉬운', '弱く壊れやすい', 'weak and vulnerable'), distractors: [t('작은 변화에도 불안정한', '小さな変化でも不安定な', 'unstable under small changes'), t('예비 구성이 부족한', '予備構成が不足した', 'lacking redundancy'), t('기술적으로 노후한', '技術的に老朽化した', 'technically obsolete')] },
  { word: '逸脱', sentence: '一部の数値が長期的な傾向から逸脱していた。', answer: t('기준이나 경향에서 벗어나다', '基準や傾向から外れる', 'deviate from a norm'), distractors: [t('경향 범위 안에서 변동하다', '傾向の範囲内で変動する', 'fluctuate within the trend'), t('일시적 이상 후 기준으로 돌아오다', '一時的に異常になり基準へ戻る', 'briefly vary then return'), t('장기 경향이 반전되다', '長期傾向が逆転する', 'reverse the long-term trend')] },
  { word: '配慮', sentence: '計画の実施に当たっては、周辺の住民への配慮が欠かせない。', answer: t('상대의 상황을 생각한 배려', '相手の事情を考えた気配り', 'thoughtful consideration'), distractors: [t('계획을 미리 알리는 절차', '計画を事前に通知する手続き', 'advance notification'), t('주민의 공식 동의를 받는 절차', '住民の正式な同意を得る手続き', 'formal consent'), t('주민에게 손실을 보상하는 조치', '住民の損失を補償する措置', 'loss compensation')] },
  { word: '概略', sentence: '報告書の冒頭で、調査の概略を説明した。', answer: t('전체의 대략적인 내용', '全体のおおよその内容', 'a general outline'), distractors: [t('조사의 핵심 결론만 요약한 내용', '調査の主結論だけを要約した内容', 'summary of conclusions'), t('추상적 개념을 설명한 내용', '抽象的な概念を説明した内容', 'conceptual explanation'), t('보고서의 항목만 나열한 목차', '報告書の項目だけを並べた目次', 'table of contents')] },
  { word: '円滑', sentence: '新しい手順を導入してから、部署間の連携が円滑になった。', answer: t('문제없이 부드럽게 진행되는', '滞りなくスムーズな', 'smooth and trouble-free'), distractors: [t('연계 속도가 전반적으로 빨라진', '連携の速度が全体に早くなった', 'generally faster'), t('부서별 연계 방식이 표준화된', '部署別の連携方法が標準化された', 'standardized'), t('연계 절차가 자동화된', '連携手順が自動化された', 'automated')] },
  { word: '抑制', sentence: '需要が集中する時間帯の電力消費を抑制する必要がある。', answer: t('늘어나지 않도록 억제하다', '増えないように抑える', 'restrain from increasing'), distractors: [t('사용량의 변동을 안정화하다', '使用量の変動を安定化する', 'stabilize fluctuations'), t('피크 수요를 다른 시간대로 이동하다', 'ピーク需要を他の時間帯へ移す', 'shift peak demand'), t('전력 손실만 줄이다', '電力損失だけを減らす', 'reduce transmission loss')] },
] as const;

const g = (ja: string, ko: string, en: string): LocalizedText => t(ko, ja, en);

export const N2_GRAMMAR_SPECS: readonly GrammarSpec[] = [
  { sentence: '彼は十年もこの地域に住み、自治会の相談役も務めているから、土地の事情に詳しい＿＿＿。', answer: g('に違いない', '틀림없다', 'must surely be'), distractors: [g('はずがない', '〜할 리가 없다', 'cannot possibly be'), g('ことはない', '할 필요는 없다', 'there is no need'), g('つもりはない', '의향은 없다', 'have no intention')], explanation: t('장기 거주와 자치회 상담역이라는 두 근거가 강한 긍정 추론을 뒷받침하므로 「に違いない」가 알맞습니다.', '長年の居住と自治会の相談役という二つの根拠が強い肯定的推論を支えるため「に違いない」が適切です。', 'Long residence plus service as a neighborhood adviser supports the strong positive conclusion ni chigai nai.') },
  { sentence: '健康のために甘い物を控えているが、まったく食べない＿＿＿。', answer: g('わけではない', '것은 아니다', 'it is not that'), distractors: [g('に決まっている', '분명히 그렇다', 'it is certain'), g('ことになっている', '규정상 그렇다', 'it is arranged'), g('べきではない', '해서는 안 된다', 'should not')], explanation: t('부분적으로 한다는 사실을 부정하지 않고 전면적 부정만 한계짓습니다.', '部分的に食べる可能性を残し、全面的な否定だけを打ち消します。', 'Wake dewa nai rejects only the absolute claim, not occasional eating.') },
  { sentence: 'この施設では規則により、すべての来館者が入場前に受付で本人確認を受ける＿＿＿。', answer: g('ことになっている', '규정으로 정해져 있다', 'it is stipulated'), distractors: [g('つもりである', '〜할 생각이다', 'intend to'), g('ことになりかけている', '규정으로 정해지려는 중이다', 'is about to become a rule'), g('ことに決めたばかりである', '방금 받기로 결정했다', 'have only just decided to receive it')], explanation: t('시설의 규칙으로 정해진 의무이므로 「ことになっている」을 씁니다.', '施設の規則として定められた義務なので「ことになっている」を使います。', 'Koto ni natte iru expresses an established institutional rule.') },
  { sentence: 'この写真を見返す＿＿＿、毎回、学生時代の旅行を思い出す。', answer: g('たびに', '〜할 때마다', 'whenever'), distractors: [g('うちに', '〜하는 동안에', 'while'), g('ところに', '〜하는 곳에', 'at the point where'), g('かわりに', '〜대신에', 'instead of')], explanation: t('「매번」이라는 단서가 있으므로 사진을 다시 볼 때마다 추억이 난다는 「たびに」가 맞습니다.', '「毎回」という手掛かりがあるため、写真を見返すたびに思い出すという「たびに」が適切です。', 'The explicit “every time” cue makes tabi ni the unique expression for the recurring memory.') },
  { sentence: '大雪のため、今夜の便は欠航する＿＿＿。', answer: g('おそれがある', '우려가 있다', 'there is a risk'), distractors: [g('にすぎない', '〜에 불과하다', 'nothing more than'), g('ようになる', '〜하게 된다', 'come to or start to'), g('わけにはいかない', '〜할 수는 없다', 'cannot do')], explanation: t('대설로 인한 부정적 가능성을 나타내므로 「おそれがある」가 적절합니다.', '大雪による望ましくない可能性を表すため「おそれがある」が適切です。', 'Osore ga aru marks an undesirable possibility.') },
  { sentence: '新人の意見が積極的だったの＿＿＿、経験者からは慎重な意見が多かった。', answer: g('に対して', '〜와 대비하여', 'in contrast to'), distractors: [g('について', '〜에 관하여', 'about'), g('によって', '〜에 의해', 'by means of'), g('において', '〜에서', 'in the setting of')], explanation: t('신입의 적극적인 의견과 경력자의 신중한 의견을 대조하므로 「に対して」가 맞습니다.', '新人の積極的な意見と経験者の慎重な意見を対比しているため「に対して」が合います。', 'Ni taishite explicitly contrasts the newcomers’ proactive views with the experienced members’ cautious views.') },
  { sentence: 'この店では、食料品＿＿＿、日用品や文房具まで扱っている。', answer: g('に限らず', '〜에 한정되지 않고', 'not limited to'), distractors: [g('に先立ち', '〜에 앞서', 'prior to'), g('に沿って', '〜을 따라서', 'in line with'), g('に反して', '〜와 반대로', 'contrary to')], explanation: t('취급 품목이 식료품에 한정되지 않고 생활용품과 문구류까지 넓어진다는 뜻이므로 「に限らず」를 씁니다.', '取扱品が食料品だけでなく日用品や文房具にも広がるため「に限らず」を使います。', 'Ni kagirazu expands the store range beyond food to daily goods and stationery.') },
  { sentence: '十分に準備した＿＿＿、本番では緊張してしまった。', answer: g('ものの', '〜하였지만', 'although'), distractors: [g('以上は', '〜한 이상은', 'now that'), g('際に', '〜할 때에', 'on the occasion of'), g('ついでに', '〜하는 김에', 'while at it')], explanation: t('충분히 준비했다는 사실과 실전의 결과가 역접이므로 「ものの」가 알맞습니다.', '十分な準備と本番の結果が逆接なので「ものの」が適切です。', 'Monono connects a fact with an unexpected contrasting result.') },
  { sentence: '参加者の経験＿＿＿、クラスを三つに分けます。', answer: g('に応じて', '〜에 맞추어', 'according to'), distractors: [g('に限って', '〜에 한해', 'only for'), g('に反して', '〜와 반대로', 'contrary to'), g('に沿って', '〜을 따라', 'along')], explanation: t('경험의 정도에 맞춰 반을 나누므로 「に応じて」가 맞습니다.', '経験の程度に合わせてクラスを分けるので「に応じて」が合います。', 'Ni ojite means the grouping changes according to experience.') },
  { sentence: '後ろの人にもはっきり聞こえる＿＿＿、話す速さは変えずに声量だけを上げてください。', answer: g('ように', '〜하도록', 'so that'), distractors: [g('ようでは', '〜하는 상태라면', 'if things are such that'), g('ほどなら', '〜정도라면', 'if it is to that extent'), g('かぎりで', '〜하는 한계에서', 'within the limit')], explanation: t('뒤 사람에게도 목소리가 들리게 하는 목적을 나타내므로 「ように」를 씁니다.', '後ろの人にも声が聞こえるようにする目的なので「ように」を使います。', 'You ni marks the intended result that others can hear the speaker’s voice.') },
  { sentence: '詳細が決まり＿＿＿、登録者にメールでお知らせします。', answer: g('次第', '〜하는 즉시', 'as soon as'), distractors: [g('以上', '〜한 이상', 'now that'), g('最中', '〜하는 한창', 'in the middle of'), g('ところ', '〜하는 중', 'just at the point')], explanation: t('세부 사항이 결정된 직후 알린다는 순차이므로 「次第」가 적절합니다.', '詳細が決まった直後に通知する順序なので「次第」が適切です。', 'Shidai means the notification follows immediately after the decision.') },
  { sentence: '重要な問題を議論している＿＿＿、非常ベルが鳴った。', answer: g('最中に', '〜하는 한창에', 'in the middle of'), distractors: [g('うえで', '〜한 후에', 'after doing'), g('かたわら', '〜하는 한편', 'while also'), g('ついでに', '〜하는 김에', 'while at it')], explanation: t('토론이 진행 중인 시점에 알람이 울렸으므로 「最中に」가 맞습니다.', '議論の進行中にベルが鳴ったので「最中に」が合います。', 'Saichu ni identifies an interruption during an ongoing activity.') },
  { sentence: 'この町は昔から水路が発達していた＿＿＿、「水の都」と呼ばれている。', answer: g('ことから', '〜라는 사실에서', 'from the fact that'), distractors: [g('ことなく', '〜하지 않고', 'without doing'), g('ことには', '〜라는 사실에는', 'as for the fact that'), g('ものの', '〜이기는 하지만', 'although')], explanation: t('별칭의 근거가 수로의 발달이라는 사실이므로 「ことから」을 씁니다.', '別名の根拠が水路の発達という事実なので「ことから」を使います。', 'Koto kara introduces the fact that motivates the nickname.') },
  { sentence: '年齢＿＿＿、能力のある人に応募してほしい。', answer: g('にかかわらず', '〜와 관계없이', 'regardless of'), distractors: [g('につれて', '〜에 따라', 'as'), g('にかぎって', '〜일 때에 한해', 'only when'), g('にあたって', '〜을 맞아', 'on the occasion of')], explanation: t('나이를 선발 조건으로 삼지 않는다는 뜻이므로 「にかかわらず」가 맞습니다.', '年齢を選考条件にしないという意味なので「にかかわらず」が合います。', 'Ni kakawarazu excludes age as a condition.') },
  { sentence: '生活が便利になる＿＿＿、家庭の電力使用量も増えていった。', answer: g('につれて', '〜에 따라서', 'as'), distractors: [g('によらず', '〜와 관계없이', 'regardless of'), g('に相違なく', '틀림없이', 'without doubt'), g('に反して', '〜와 반대로', 'contrary to')], explanation: t('편리함의 증가와 전력 사용량의 증가가 함께 변화하므로 「につれて」를 씁니다.', '便利さの増加と電力使用量の増加が並行して変化するため「につれて」を使います。', 'Ni tsurete links two changes that progress together.') },
] as const;

export const N1_GRAMMAR_SPECS: readonly GrammarSpec[] = [
  { sentence: '来月の東京公演＿＿＿、全国十二都市を回るツアーが始まる。', answer: g('を皮切りに', '〜을 시작으로', 'starting with'), distractors: [g('をよそに', '〜을 무시하고', 'ignoring'), g('を限りに', '〜을 한계로', 'ending with'), g('をもってすら', '〜로써조차', 'even by means of')], explanation: t('도쿄 공연이 연속 투어의 첫 기점이므로 「を皮切りに」가 알맞습니다.', '東京公演が連続するツアーの最初の契機なので「を皮切りに」が適切です。', 'O kawakiri ni marks the first event in a continuing series.') },
  { sentence: '兄が即断即決なの＿＿＿、弟は何を決めるにも時間がかかる。', answer: g('にひきかえ', '〜와는 반대로', 'in contrast to'), distractors: [g('と相まって', '〜와 더불어', 'combined with'), g('に即して', '〜에 맞추어', 'in accordance with'), g('にしては', '〜치고는', 'considering')], explanation: t('형의 즉각적인 판단과 동생의 신중함을 대조하므로 「にひきかえ」를 씁니다.', '兄の即断と弟の慎重さを対比するので「にひきかえ」を使います。', 'Ni hikikae contrasts the brothers sharply.') },
  { sentence: '研究チームは原因を明らかにす＿＿＿、そのための追加実験を開始した。', answer: g('べく', '〜하기 위하여', 'in order to'), distractors: [g('べくもなく', '〜할 수도 없고', 'unable to'), g('べからず', '〜해서는 안 되는데', 'must not'), g('まじく', '〜해서는 안 되며·〜할 리 없게', 'being impermissible or unlikely to')], explanation: t('「그 목적을 위한」 추가 실험이라고 명시되어 있으므로 목적을 나타내는 문어적 표현 「べく」가 맞습니다.', '「そのための」追加実験と明示されているため、目的を表す文語的な「べく」が合います。', 'The explicit “for that purpose” phrase makes beku the unique purpose construction.') },
  { sentence: '今から計画を立て直した＿＿＿、締め切りには間に合わない。', answer: g('ところで', '〜한다고 해도', 'even if'), distractors: [g('ところを', '〜하는 중에', 'when in the middle'), g('ところから', '〜한 것으로부터', 'from the fact'), g('ところまで', '〜하는 지점까지', 'up to the point')], explanation: t('지금 재계획해도 결과가 바뀌지 않는다는 가정적 양보입니다.', '今立て直しても結果は変わないという仮定的な譲歩です。', 'Ta tokoro de indicates that even taking the action would not change the result.') },
  { sentence: 'この記録映画の衝撃的な映像は、見る人の価値観を必ず揺さぶら＿＿＿。', answer: g('ずにはおかない', '반드시 〜하게 한다', 'inevitably causes'), distractors: [g('ないまでも', '〜하지는 않더라도', 'even if not'), g('ずじまいだ', '끝내 〜하지 못하다', 'end without doing'), g('ずに済む', '〜하지 않고 끝나다', 'get by without')], explanation: t('「반드시」라는 단서와 함께 영상이 관객의 가치관에 필연적으로 영향을 준다는 뜻이므로 「ずにはおかない」를 씁니다.', '「必ず」という手掛かりとともに、映像が観客の価値観へ必然的に影響することを表すため「ずにはおかない」を使います。', 'With the explicit “certainly” cue, zuniwa okanai uniquely expresses the inevitable effect on viewers.') },
  { sentence: '世界的なピアニストによる一夜限りの公演＿＿＿、会場は開演前から熱気に包まれていた。', answer: g('とあって', '〜이라는 특별한 상황이라', 'given the special circumstance'), distractors: [g('とはいえ', '〜이라고는 하지만', 'although'), g('といえども', '〜이라고 해도', 'even though'), g('ときたら', '〜이라면 말이야', 'when it comes to')], explanation: t('세계적 피아니스트의 단 하룻밤 공연이라는 특별한 사정이 열기의 이유입니다.', '世界的演奏家による一夜限りの公演という特別な事情が熱気の理由です。', 'To atte links the exceptional one-night performance to the expected excitement.') },
  { sentence: '地元の材料と伝統技法を生かした、この工房＿＿＿の製品だ。', answer: g('ならでは', '〜만의 특색이 있는', 'unique to'), distractors: [g('というより', '〜라기보다', 'rather than'), g('といえば', '〜라고 하면', 'speaking of'), g('に限らず', '〜뿐만 아니라', 'not limited to')], explanation: t('지역 소재와 전통 기법이 그 공방만의 독자적 특징임을 나타냅니다.', '地元の素材と伝統技法がその工房特有の長所であることを表します。', 'Naradewa emphasizes a quality unique to that workshop.') },
  { sentence: '彼の研究対象は、古代文学から当時の食文化＿＿＿幅広く及んでいる。', answer: g('に至るまで', '〜에 이르기까지', 'even extending to'), distractors: [g('に至っては', '〜에 관해서는', 'when it comes to'), g('に至るより', '〜에 이르기보다', 'rather than reaching'), g('に至ったら', '〜에 다다르면', 'if it reaches')], explanation: t('「〜에서 〜에 이르기까지」의 범위를 나타내므로 「に至るまで」가 유일하게 맞습니다.', '「〜から〜に至るまで」という範囲を表すため「に至るまで」が適切です。', 'The kara ... ni itaru made construction uniquely marks the full research range.') },
  { sentence: '記録的な暴雨により、大会の主催者は延期＿＿＿。', answer: g('を余儀なくされた', '〜을 피할 수 없게 강요받았다', 'was forced to'), distractors: [g('に引き替えた', '〜와 바꾸었다', 'exchanged for'), g('をものともしなかった', '〜을 아랑곳하지 않았다', 'ignored'), g('に足りるとした', '〜으로 충분하다고 했다', 'deemed sufficient')], explanation: t('폭우로 인해 주최자에게 연기 외의 선택지가 없었음을 나타냅니다.', '暴雨のため主催者に延期以外の選択肢がなかったことを表します。', 'O yogi naku sareta expresses an externally forced decision.') },
  { sentence: 'この資料が計画の基礎であることは全員が承知しており、今さら説明する＿＿＿。', answer: g('までもない', '〜할 필요까지도 없다', 'it goes without saying'), distractors: [g('だけのことはある', '〜할 만한 가치가 있다', 'is worth doing'), g('に越したことはない', '〜하는 편이 가장 좋다', 'it is best to do'), g('わけにはいかない', '사정상 〜할 수는 없다', 'cannot do under the circumstances')], explanation: t('전원이 이미 아는 사실이라고 명시되어 있으므로 굳이 설명할 필요가 없다는 「までもない」가 맞습니다.', '全員がすでに承知していると明示されているため、あえて説明する必要がないという「までもない」が適切です。', 'Because everyone already knows the fact, made mo nai uniquely says no explanation is necessary.') },
  { sentence: 'ふと気づくと、特に意識せず窓の外を見る＿＿＿、今後の進め方を考えていた。', answer: g('ともなく', '특별한 의도 없이', 'without consciously'), distractors: [g('べくもなく', '〜할 수도 없이', 'being unable to'), g('が早いか', '〜하자마자', 'as soon as'), g('にあって', '〜한 상황에서', 'in the situation of')], explanation: t('「특별히 의식하지 않고」라는 단서가 있으므로 창밖을 뚜렷한 목적 없이 보고 있었다는 「ともなく」가 맞습니다.', '「特に意識せず」という手掛かりがあるため、明確な目的もなく窓の外を見ていたことを表す「ともなく」が適切です。', 'The explicit “without consciously intending to” cue makes tomonaku the unique expression for the absent-minded gaze.') },
  { sentence: 'ご報告＿＿＿、完成した試作品をお持ちしました。', answer: g('かたがた', '〜를 겸하여', 'while also'), distractors: [g('をよそに', '〜을 개의치 않고', 'regardless of'), g('に即して', '〜에 맞추어', 'in accordance with'), g('を皮切りに', '〜을 시작으로', 'starting with')], explanation: t('보고를 하는 방문과 시작품 전달을 함께 한다는 격식적 표현입니다.', '報告の訪問と試作品の持参を兼ねる格式的な表現です。', 'Katagata formally combines the visit for reporting with delivering the prototype.') },
  { sentence: '災害時＿＿＿、安全確認の手順を省略してはならない。', answer: g('といえども', '〜이라고 해도', 'even in'), distractors: [g('を皮切りに', '〜을 시작으로', 'starting with'), g('をよそに', '〜을 개의치 않고', 'regardless of'), g('にひきかえ', '〜와는 반대로', 'in contrast to')], explanation: t('재해 상황이라고 해도 안전 확인은 생략할 수 없다는 양보를 나타내므로 「といえども」를 씁니다.', '災害時であっても安全確認は省略できないという譲歩を表すので「といえども」を使います。', 'To iedomo concedes that even a disaster does not permit skipping the safety check.') },
  { sentence: '新しい単語を覚えた＿＿＿忘れるので、例文と一緒に復習している。', answer: g('そばから', '〜하자마자', 'as soon as'), distractors: [g('上から', '위에서부터', 'from above'), g('かたがた', '〜를 겸하여', 'while also'), g('てからでないと', '〜한 후가 아니면', 'not until after')], explanation: t('외운 직후 반복적으로 잊어버리는 상황을 나타냅니다.', '覚えた直後に何度も忘れてしまう状況を表します。', 'Soba kara describes the frustrating repetition of forgetting immediately after learning.') },
  { sentence: '彼は、今にも泣き出さ＿＿＿表情で、結果を見つめていた。', answer: g('んばかりの', '〜할 듯한', 'as if about to'), distractors: [g('ながらの', '〜하면서의', 'while'), g('たきりの', '〜한 채의', 'remaining after'), g('にすぎない', '〜에 불과한', 'nothing more than')], explanation: t('실제로 울지는 않았지만 울 직전처럼 보이는 표정을 나타냅니다.', '実際には泣いていないが、今にも泣きそうな様子を表します。', 'N bakari no describes an appearance as if the action were about to happen.') },
] as const;

export const N2_KANJI_SPECS: readonly KanjiSpec[] = [
  { word: '維持', reading: 'いじ', meaning: t('유지', '保ち続けること', 'maintenance'), distractors: ['いし', 'いち', 'いせい'] },
  { word: '輸送', reading: 'ゆそう', meaning: t('수송', '物を運ぶこと', 'transportation'), distractors: ['ゆしょう', 'ゆぞう', 'ゆそ'] },
  { word: '改善', reading: 'かいぜん', meaning: t('개선', 'より良くすること', 'improvement'), distractors: ['かいせん', 'かいせい', 'かいぜい'] },
  { word: '承認', reading: 'しょうにん', meaning: t('승인', '正式に認めること', 'approval'), distractors: ['しょうじん', 'しょうねん', 'しょにん'] },
  { word: '混雑', reading: 'こんざつ', meaning: t('혼잡', '人や物がこみ合うこと', 'congestion'), distractors: ['こんさつ', 'こうざつ', 'こんぞつ'] },
  { word: '講義', reading: 'こうぎ', meaning: t('강의', '学問を説明する授業', 'lecture'), distractors: ['こうぎょ', 'こうし', 'こうげ'] },
  { word: '貯金', reading: 'ちょきん', meaning: t('저금', '金銭をためること', 'savings'), distractors: ['ちょうきん', 'ちょがね', 'たくきん'] },
  { word: '豊富', reading: 'ほうふ', meaning: t('풍부', '十分に多いこと', 'abundance'), distractors: ['ほうぶ', 'とみふ', 'ほうほ'] },
  { word: '規模', reading: 'きぼ', meaning: t('규모', '大きさや範囲', 'scale'), distractors: ['きも', 'ぎぼ', 'きぼう'] },
  { word: '傾向', reading: 'けいこう', meaning: t('경향', '一定の方向に傾くこと', 'tendency'), distractors: ['けいごう', 'けいきょう', 'けんこう'] },
  { word: '採用', reading: 'さいよう', meaning: t('채용', '人や方法を選ぶこと', 'adoption or hiring'), distractors: ['さいゆう', 'さいよ', 'さとう'] },
  { word: '資源', reading: 'しげん', meaning: t('자원', '利用できる物資', 'resources'), distractors: ['じげん', 'しけん', 'しげ'] },
  { word: '確率', reading: 'かくりつ', meaning: t('확률', '起こりやすさの割合', 'probability'), distractors: ['かくそつ', 'かくれつ', 'かくりち'] },
  { word: '責任', reading: 'せきにん', meaning: t('책임', '引き受けるべき務め', 'responsibility'), distractors: ['せっにん', 'せきじん', 'せきねん'] },
  { word: '防災', reading: 'ぼうさい', meaning: t('방재', '災害を防ぐこと', 'disaster prevention'), distractors: ['ほうさい', 'ぼうざい', 'ぼうせい'] },
] as const;

export const N1_KANJI_SPECS: readonly KanjiSpec[] = [
  { word: '遂行', reading: 'すいこう', meaning: t('수행', '任務をやり遂げること', 'execution'), distractors: ['ずいこう', 'すいぎょう', 'すいごう'] },
  { word: '懸念', reading: 'けねん', meaning: t('우려', '気にかかって心配すること', 'concern'), distractors: ['けんねん', 'けんじょう', 'かけねん'] },
  { word: '脆弱', reading: 'ぜいじゃく', meaning: t('취약', '弱くてもろいこと', 'vulnerability'), distractors: ['せいじゃく', 'ぜいしゃく', 'きじゃく'] },
  { word: '促進', reading: 'そくしん', meaning: t('촉진', '進みを早めること', 'promotion'), distractors: ['そっしん', 'そくじん', 'そうしん'] },
  { word: '把握', reading: 'はあく', meaning: t('파악', '正確につかむこと', 'grasp'), distractors: ['ばあく', 'はあぐ', 'はくあく'] },
  { word: '概略', reading: 'がいりゃく', meaning: t('개략', 'おおよその内容', 'outline'), distractors: ['がいれき', 'がいらく', 'かいりゃく'] },
  { word: '顧慮', reading: 'こりょ', meaning: t('고려', '周囲の事情を考えること', 'consideration'), distractors: ['こりょう', 'かりょ', 'こうりょ'] },
  { word: '踏襲', reading: 'とうしゅう', meaning: t('답습', '従来の方式を受け継ぐこと', 'following precedent'), distractors: ['とうしゅ', 'とうじゅう', 'とっしゅう'] },
  { word: '顕在', reading: 'けんざい', meaning: t('겉으로 분명히 드러나 있음', 'はっきり現れていること', 'being manifest'), distractors: ['けんさい', 'けんせい', 'あらざい'] },
  { word: '措置', reading: 'そち', meaning: t('조치', '必要な対応を取ること', 'measure'), distractors: ['そっち', 'さくち', 'そし'] },
  { word: '妥当', reading: 'だとう', meaning: t('타당', '適切で無理がないこと', 'validity'), distractors: ['たとう', 'だっとう', 'だどう'] },
  { word: '繁栄', reading: 'はんえい', meaning: t('번영', '豊かに発展すること', 'prosperity'), distractors: ['はんさい', 'ばんえい', 'はんえ'] },
  { word: '賠償', reading: 'ばいしょう', meaning: t('배상', '損害を金品で償うこと', 'compensation'), distractors: ['ばいしゅう', 'ばいじょう', 'ばいそう'] },
  { word: '逸脱', reading: 'いつだつ', meaning: t('일탈', '基準から外れること', 'deviation'), distractors: ['いっだつ', 'いつだち', 'えつだつ'] },
  { word: '閑散', reading: 'かんさん', meaning: t('한산', '人が少なく静かな様子', 'desertedness'), distractors: ['かんざん', 'かんさい', 'ひまさん'] },
] as const;

const N2_LISTENING_AUTHORED_SPECS: readonly ListeningSpec[] = [
  { audioScriptJa: '会議室が二時まで使えないそうです。準備に三十分必要なので、開始は三時に変更しましょう。', question: t('회의는 몇 시에 시작합니까?', '会議は何時に始まりますか。', 'What time will the meeting begin?'), answer: t('오후 3시', '午後三時', '3 p.m.'), distractors: [t('오후 2시', '午後二時', '2 p.m.'), t('오후 2시 30분', '午後二時半', '2:30 p.m.'), t('오후 3시 30분', '午後三時半', '3:30 p.m.')], explanation: t('회의실 사용과 준비 시간 때문에 시작을 3시로 바꾸었습니다.', '会議室の利用と準備時間のため、開始は三時に変更されました。', 'The room schedule and setup time move the start to 3 p.m.') },
  { audioScriptJa: '報告書はほぼ完成していますが、先に部長に下書きを送ってください。意見を反映してから、金曜日に最終版を提出します。', question: t('먼저 해야 할 일은 무엇입니까?', 'まず何をしなければなりませんか。', 'What must be done first?'), answer: t('부장에게 초안을 보내다', '部長に下書きを送る', 'send the draft to the manager'), distractors: [t('최종본을 금요일 전에 제출하다', '最終版を金曜日より前に提出する', 'submit the final before Friday'), t('보고서를 처음부터 다시 쓰다', '報告書を最初から書き直す', 'rewrite the report from scratch'), t('금요일 회의를 예약하다', '金曜日の会議を予約する', 'book a Friday meeting')], explanation: t('최종본 전에 부장의 의견을 받아야 하므로 초안 전송이 먼저입니다.', '最終版の前に部長の意見を受けるため、下書きの送付が先です。', 'The draft must go to the manager before the feedback is incorporated.') },
  { audioScriptJa: '妹への誕生日プレゼントを探しています。香水は香りが苦手だそうで、アクセサリーも仕事では着けられません。毎日使える革の定期入れにします。', question: t('말하는 사람은 무엇을 삽니까?', '話している人は何を買いますか。', 'What will the speaker buy?'), answer: t('가죽 정기권 지갑', '革の定期入れ', 'a leather pass holder'), distractors: [t('향수', '香水', 'perfume'), t('액세서리', 'アクセサリー', 'jewelry'), t('업무용 가방', '仕事用のかばん', 'a work bag')], explanation: t('향수와 액세서리는 조건에 맞지 않아 매일 쓸 수 있는 정기권 지갑을 골랐습니다.', '香水とアクセサリーは条件に合わず、毎日使える定期入れを選びました。', 'The speaker rejects perfume and jewelry and chooses the pass holder.') },
  { audioScriptJa: '快速電車は設備点検で運休しています。二番線の普通電車で南駅まで行き、そこから市役所行きのバスに乗り換えてください。', question: t('여행자는 어떻게 이동해야 합니까?', '利用者はどのように移動しますか。', 'How should the traveler proceed?'), answer: t('일반 전철 후 버스로 갈아타다', '普通電車の後にバスへ乗り換える', 'take a local train, then transfer to a bus'), distractors: [t('쾌속 전철만 타다', '快速電車だけに乗る', 'take only the rapid train'), t('버스를 타고 북역에서 전철로 갈아타다', 'バスで北駅へ行き電車に乗る', 'take a bus to North Station, then a train'), t('남역까지 걸어가다', '南駅まで歩く', 'walk to South Station')], explanation: t('쾌속은 운행하지 않으므로 일반 전철로 남역까지 간 후 버스로 갈아탑니다.', '快速は運休中なので、普通電車で南駅へ行きバスに乗り換えます。', 'Because the rapid service is suspended, the route is local train then bus.') },
  { audioScriptJa: '借りている本は今日が返却日ですが、図書館は休館日です。入口の返却ポストは使えるので、仕事の後にそこへ入れておきます。', question: t('책은 어떻게 반납합니까?', '本はどのように返しますか。', 'How will the book be returned?'), answer: t('입구의 반납함에 넣다', '入口の返却ポストに入れる', 'put it in the entrance return box'), distractors: [t('다음 영업일에 카운터에 반납하다', '次の開館日にカウンターで返す', 'return it at the counter next opening day'), t('직장에 두고 온다', '職場に置いてくる', 'leave it at work'), t('우편으로 보내다', '郵送で返す', 'mail it back')], explanation: t('휴관일이지만 입구의 반납함을 사용할 수 있습니다.', '休館日でも入口の返却ポストは利用できます。', 'The return box remains available even though the library is closed.') },
  { audioScriptJa: '歯医者の予約は木曜日でしたが、出張が入りました。翌週の月曜日は休診なので、火曜日の午前に変えてもらいました。', question: t('치과 예약은 언제입니까?', '歯医者の予約はいつですか。', 'When is the dental appointment?'), answer: t('다음 주 화요일 오전', '翌週の火曜日の午前', 'Tuesday morning next week'), distractors: [t('이번 주 목요일', '今週の木曜日', 'Thursday this week'), t('다음 주 월요일', '翌週の月曜日', 'Monday next week'), t('다음 주 화요일 오후', '翌週の火曜日の午後', 'Tuesday afternoon next week')], explanation: t('출장과 휴진일 때문에 다음 주 화요일 오전으로 변경했습니다.', '出張と休診日のため、翌週の火曜日の午前に変更しました。', 'The appointment is moved to Tuesday morning next week.') },
  { audioScriptJa: '今日は新人向けの資料を作る予定でしたが、午後の発表で使うグラフに間違いが見つかりました。まずグラフを修正し、その後で資料に取りかかります。', question: t('말하는 사람은 먼저 무엇을 합니까?', '話している人はまず何をしますか。', 'What will the speaker do first?'), answer: t('그래프를 수정하다', 'グラフを修正する', 'correct the graph'), distractors: [t('신입 자료를 만들다', '新人向けの資料を作る', 'prepare the new-hire materials'), t('발표를 취소하다', '発表を取り消す', 'cancel the presentation'), t('신입에게 그래프를 맡긴다', '新人にグラフを任せる', 'ask a new hire to fix the graph')], explanation: t('오후 발표에 필요한 그래프 수정이 긴급한 작업으로 우선됩니다.', '午後の発表に必要なグラフの修正が緊急なため、先に行います。', 'The graph is urgent for the afternoon presentation, so it comes first.') },
  { audioScriptJa: '週末のハイキングに誘われましたが、月曜日までに仕事の提案書を完成させなければなりません。土曜日は仕事をして、日曜日の昼食だけ参加します。', question: t('말하는 사람은 왜 하이킹에 참여하지 않습니까?', '話している人はなぜハイキングに参加しませんか。', 'Why will the speaker not join the hike?'), answer: t('제안서를 완성해야 해서', '提案書を完成させるため', 'to finish a proposal'), distractors: [t('등산화가 없어서', '登山靴がないため', 'because of missing hiking shoes'), t('월요일에 여행해야 해서', '月曜日に旅行するため', 'because of Monday travel'), t('일요일 점심 약속이 있어서', '日曜日の昼食の予定があるため', 'because of Sunday lunch')], explanation: t('월요일 마감인 제안서를 완성하기 위해 토요일에 일합니다.', '月曜日が締め切りの提案書を完成させるため、土曜日は仕事をします。', 'The Monday deadline requires working on the proposal on Saturday.') },
  { audioScriptJa: '来週の実習では野外で長時間調査します。ノートと筆記用具はこちらで用意しますが、雨でも行うので、各自レインコートを持ってきてください。', question: t('참가자가 각자 준비해야 하는 것은 무엇입니까?', '参加者が各自で準備する物は何ですか。', 'What must each participant bring?'), answer: t('비옷', 'レインコート', 'a raincoat'), distractors: [t('공책', 'ノート', 'a notebook'), t('필기구', '筆記用具', 'writing tools'), t('조사 용지', '調査用紙', 'survey sheets')], explanation: t('공책과 필기구는 주최 측이 준비하고, 참가자는 비옷을 가져와야 합니다.', 'ノートと筆記用具は主催者が用意し、参加者はレインコートを持参します。', 'The organizer supplies the stationery; participants bring raincoats.') },
  { audioScriptJa: '土曜日は午前に掃除をして、午後は美術館に行くつもりでした。でも、美術館のチケットが売り切れたので、近所の温水プールで泳ぐことにしました。', question: t('토요일 오후에 무엇을 합니까?', '土曜日の午後に何をしますか。', 'What will the speaker do Saturday afternoon?'), answer: t('수영하다', '温水プールで泳ぐ', 'go swimming'), distractors: [t('미술관에 가다', '美術館に行く', 'visit the museum'), t('청소하다', '掃除をする', 'clean the house'), t('표를 사러 가다', 'チケットを買いに行く', 'buy a ticket')], explanation: t('미술관 표가 매진되어 계획을 바꾸고 온수 풀에서 수영합니다.', '美術館のチケットが売り切れたため、予定を変えてプールで泳ぎます。', 'The sold-out museum tickets lead to the swimming plan.') },
  { audioScriptJa: 'お荷物は本日の午後二時から四時の間にお届けする予定でした。交通渋滞のため、到着は四時半ごろになる見込みです。', question: t('택배는 언제 도착할 예정입니까?', '荷物はいつ届く予定ですか。', 'When is the package now expected?'), answer: t('오후 4시 30분쯤', '午後四時半ごろ', 'around 4:30 p.m.'), distractors: [t('오후 2시', '午後二時', '2 p.m.'), t('오후 4시', '午後四時', '4 p.m.'), t('오후 5시 30분', '午後五時半', '5:30 p.m.')], explanation: t('교통 체증으로 예정 시간대보다 늦은 4시 30분쯤 도착합니다.', '交通渋滞により、予定時間帯より遅い四時半ごろの到着です。', 'Traffic delays the expected arrival until about 4:30 p.m.') },
  { audioScriptJa: '会話は得意ですが、漢字を読むのに時間がかかります。初級会話ではなく、漢字と読解を練習する中級クラスを選びます。', question: t('말하는 사람은 어떤 수업을 선택합니까?', '話している人はどの授業を選びますか。', 'Which class will the speaker choose?'), answer: t('중급 한자·독해반', '中級の漢字・読解クラス', 'intermediate kanji and reading'), distractors: [t('초급 회화반', '初級会話クラス', 'beginner conversation'), t('고급 발음반', '上級発音クラス', 'advanced pronunciation'), t('중급 작문반', '中級作文クラス', 'intermediate writing')], explanation: t('회화보다 한자와 독해가 취약하므로 중급 한자·독해반을 고릅니다.', '会話より漢字と読解が弱いため、中級の漢字・読解クラスを選びます。', 'The speaker targets the weaker kanji and reading skills.') },
  { audioScriptJa: '家の鍵が見つからなかったので、駅とコンビニに電話しました。その後、会社の警備員から、会議室の机の下にあったと連絡がありました。', question: t('열쇠는 어디에서 발견되었습니까?', '鍵はどこで見つかりましたか。', 'Where were the keys found?'), answer: t('회사 회의실의 책상 아래', '会社の会議室の机の下', 'under a meeting-room desk at work'), distractors: [t('역 분실물 창구', '駅の忘れ物窓口', 'the station lost-and-found'), t('편의점 카운터', 'コンビニのカウンター', 'the convenience-store counter'), t('집 현관', '家の玄関', 'the home entrance')], explanation: t('역과 편의점에 문의했지만 실제로는 회사 회의실에서 발견되었습니다.', '駅とコンビニに問い合わせましたが、実際には会社の会議室で見つかりました。', 'The station and store were contacted, but the keys were found at work.') },
  { audioScriptJa: '八人の打ち合わせなので、小会議室では狭すぎます。大会議室は午後から使用中ですから、午前十時から予約しましょう。', question: t('어떤 예약을 합니까?', 'どの予約をしますか。', 'Which reservation will be made?'), answer: t('오전 10시 대회의실', '午前十時の大会議室', 'the large room at 10 a.m.'), distractors: [t('오전 10시 소회의실', '午前十時の小会議室', 'the small room at 10 a.m.'), t('오후 1시 대회의실', '午後一時の大会議室', 'the large room at 1 p.m.'), t('오후 3시 소회의실', '午後三時の小会議室', 'the small room at 3 p.m.')], explanation: t('8명에게는 대회의실이 필요하고 오후에는 사용 중이므로 오전 10시로 예약합니다.', '八人には大会議室が必要で、午後は使用中なので午前十時に予約します。', 'Eight people need the large room, which is available at 10 a.m.') },
  { audioScriptJa: 'この店は駅から近いので便利ですが、希望する静かな席は予約できません。少し歩いても、個室を予約できる公園前の店にします。', question: t('어느 가게를 선택합니까?', 'どの店を選びますか。', 'Which restaurant will be chosen?'), answer: t('개인실을 예약할 수 있는 공원 앞 가게', '個室を予約できる公園前の店', 'the park-side restaurant with reservable private rooms'), distractors: [t('역에서 가깝지만 조용한 자리를 예약할 수 없는 가게', '駅に近いが静かな席を予約できない店', 'the nearby restaurant without quiet reservations'), t('공원 안의 야외 매점', '公園内の屋外店', 'the outdoor shop in the park'), t('역 뒤의 포장 전문점', '駅裏のテイクアウト専門店', 'the takeaway shop behind the station')], explanation: t('거리보다 조용한 개인실 예약을 우선하여 공원 앞 가게를 선택합니다.', '距離よりも静かな個室の予約を優先し、公園前の店を選びます。', 'A reservable quiet room is prioritized over proximity.') },
  { audioScriptJa: '明日の検定は午前九時からです。会場へは八時半までに入り、受付で参加証を受け取ってください。道具は会場にあるので持参不要です。', question: t('참가자는 오전 8시 30분까지 무엇을 해야 합니까?', '参加者は午前八時半までに何をしますか。', 'What must participants do by 8:30 a.m.?'), answer: t('회장에 입장하다', '会場に入る', 'enter the venue'), distractors: [t('검정을 시작하다', '検定を始める', 'start the test'), t('도구를 준비하다', '道具を準備する', 'prepare the tools'), t('참가증을 집에서 인쇄하다', '参加証を家で印刷する', 'print the pass at home')], explanation: t('검정은 9시에 시작하며, 8시 30분까지 회장에 들어가 접수해야 합니다.', '検定は九時開始で、八時半までに会場に入って受付をします。', 'The test begins at nine; entry and reception must happen by 8:30.') },
  { audioScriptJa: 'コピー機の紙がなくなりました。倉庫には予備がありません。隣の部署から一包み借りて今日の印刷を終え、新しい紙は明日注文します。', question: t('오늘 인쇄를 끝내기 위해 무엇을 합니까?', '今日の印刷を終えるために何をしますか。', 'How will today’s printing be completed?'), answer: t('옆 부서에서 용지를 빌린다', '隣の部署から紙を借りる', 'borrow paper from the next department'), distractors: [t('창고의 예비 용지를 쓴다', '倉庫の予備の紙を使う', 'use reserve paper'), t('오늘 새 용지를 주문한다', '今日、新しい紙を注文する', 'order new paper today'), t('인쇄을 내일로 미룬다', '印刷を明日に延ばす', 'postpone printing')], explanation: t('창고에 예비가 없어 옆 부서에서 한 묶음을 빌립니다.', '倉庫に予備がないため、隣の部署から一包み借ります。', 'With no reserve stock, one pack is borrowed from the neighboring department.') },
] as const;

export const N2_LISTENING_SPECS: readonly ListeningSpec[] = N2_LISTENING_AUTHORED_SPECS.slice(0, 15);

const N1_LISTENING_AUTHORED_SPECS: readonly ListeningSpec[] = [
  { audioScriptJa: '新規事業案は方向性には賛成です。ただし、初年度の負担が大きいので、対象地域を一つに絞った試行結果を見てから全国展開を判断しましょう。', question: t('새 사업에 대해 어떤 결정이 났습니까?', '新規事業についてどのように決まりましたか。', 'What was decided about the new business?'), answer: t('한 지역에서 시범 운영 후 전국 확대를 판단한다', '一地域で試行してから全国展開を判断する', 'run one regional pilot before deciding national expansion'), distractors: [t('즉시 전국에서 시작한다', 'すぐに全国展開する', 'launch nationwide immediately'), t('초년도 비용 때문에 사업을 취소한다', '初年度の費用のため事業を中止する', 'cancel because of first-year cost'), t('여러 지역에서 동시에 시범 운영한다', '複数地域で同時に試行する', 'pilot in several regions at once')], explanation: t('방향은 승인했지만 비용 위험을 줄이기 위해 한 지역에서 먼저 시범 운영합니다.', '方向性は承認した上で、費用リスクを抑えるため一地域で試行します。', 'The direction is approved, but cost risk leads to a single-region pilot.') },
  { audioScriptJa: '発表の論点は明確ですが、相関関係だけで因果関係まで結論しているように聞こえます。追加分析が間に合わないなら、結論の表現を限定的にすべきです。', question: t('발표자가 가장 우선해야 할 수정은 무엇입니까?', '発表者が最も優先すべき修正は何ですか。', 'What revision should the presenter prioritize?'), answer: t('인과 관계를 단정하지 않도록 결론을 제한해 표현한다', '因果関係を断定しない限定的な結論にする', 'limit the conclusion so it does not assert causation'), distractors: [t('논점을 더 많이 추가한다', '論点をさらに追加する', 'add more arguments'), t('상관관계 수치를 삭제한다', '相関係数を削除する', 'delete correlation figures'), t('추가 분석을 위해 발표를 취소한다', '追加分析のため発表を中止する', 'cancel the presentation')], explanation: t('추가 분석이 어렵다면 현재 증거가 보장하는 상관관계까지만 결론해야 합니다.', '追加分析が難しければ、現在の証拠が支える相関関係までに結論を限定します。', 'Without further analysis, the conclusion must stay within correlation.') },
  { audioScriptJa: '開発の遅れを取り戻すために検証工程を短縮する案も出ていますが、それでは公開後の障害リスクが高まります。機能を絞って、検証期間は確保しましょう。', question: t('팀은 일정 지연에 어떻게 대응합니까?', 'チームは遅れにどう対応しますか。', 'How will the team address the delay?'), answer: t('기능 범위를 줄이고 검증 기간은 유지한다', '機能を絞り検証期間は維持する', 'reduce scope while preserving validation time'), distractors: [t('검증 기간을 반으로 줄인다', '検証期間を半分にする', 'halve validation time'), t('모든 기능을 유지하고 공개를 미룬다', '全機能を保って公開を延期する', 'keep all features and delay release'), t('검증 없이 즉시 공개한다', '検証なしですぐ公開する', 'release without validation')], explanation: t('검증을 줄이지 않고 지연을 만회하기 위해 기능 범위만 줄입니다.', '検証期間を削らずに遅れを取り戻すため、機能範囲だけを絞ります。', 'Only scope is reduced to recover the delay without shortening validation.') },
  { audioScriptJa: '新しい制度は、支給対象を広げた一方で、所得に応じて支給額を調整する仕組みです。つまり、対象者が増えることと、全員の支給額が増えることは同じではありません。', question: t('새 제도에 대한 설명으로 맞는 것은 무엇입니까?', '新制度の説明として正しいものは何ですか。', 'Which statement correctly describes the new system?'), answer: t('대상자는 늘지만 지급액은 소득에 따라 다를 수 있다', '対象者は増えるが支給額は所得によって異なる', 'eligibility expands, but payments may differ by income'), distractors: [t('모든 대상자의 지급액이 동일하게 늘어난다', '全対象者の支給額が一律に増える', 'everyone receives the same increase'), t('고소득자만 새로 대상이 된다', '高所得者だけが新たな対象になる', 'only high earners become eligible'), t('대상자 수와 지급액이 모두 줄어든다', '対象者数と支給額の両方が減る', 'both eligibility and payments shrink')], explanation: t('제도는 범위를 넓히면서도 소득에 따라 개별 금액을 조정합니다.', '制度は対象を広げつつ、所得に応じて個別の支給額を調整します。', 'The system broadens eligibility while adjusting individual amounts by income.') },
  { audioScriptJa: 'お客様は返金よりも、業務を止めずに済むことを望んでいます。代替機を本日中に手配し、故障機はその際に回収して修理の見積もりを出しましょう。', question: t('고객 불만에 대한 첫 대응은 무엇입니까?', '顧客の苦情への最初の対応は何ですか。', 'What is the first response to the complaint?'), answer: t('오늘 대체 장비를 수배한다', '本日中に代替機を手配する', 'arrange a replacement today'), distractors: [t('즉시 전액 환불한다', 'すぐに全額返金する', 'issue an immediate full refund'), t('수리 견적을 먼저 보낸다', '修理見積もりを最初に送る', 'send the repair quote first'), t('고객에게 고장품을 배송하라고 한다', '顧客に故障機の発送を依頼する', 'ask the customer to ship the broken unit')], explanation: t('고객의 최우선 요구는 업무 중단 방지이므로 대체 장비를 먼저 보냅니다.', '顧客の最優先要求は業務停止の回避なので、代替機を先に手配します。', 'Continuity is the customer’s priority, so replacement comes first.') },
  { audioScriptJa: '価格面の差は小さいので、今回は納期の確実性を重視したいと思います。値引きを要求するより、遅延した場合の代替供給を契約に明記してもらいましょう。', question: t('협상에서 가장 중요한 조건은 무엇입니까?', '交渉で最も重視する条件は何ですか。', 'Which condition matters most in the negotiation?'), answer: t('납기 지연 시 대체 공급 보장', '納期遅延時の代替供給保証', 'guaranteed alternative supply if delivery is late'), distractors: [t('더 큰 가격 할인', 'さらなる価格値引き', 'a larger discount'), t('납품물의 포장 디자인', '納入品の包装デザイン', 'packaging design'), t('계약 기간 단축', '契約期間の短縮', 'a shorter contract term')], explanation: t('가격 차이가 작으므로 공급 중단을 막는 납기 보장을 우선합니다.', '価格差が小さいため、供給停止を防ぐ納期保証を優先します。', 'Delivery resilience is prioritized because price differences are small.') },
  { audioScriptJa: '現地調査は火曜日の午後です。月曜日までに質問項目を確定し、火曜日の午前に調査票を印刷します。回収データの整理は水曜日から始めます。', question: t('화요일 오전에 무엇을 합니까?', '火曜日の午前に何をしますか。', 'What happens Tuesday morning?'), answer: t('조사표를 인쇄한다', '調査票を印刷する', 'print the survey forms'), distractors: [t('질문 항목을 확정한다', '質問項目を確定する', 'finalize questions'), t('현지 조사를 시작한다', '現地調査を始める', 'begin fieldwork'), t('회수 데이터를 정리한다', '回収データを整理する', 'organize collected data')], explanation: t('질문은 월요일까지 확정하고 조사 직전인 화요일 오전에 인쇄합니다.', '質問は月曜日までに確定し、調査直前の火曜日午前に印刷します。', 'Questions are finalized Monday, and the forms are printed Tuesday morning.') },
  { audioScriptJa: '応募者の専門知識は十分です。ただ、今回の役割では異なる部門の意見を調整する必要があります。次の面接では、対立した意見をまとめた経験を具体的に確認しましょう。', question: t('다음 면접에서 중점적으로 확인할 내용은 무엇입니까?', '次の面接で重点的に確認することは何ですか。', 'What will the next interview focus on?'), answer: t('부서 간 갈등을 조정한 경험', '部門間の対立を調整した経験', 'experience resolving cross-department disagreement'), distractors: [t('전문 지식의 기초 수준', '専門知識の基礎水準', 'basic specialist knowledge'), t('현재 연봉에 대한 만족도', '現在の年収への満足度', 'satisfaction with current salary'), t('개인적인 작업 속도', '個人作業の速度', 'individual work speed')], explanation: t('전문성은 이미 충분하므로 역할에 필요한 조율 경험을 확인합니다.', '専門性はすでに十分なので、役割に必要な調整経験を確認します。', 'Technical knowledge is sufficient; coordination experience is the gap to test.') },
  { audioScriptJa: '予算を一割削減する必要があります。顧客サポートは契約更新率に直結するので維持し、利用率の低い外部セミナーと重複した調査委託を見直しましょう。', question: t('예산 삭감을 위해 무엇을 재검토합니까?', '予算削減のために何を見直しますか。', 'What will be reviewed for budget cuts?'), answer: t('이용률이 낮은 세미나와 중복 조사 위탁', '利用率の低いセミナーと重複した調査委託', 'low-use seminars and duplicate outsourced research'), distractors: [t('고객 지원 인력', '顧客サポート人員', 'customer support staffing'), t('계약 갱신 절차', '契約更新の手順', 'contract renewal procedures'), t('모든 외부 위탁을 일괄 취소', 'すべての外部委託の一律中止', 'all outsourcing indiscriminately')], explanation: t('갱신률에 직결된 지원은 보호하고, 효율이 낮거나 중복된 비용을 줄입니다.', '更新率に直結する支援は保護し、効率が低い、または重複した費用を削減します。', 'The plan protects retention-critical support and cuts low-value duplication.') },
  { audioScriptJa: '新しい手順では処理時間が平均で二割短くなりました。一方、誤りの件数は統計的に有意な変化がありません。現時点では、速度は改善したが正確性への影響は確認できないとまとめられます。', question: t('실험 결과에서 말할 수 있는 것은 무엇입니까?', '実験結果から言えることは何ですか。', 'What can be concluded from the experiment?'), answer: t('처리 속도는 개선됐지만 정확성 변화는 확인되지 않았다', '処理速度は改善したが正確性の変化は確認できなかった', 'speed improved, but no accuracy change was established'), distractors: [t('속도와 정확성이 모두 개선되었다', '速度と正確性の両方が改善した', 'both speed and accuracy improved'), t('속도가 빨라진 대신 오류가 늘었다', '速度が上がる代わりに誤りが増えた', 'errors increased as speed rose'), t('새 절차는 아무 효과가 없었다', '新手順には何の効果もなかった', 'the procedure had no effect')], explanation: t('속도는 유의하게 개선됐지만 오류 건수 변화는 통계적으로 확인되지 않았습니다.', '速度は有意に改善しましたが、誤り件数の変化は統計的に確認されませんでした。', 'Only the speed improvement is supported statistically.') },
  { audioScriptJa: '原稿の主張は興味深いのですが、冒頭で示した問いと最後の結論がずれています。事例を増やす前に、結論が最初の問いに答えるよう論旨を組み直してください。', question: t('편집자가 먼저 요구한 수정은 무엇입니까?', '編集者がまず求めた修正は何ですか。', 'What revision does the editor request first?'), answer: t('초반 질문과 결론이 일치하도록 논지를 재구성한다', '冒頭の問いと結論が対応するよう論旨を組み直す', 'restructure the argument so the conclusion answers the opening question'), distractors: [t('사례를 먼저 두 배로 늘린다', '事例をまず二倍に増やす', 'double the examples first'), t('흥미로운 주장을 삭제한다', '興味深い主張を削除する', 'delete the interesting claim'), t('결론을 없애고 질문만 남긴다', '結論を削除して問いだけ残す', 'remove the conclusion')], explanation: t('보완 사례보다 글의 핵심 질문과 결론의 논리적 연결을 먼저 고쳐야 합니다.', '追加事例より先に、文章の中心的な問いと結論の論理的接続を直す必要があります。', 'Logical alignment between the opening question and conclusion comes before more examples.') },
  { audioScriptJa: '契約書の表現だけでは、この場合に解約権が発生するかは断定できません。相手方に通知する前に、交渉記録と納品履歴を確認し、事実関係を整理してください。', question: t('상대방에게 알리기 전에 무엇을 해야 합니까?', '相手方に通知する前に何をすべきですか。', 'What should be done before notifying the other party?'), answer: t('협상 기록과 납품 이력을 확인해 사실 관계를 정리한다', '交渉記録と納品履歴を確認し事実関係を整理する', 'review records and establish the facts'), distractors: [t('해약권이 있다고 즉시 통지한다', '解約権があるとすぐに通知する', 'immediately assert termination rights'), t('계약서의 해당 조항을 삭제한다', '契約書の該当条項を削除する', 'delete the contract clause'), t('납품을 모두 반품한다', '納品をすべて返品する', 'return all deliveries')], explanation: t('계약 문구만으로 권리 발생을 확정할 수 없으므로 관련 사실을 먼저 확인합니다.', '契約文言だけで権利発生を断定できないため、関連事実を先に確認します。', 'The facts must be established before making a legal assertion.') },
  { audioScriptJa: '障害の原因は調査中ですが、影響範囲と復旧作業の進捗は確認できています。原因を推測で説明せず、現在確認済みの影響と次回更新時刻を先に公表しましょう。', question: t('첫 공지에 포함할 내용은 무엇입니까?', '最初の公表に含める内容は何ですか。', 'What should the first public update contain?'), answer: t('확인된 영향 범위와 다음 공지 시각', '確認済みの影響範囲と次回更新時刻', 'confirmed impact and the next update time'), distractors: [t('확인되지 않은 원인 추정', '未確認の原因推測', 'an unconfirmed cause'), t('복구 완료 시각의 확정적 약속', '復旧完了時刻の断定的な約束', 'a guaranteed recovery time'), t('장애의 책임자 이름', '障害の責任者名', 'the name of a person to blame')], explanation: t('추측은 배제하고 현재 확인된 영향과 다음 소통 시점을 먼저 공유합니다.', '推測は避け、現在確認できている影響と次の連絡時点を先に共有します。', 'The first update separates confirmed facts from speculation and sets the next update time.') },
  { audioScriptJa: '二社の提案は性能面で大きな差がありません。価格の安い会社Aは部品供給に三カ月かかり、会社Bは少し高いものの国内に交換部品を常備しています。停止時間の損失を考え、会社Bを選びます。', question: t('B사를 선택한 주요 이유는 무엇입니까?', '会社Bを選んだ主な理由は何ですか。', 'Why was Company B selected?'), answer: t('교체 부품을 국내에서 빠르게 조달할 수 있어서', '交換部品を国内で迅速に調達できるから', 'replacement parts are quickly available domestically'), distractors: [t('가격이 가장 저렴해서', '価格が最も安いから', 'it has the lowest price'), t('성능이 A사보다 크게 높아서', '性能が会社Aより大幅に高いから', 'performance is much higher'), t('부품 공급이 3개월 걸려서', '部品供給に三カ月かかるから', 'parts take three months')], explanation: t('성능은 비슷하므로 정지 시간을 줄일 수 있는 부품 조달성을 우선했습니다.', '性能は同程度なので、停止時間を短縮できる部品調達性を優先しました。', 'Similar performance makes fast parts availability the decisive factor.') },
  { audioScriptJa: '在宅勤務の試行では生産性に大きな変化はなく、通勤時間に関する満足度は上がりました。一方で新入社員の相談機会が減ったという課題があるため、週二日の在宅勤務を継続しつつ、新人向けの定例相談時間を設けます。', question: t('시범 운영 후 어떤 방침을 채택합니까?', '試行後、どのような方針を採用しますか。', 'What policy follows the pilot?'), answer: t('주 2일 재택근무를 유지하고 신입 정기 상담을 추가한다', '週二日の在宅勤務を続け、新人の定例相談を追加する', 'keep two remote days and add regular new-hire consultations'), distractors: [t('재택근무를 전면 폐지한다', '在宅勤務を全面廃止する', 'abolish remote work'), t('전 직원을 주 5일 재택으로 전환한다', '全社員を週五日在宅にする', 'move everyone to five remote days'), t('상담 기회 문제를 추가 조치 없이 두다', '相談機会の問題を対策なしで残す', 'leave the consultation issue unaddressed')], explanation: t('재택근무의 장점은 유지하고 신입 지원 부족을 별도 상담으로 보완합니다.', '在宅勤務の利点は保ち、新人支援の不足を定例相談で補います。', 'The policy preserves the benefit while directly addressing the support gap.') },
  { audioScriptJa: '新商品の発売日は変えません。ただし、広告表現の一部が消費者に誤解を与える可能性があるので、映像全体を作り直すのではなく、該当部分のナレーションと字幕を差し替えます。', question: t('광고에 대해 무엇을 변경합니까?', '広告の何を変更しますか。', 'What will be changed in the advertisement?'), answer: t('문제되는 부분의 나레이션과 자막', '該当部分のナレーションと字幕', 'the narration and captions in the problematic section'), distractors: [t('광고 영상 전체', '広告映像の全体', 'the entire video'), t('새 상품의 출시일', '新商品の発売日', 'the product launch date'), t('영상의 배경 음악만', '映像の背景音楽だけ', 'only the background music')], explanation: t('출시일은 유지하고 오해 가능성이 있는 표현만 교체합니다.', '発売日は維持し、誤解の可能性がある表現だけを差し替えます。', 'The launch remains fixed; only potentially misleading narration and captions change.') },
  { audioScriptJa: '取得候補のデータは全体の六割にすぎませんが、利用者属性は現行サービスと近い構成です。数量の不足だけで却下せず、欠損期間を別のデータで補えるかを先に検証しましょう。', question: t('데이터 취득 후보에 대해 먼저 무엇을 합니까?', 'データ取得候補についてまず何をしますか。', 'What is the first step for the data acquisition candidate?'), answer: t('결측 기간을 다른 데이터로 보완할 수 있는지 검증한다', '欠損期間を他データで補えるか検証する', 'test whether other data can fill the missing period'), distractors: [t('수량이 부족하므로 즉시 거절한다', '数量不足のため即座に却下する', 'reject immediately for low volume'), t('이용자 속성을 현재 서비스와 다르게 바꾼다', '利用者属性を現行サービスと異なるものに変える', 'change the user profile'), t('부족한 4할을 임의로 생성한다', '不足する四割を任意に作る', 'invent the missing forty percent')], explanation: t('대표성은 유사하므로 우선 결측 부분을 안전하게 보완할 수 있는지 검증합니다.', '代表性は近いため、まず欠損部分を安全に補完できるかを検証します。', 'Similar user composition justifies testing a safe way to fill the gap before rejection.') },
  { audioScriptJa: '住民説明会では、事業の利点だけを強調すると不信を招きかねません。騒音と交通量の試算値、そして基準を超えた場合の追加対策まで、最初から具体的に示しましょう。', question: t('주민 설명회에서 어떤 방식을 취합니까?', '住民説明会でどのように説明しますか。', 'How will the project be explained to residents?'), answer: t('장점과 함께 소음·교통 예측과 추가 대책을 구체적으로 공개한다', '利点とともに騒音・交通の予測と追加対策を具体的に示す', 'present benefits, impact estimates, and contingency measures'), distractors: [t('사업의 장점만 강조한다', '事業の利点だけを強調する', 'emphasize only benefits'), t('시산치는 공사 후에 공개한다', '試算値は工事後に公開する', 'disclose estimates after construction'), t('기준 초과 시의 대책은 결정하지 않는다', '基準超過時の対策は決めない', 'leave contingencies undecided')], explanation: t('장점만 말하면 불신을 키울 수 있으므로 영향과 조치를 처음부터 투명하게 제시합니다.', '利点だけでは不信を招くため、影響と対策も当初から透明に示します。', 'Trust requires disclosing projected impacts and responses alongside benefits.') },
] as const;

export const N1_LISTENING_SPECS: readonly ListeningSpec[] = N1_LISTENING_AUTHORED_SPECS.slice(0, 15);
