import { esc } from './utils.js';
import {
  type IndependentReviewLedger,
  type LocalizedText,
  type PendingReview,
  requireIndependentReview,
} from './jlpt-n3-practice-bank-v1.js';
import {
  NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE,
} from './next-content-expansion-source.js';

export const TOPIK_OWNER_BATCH_6_SOURCE_CODE = NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourceCode;
export const TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID = NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourceAssetId;

type Grade = 3 | 4 | 5 | 6;
type Section = 'vocab' | 'grammar' | 'reading' | 'listening' | 'writing';

export interface TopikOwnerBatch6Draft {
  id: string;
  grade: Grade;
  section: Section;
  sequence: 1 | 2;
  title: LocalizedText;
  prompt: LocalizedText;
  choices?: readonly LocalizedText[];
  answer_index?: number;
  rubric?: LocalizedText;
  explanation: LocalizedText;
  audio_text_ko: string | null;
  speech_provider: 'google-browser' | 'unavailable';
  authorship: 'self-authored';
  source_evidence_hash: string;
  reviews: readonly [PendingReview, PendingReview];
  release_state: 'draft';
  is_published: 0;
}

const t = (ko: string, ja: string, en: string): LocalizedText => ({ ko, ja, en });
const pendingReviews = (): readonly [PendingReview, PendingReview] => [
  { reviewer_slot: 'adversarial-1', status: 'pending' },
  { reviewer_slot: 'adversarial-2', status: 'pending' },
];

function choice(
  grade: Grade,
  section: Exclude<Section, 'writing'>,
  sequence: 1 | 2,
  title: LocalizedText,
  prompt: LocalizedText,
  correct: LocalizedText,
  distractors: readonly [LocalizedText, LocalizedText, LocalizedText],
  answerIndex: number,
  explanation: LocalizedText,
  audioTextKo?: string,
): TopikOwnerBatch6Draft {
  const choices = [...distractors];
  choices.splice(answerIndex, 0, correct);
  return {
    id: `topik-owner-batch6-grade${grade}-${section}-${sequence}`,
    grade,
    section,
    sequence,
    title,
    prompt,
    choices,
    answer_index: answerIndex,
    explanation,
    audio_text_ko: section === 'listening' ? audioTextKo ?? null : null,
    speech_provider: section === 'listening' ? 'google-browser' : 'unavailable',
    authorship: 'self-authored',
    source_evidence_hash: NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.intakeArtifactSha256,
    reviews: pendingReviews(),
    release_state: 'draft',
    is_published: 0,
  };
}

function writing(
  grade: Grade,
  sequence: 1 | 2,
  title: LocalizedText,
  prompt: LocalizedText,
  explanation: LocalizedText,
  rubric: LocalizedText,
): TopikOwnerBatch6Draft {
  return {
    id: `topik-owner-batch6-grade${grade}-writing-${sequence}`,
    grade,
    section: 'writing',
    sequence,
    title,
    prompt,
    explanation,
    rubric,
    audio_text_ko: null,
    speech_provider: 'unavailable',
    authorship: 'self-authored',
    source_evidence_hash: NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.intakeArtifactSha256,
    reviews: pendingReviews(),
    release_state: 'draft',
    is_published: 0,
  };
}

export const TOPIK_OWNER_BATCH_6: readonly TopikOwnerBatch6Draft[] = [
  choice(3, 'vocab', 1,
    t('교환과 환불', '交換と払い戻し', 'Exchange and refund'),
    t('산 물건에 문제가 있어 돈을 돌려받는 일을 무엇이라고 합니까?', '買った物に問題があり、お金を返してもらうことを何といいますか。', 'What do you call getting your money back because a purchased item has a problem?'),
    t('환불', '払い戻し', 'refund'),
    [t('할인', '割引', 'discount'), t('포장', '包装', 'wrapping'), t('배송', '配送', 'delivery')],
    0,
    t('환불은 구입한 물건의 대금을 다시 돌려받는 일입니다.', '「환불」は購入した品物の代金を返してもらうことです。', '환불 means receiving back the money paid for a purchase.'),
  ),
  choice(3, 'vocab', 2,
    t('공공시설', '公共施設', 'Public facility'),
    t('주민들이 운동이나 강좌에 이용하도록 지방자치단체가 운영하는 곳은 무엇입니까?', '住民が運動や講座に利用できるよう自治体が運営する場所は何ですか。', 'What is a place run by a local government for residents to use for exercise or classes?'),
    t('주민센터', '住民センター', 'community center'),
    [t('백화점', 'デパート', 'department store'), t('공장', '工場', 'factory'), t('창고', '倉庫', 'warehouse')],
    1,
    t('주민센터는 주민을 위한 행정 서비스와 생활 프로그램을 제공합니다.', '住民センターは住民向けの行政サービスや生活プログラムを提供します。', 'A community center provides local services and programs for residents.'),
  ),
  choice(3, 'grammar', 1,
    t('는 바람에', '〜したせいで', 'Because of an unexpected event'),
    t('예상하지 못한 일 때문에 생긴 결과가 되도록 빈칸을 고르세요. 버스가 늦게 오는 ___ 회의에 지각했습니다.', '予想外のことが原因となるよう空欄を選んでください。버스가 늦게 오는 ___ 회의에 지각했습니다.', 'Choose the expression showing an unexpected cause: 버스가 늦게 오는 ___ 회의에 지각했습니다.'),
    t('바람에', '予想外の原因で', 'because of an unexpected cause'),
    [t('대신에', '〜の代わりに', 'instead of'), t('만큼', '〜ほど・〜だけ', 'as much as'), t('중에도', '〜している最中にも', 'even while')],
    2,
    t('‘-는 바람에’는 예상하지 못한 원인 때문에 좋지 않은 결과가 생겼음을 나타냅니다.', '「-는 바람에」は予想外の原因で好ましくない結果が生じたことを表します。', '-는 바람에 indicates that an unexpected cause led to an undesirable result.'),
  ),
  choice(3, 'grammar', 2,
    t('더라도', '〜としても', 'Even if'),
    t('조건과 상관없이 계획을 유지한다는 뜻이 되도록 고르세요. 비가 오___ 행사는 예정대로 진행합니다.', '条件に関係なく予定を維持する意味になるよう選んでください。비가 오___ 행사는 예정대로 진행합니다.', 'Choose the ending meaning the plan will continue regardless of the condition: 비가 오___ 행사는 예정대로 진행합니다.'),
    t('더라도', '〜としても', 'even if'),
    [t('자마자', '〜するとすぐ', 'as soon as'), t('느라고', '〜するのに追われて', 'because one was occupied with'), t('도록', '〜するように', 'so that')],
    3,
    t('‘-더라도’는 앞의 조건이 생겨도 뒤의 결정이 달라지지 않음을 나타냅니다.', '「-더라도」は前の条件が生じても後ろの決定が変わらないことを表します。', '-더라도 means the following decision remains unchanged even if the condition occurs.'),
  ),
  choice(3, 'reading', 1,
    t('강좌 신청 안내', '講座申込案内', 'Class registration notice'),
    t('안내: 요리 강좌 신청은 수요일 오후 여섯 시에 마감됩니다. 신청자가 열 명보다 적으면 강좌가 취소되며, 취소 여부는 목요일 오전에 문자로 알려 드립니다. 신청자는 언제 취소 여부를 알 수 있습니까?', '案内：料理講座の申込は水曜日午後六時に締め切ります。申込者が十人未満の場合は講座を中止し、中止の有無は木曜日午前にメッセージでお知らせします。申込者はいつ中止の有無が分かりますか。', 'Notice: Registration closes Wednesday at 6 p.m. If fewer than ten people register, the class will be canceled, and a message will be sent Thursday morning. When will applicants learn whether it is canceled?'),
    t('목요일 오전', '木曜日の午前', 'Thursday morning'),
    [t('수요일 오전', '水曜日の午前', 'Wednesday morning'), t('수요일 오후 여섯 시', '水曜日午後六時', 'Wednesday at 6 p.m.'), t('금요일 오후', '金曜日の午後', 'Friday afternoon')],
    0,
    t('취소 여부는 신청 마감 다음 날인 목요일 오전에 문자로 안내됩니다.', '中止の有無は申込締切の翌日、木曜日の午前にメッセージで通知されます。', 'The cancellation decision is sent by message on Thursday morning.'),
  ),
  choice(3, 'reading', 2,
    t('자전거 보관소 공사', '駐輪場工事', 'Bicycle parking construction'),
    t('공지: 지하 자전거 보관소는 환기 시설 공사로 다음 주 월요일부터 금요일까지 이용할 수 없습니다. 공사 기간에는 건물 뒤편 임시 보관소를 이용해 주십시오. 이용자는 공사 기간에 자전거를 어디에 두어야 합니까?', 'お知らせ：地下駐輪場は換気設備工事のため、来週月曜日から金曜日まで利用できません。工事期間中は建物裏の臨時駐輪場をご利用ください。利用者は工事期間中、自転車をどこに置きますか。', 'Notice: The underground bicycle parking area will be closed Monday through Friday next week for ventilation work. During construction, where should users leave bicycles?'),
    t('건물 뒤편 임시 보관소', '建物裏の臨時駐輪場', 'the temporary area behind the building'),
    [t('지하 보관소', '地下駐輪場', 'the underground parking area'), t('건물 정문', '建物の正面入口', 'the building entrance'), t('도로 옆', '道路脇', 'beside the road')],
    1,
    t('공지에서 공사 기간에는 건물 뒤편의 임시 보관소를 이용하라고 했습니다.', 'お知らせでは工事期間中、建物裏の臨時駐輪場を利用するよう案内しています。', 'The notice directs users to the temporary parking area behind the building.'),
  ),
  choice(3, 'listening', 1,
    t('설명회 장소 변경', '説明会会場の変更', 'Orientation venue change'),
    t('설명회는 어디에서 열립니까?', '説明会はどこで開かれますか。', 'Where will the orientation be held?'),
    t('별관 2층 회의실', '別館二階の会議室', 'the second-floor meeting room in the annex'),
    [t('본관 강당', '本館講堂', 'the main auditorium'), t('도서관 세미나실', '図書館セミナー室', 'the library seminar room'), t('운동장', '運動場', 'the athletic field')],
    2,
    t('본관 강당의 냉방 문제 때문에 설명회 장소가 별관 2층 회의실로 바뀌었습니다.', '本館講堂の冷房問題により、説明会会場は別館二階の会議室に変更されました。', 'The orientation moved to the annex meeting room because the main auditorium has an air-conditioning problem.'),
    '오늘 설명회 장소가 바뀌었습니다. 본관 강당의 냉방 시설을 사용할 수 없어서 별관 이층 회의실에서 진행합니다.',
  ),
  choice(3, 'listening', 2,
    t('업무 순서 확인', '作業手順の確認', 'Confirming task order'),
    t('직원은 보고서를 보내기 전에 무엇을 해야 합니까?', '職員は報告書を送る前に何をしなければなりませんか。', 'What must the employee do before sending the report?'),
    t('수정된 수치를 다시 확인한다', '修正した数値を再確認する', 'check the revised figures again'),
    [t('보고서를 바로 인쇄한다', '報告書をすぐ印刷する', 'print the report immediately'), t('고객에게 먼저 전화한다', '先に顧客へ電話する', 'call the customer first'), t('회의 일정을 취소한다', '会議日程を取り消す', 'cancel the meeting')],
    3,
    t('팀장은 수정된 수치를 한 번 더 확인한 뒤 보고서를 보내라고 했습니다.', 'チーム長は修正した数値をもう一度確認してから報告書を送るよう指示しました。', 'The team leader instructed the employee to check the revised figures once more before sending the report.'),
    '보고서의 표를 수정했군요. 보내기 전에 바뀐 수치가 맞는지 한 번 더 확인해 주세요. 확인이 끝나면 거래처에 이메일로 보내면 됩니다.',
  ),
  writing(3, 1,
    t('시설 이용 문의', '施設利用の問い合わせ', 'Facility inquiry'),
    t('체육관 담당자에게 이용 가능 시간과 준비물을 묻는 이메일을 세 문장으로 쓰세요.', '体育館担当者に利用可能な時間と持ち物を尋ねるメールを三文で書いてください。', 'Write a three-sentence email asking a gym coordinator about available hours and what to bring.'),
    t('예: 안녕하세요. 토요일에 체육관을 이용할 수 있는 시간이 궁금합니다. 실내화 외에 준비해야 할 물건도 알려 주시면 감사하겠습니다.', '例：こんにちは。土曜日に体育館を利用できる時間を知りたいです。室内履き以外に必要な持ち物も教えていただけると幸いです。', 'Example: Hello. I would like to know when the gym is available on Saturday. I would also appreciate information about anything required besides indoor shoes.'),
    t('인사, 이용 가능 시간에 대한 질문, 준비물에 대한 질문을 각각 포함하고 정중한 높임말을 사용합니다.', '挨拶、利用可能時間への質問、持ち物への質問をそれぞれ含め、丁寧な敬語を使います。', 'Include a greeting, a question about available hours, and a question about required items, using polite language.'),
  ),
  writing(3, 2,
    t('습관 개선 제안', '習慣改善の提案', 'Suggesting a better habit'),
    t('늦게 자는 친구에게 생활 습관을 바꾸는 방법과 그 이유를 세 문장으로 조언하세요.', '夜更かしする友達に、生活習慣を変える方法とその理由を三文で助言してください。', 'Give a friend who stays up late three sentences of advice, including a method and its reason.'),
    t('예: 잠들기 한 시간 전에는 휴대 전화를 보지 않는 것이 좋아요. 대신 조용한 음악을 듣거나 책을 읽어 보세요. 그러면 긴장이 풀려서 조금 더 일찍 잠들 수 있어요.', '例：寝る一時間前には携帯電話を見ないほうがいいです。代わりに静かな音楽を聴いたり本を読んだりしてみてください。そうすれば緊張がほぐれ、少し早く眠れます。', 'Example: Avoid your phone for an hour before bed. Try quiet music or reading instead. This can help you relax and fall asleep earlier.'),
    t('세 문장으로 문제 행동, 구체적인 대안, 기대되는 효과를 논리적으로 연결하고 친구에게 알맞은 말투를 사용합니다.', '三文で問題行動、具体的な代案、期待される効果を論理的につなぎ、友達に合う話し方を使います。', 'Use three sentences to connect the problematic habit, a specific alternative, and its expected benefit in an appropriate friendly tone.'),
  ),

  choice(4, 'vocab', 1,
    t('계획의 보완', '計画の補完', 'Improving a plan'),
    t('부족한 부분을 더하여 계획을 완전하게 만드는 것을 무엇이라고 합니까?', '不足している部分を加えて計画をより完全にすることを何といいますか。', 'What do you call adding what is missing to make a plan more complete?'),
    t('보완', '補完', 'supplementation'),
    [t('축소', '縮小', 'reduction'), t('연기', '延期', 'postponement'), t('분리', '分離', 'separation')],
    0,
    t('보완은 부족하거나 불충분한 부분을 채워 더 나아지게 하는 일입니다.', '「보완」は不足または不十分な部分を補って改善することです。', '보완 means filling a missing or insufficient part to improve something.'),
  ),
  choice(4, 'vocab', 2,
    t('식품 정보', '食品情報', 'Food information'),
    t('식품을 안전하게 먹을 수 있다고 정해 놓은 기한은 무엇입니까?', '食品を安全に食べられると定められた期限は何ですか。', 'What is the stated period during which food can be safely consumed?'),
    t('소비기한', '消費期限', 'use-by date'),
    [t('생산량', '生産量', 'production volume'), t('판매가', '販売価格', 'sale price'), t('배송비', '配送料', 'delivery charge')],
    1,
    t('소비기한은 정해진 보관 방법을 지켰을 때 식품을 안전하게 먹을 수 있는 기한입니다.', '消費期限は定められた保存方法を守った場合に食品を安全に食べられる期限です。', 'A use-by date is the period during which food can be safely consumed when stored as directed.'),
  ),
  choice(4, 'grammar', 1,
    t('을 뿐만 아니라', '〜だけでなく', 'Not only but also'),
    t('두 장점을 함께 강조하도록 빈칸을 고르세요. 이 도서관은 자료가 다양할 ___ 이용 시간도 깁니다.', '二つの長所を強調するよう空欄を選んでください。이 도서관은 자료가 다양할 ___ 이용 시간도 깁니다.', 'Choose the expression emphasizing two advantages: 이 도서관은 자료가 다양할 ___ 이용 시간도 깁니다.'),
    t('뿐만 아니라', '〜だけでなく', 'not only ... but also'),
    [t('수밖에 없고', '〜するしかなくて', 'having no choice but to'), t('뻔하다가', '〜しかけて', 'nearly, then'), t('지도 모르고', '〜かもしれず', 'perhaps, and')],
    2,
    t('‘-을 뿐만 아니라’는 앞의 사실에 뒤의 사실을 더해 강조할 때 씁니다.', '「-을 뿐만 아니라」は前の事実に後ろの事実を加えて強調するときに使います。', '-을 뿐만 아니라 adds and emphasizes a second fact in addition to the first.'),
  ),
  choice(4, 'grammar', 2,
    t('는 반면에', '〜一方で', 'Whereas'),
    t('두 방식의 차이를 대조하도록 고르세요. 온라인 회의는 이동 시간이 줄어드는 ___ 집중하기 어렵다는 의견도 있습니다.', '二つの方式の違いを対照するよう選んでください。온라인 회의는 이동 시간이 줄어드는 ___ 집중하기 어렵다는 의견도 있습니다.', 'Choose the expression contrasting two aspects: 온라인 회의는 이동 시간이 줄어드는 ___ 집중하기 어렵다는 의견도 있습니다.'),
    t('반면에', '〜一方で', 'whereas'),
    [t('덕분에', '〜のおかげで', 'thanks to'), t('바에야', '〜するくらいなら', 'rather than'), t('셈치고', '〜したことにして', 'assuming it as')],
    3,
    t('‘-는 반면에’는 서로 다른 두 특징이나 상황을 대조할 때 사용합니다.', '「-는 반면에」は異なる二つの特徴や状況を対照するときに使います。', '-는 반면에 is used to contrast two different characteristics or situations.'),
  ),
  choice(4, 'reading', 1,
    t('공유 자전거 운영', 'シェアサイクル運営', 'Bike-share operation'),
    t('시에서는 출근 시간에 공유 자전거가 부족하다는 민원이 늘자 지하철역 주변의 자전거 수를 늘렸다. 그러나 퇴근 뒤 특정 지역에 자전거가 몰리는 문제가 생겨, 이용 기록을 바탕으로 밤마다 자전거를 다시 배치하기로 했다. 시에서 새로 하기로 한 일은 무엇입니까?', '市は通勤時間帯にシェアサイクルが不足するという苦情が増えたため、地下鉄駅周辺の台数を増やしました。しかし退勤後に特定地域へ自転車が集中する問題が生じ、利用記録をもとに毎晩自転車を再配置することにしました。市が新たに行うことは何ですか。', 'The city increased shared bicycles near subway stations, but bicycles then accumulated in certain areas after work. What will the city newly do?'),
    t('이용 기록에 따라 밤마다 자전거를 재배치한다', '利用記録に基づき毎晩自転車を再配置する', 'redistribute bicycles nightly using usage records'),
    [t('출근 시간마다 지하철역 주변 자전거만 늘린다', '通勤時間ごとに地下鉄駅周辺の自転車だけを増やす', 'add bicycles only near subway stations each morning'), t('퇴근 뒤에는 특정 지역의 반납을 제한한다', '退勤後は特定地域での返却を制限する', 'restrict returns in selected areas after work'), t('지역별 고정 수량에 따라 한 달에 한 번 재배치한다', '地域別の固定台数に基づき月一回再配置する', 'redistribute monthly according to fixed area quotas')],
    0,
    t('자전거 쏠림을 줄이기 위해 이용 기록을 보고 밤마다 위치를 조정하기로 했습니다.', '自転車の偏りを減らすため、利用記録を見て毎晩位置を調整することにしました。', 'The city will use usage records to redistribute bicycles each night and reduce imbalance.'),
  ),
  choice(4, 'reading', 2,
    t('재택근무 지침', '在宅勤務指針', 'Remote-work guideline'),
    t('회사에서는 재택근무 중 집중 시간이 자주 끊긴다는 의견을 반영해 오전 열 시부터 열두 시까지 회의를 잡지 않기로 했다. 긴급한 업무는 공동 채널에 남기되, 즉시 답해야 하는 경우에만 전화하도록 했다. 긴급한 업무가 생겼을 때 우선 해야 할 일은 무엇입니까?', '会社は在宅勤務中に集中時間が頻繁に途切れるという意見を受け、午前十時から正午まで会議を入れないことにしました。緊急業務は共有チャンネルに残し、即答が必要な場合だけ電話することにしました。緊急業務が生じたとき最初に何をしますか。', 'The company protects a meeting-free focus period. Urgent work should be posted in a shared channel, with calls only when an immediate answer is necessary. What should happen first?'),
    t('공동 채널에 내용을 남긴다', '共有チャンネルに内容を残す', 'post the details in the shared channel'),
    [t('모든 직원에게 전화한다', '全社員に電話する', 'call every employee'), t('집중 시간을 없앤다', '集中時間をなくす', 'eliminate the focus period'), t('다음 주까지 기다린다', '来週まで待つ', 'wait until next week')],
    1,
    t('지침은 긴급 업무를 먼저 공동 채널에 남기고 즉시 답이 필요할 때만 전화하도록 합니다.', '指針では緊急業務をまず共有チャンネルに残し、即答が必要な場合だけ電話するよう求めています。', 'The guideline says to post urgent work in the shared channel first and call only when an immediate answer is needed.'),
  ),
  choice(4, 'listening', 1,
    t('워크숍 준비 변경', 'ワークショップ準備の変更', 'Workshop preparation change'),
    t('참가자 수가 늘어서 준비팀이 추가로 해야 할 일은 무엇입니까?', '参加者が増えたため、準備チームが追加で行うことは何ですか。', 'What additional task must the team do because attendance increased?'),
    t('실습 재료를 열 세트 더 준비한다', '実習材料を十セット追加で用意する', 'prepare ten more sets of materials'),
    [t('행사를 한 시간 늦춘다', '行事を一時間遅らせる', 'delay the event by one hour'), t('강사를 바꾼다', '講師を変更する', 'change the instructor'), t('참가 신청을 모두 취소한다', '参加申込をすべて取り消す', 'cancel all registrations')],
    2,
    t('참가자가 서른 명에서 마흔 명으로 늘어 실습 재료 열 세트를 추가해야 합니다.', '参加者が三十人から四十人に増えたため、実習材料を十セット追加する必要があります。', 'Attendance increased from thirty to forty, so ten additional material sets are needed.'),
    '워크숍 참가자가 서른 명에서 마흔 명으로 늘었습니다. 의자는 충분하지만 실습 재료가 부족하니 열 세트를 더 준비해 주세요.',
  ),
  choice(4, 'listening', 2,
    t('도서 대출 연장', '図書貸出の延長', 'Extending a book loan'),
    t('이용자가 대출 기간을 연장할 수 없는 이유는 무엇입니까?', '利用者が貸出期間を延長できない理由は何ですか。', 'Why can the user not extend the loan?'),
    t('다른 이용자가 그 책을 예약했기 때문에', '別の利用者がその本を予約しているため', 'because another user reserved the book'),
    [t('회원 카드가 만료되어서', '会員カードの期限が切れたため', 'because the membership card expired'), t('도서관이 공사 중이어서', '図書館が工事中のため', 'because the library is under construction'), t('책을 이미 잃어버려서', '本をすでになくしたため', 'because the book was already lost')],
    3,
    t('예약자가 있는 책은 대출 기간을 연장할 수 없다고 안내했습니다.', '予約者がいる本は貸出期間を延長できないと案内しています。', 'The library explains that a reserved book cannot be renewed.'),
    '반납일이 내일까지인데 일주일 더 빌릴 수 있을까요? 죄송하지만 다른 이용자가 이 책을 예약해서 연장은 어렵습니다. 내일까지 반납해 주세요.',
  ),
  writing(4, 1,
    t('서비스 개선 제안', 'サービス改善提案', 'Service improvement proposal'),
    t('공공 앱의 불편한 점 하나와 구체적인 개선 방법 두 가지를 네 문장으로 제안하세요.', '公共アプリの不便な点一つと具体的な改善方法二つを四文で提案してください。', 'In four sentences, describe one inconvenience in a public app and propose two specific improvements.'),
    t('예: 버스 앱의 정류장 검색 결과가 너무 많아 원하는 곳을 찾기 어렵습니다. 현재 위치와 가까운 정류장을 먼저 보여 주면 좋겠습니다. 자주 이용하는 정류장을 저장하는 기능도 필요합니다. 이렇게 바꾸면 이용자가 정보를 더 빨리 찾을 수 있습니다.', '例：バスアプリの停留所検索結果が多すぎて目的地を探しにくいです。現在地に近い停留所を先に表示するとよいです。よく使う停留所を保存する機能も必要です。このように変えれば利用者がより早く情報を見つけられます。', 'Example: The bus app shows too many search results. Nearby stops should appear first. Users should also be able to save frequent stops. These changes would help people find information faster.'),
    t('네 문장 안에 현재 문제, 구체적인 개선책 두 가지, 예상 효과를 포함하고 제안의 근거가 드러나야 합니다.', '四文の中に現状の問題、具体的な改善策二つ、予想される効果を含め、提案の根拠を示します。', 'Within four sentences, include the current problem, two specific improvements, the expected effect, and a clear rationale.'),
  ),
  writing(4, 2,
    t('두 방식 비교', '二つの方式の比較', 'Comparing two methods'),
    t('온라인 수업과 교실 수업의 장점과 단점을 비교하고 자신이 선호하는 방식을 네 문장으로 쓰세요.', 'オンライン授業と教室授業の長所と短所を比較し、自分が好む方式を四文で書いてください。', 'In four sentences, compare online and classroom learning and state which you prefer.'),
    t('예: 온라인 수업은 이동하지 않아도 되어 편리하지만 집중력이 떨어질 수 있습니다. 교실 수업은 바로 질문할 수 있는 반면 통학 시간이 필요합니다. 저는 대화를 통해 배우는 편이라 교실 수업을 선호합니다. 다만 복습 자료는 온라인으로 제공되면 좋겠습니다.', '例：オンライン授業は移動せず便利ですが、集中力が落ちることがあります。教室授業はすぐ質問できる一方、通学時間が必要です。私は対話で学ぶほうなので教室授業を好みます。ただし復習資料はオンラインで提供されるとよいです。', 'Example: Online classes save travel but can reduce concentration. Classroom lessons allow immediate questions but require commuting. I prefer classroom learning because I learn through interaction. Online review materials would still be helpful.'),
    t('두 방식의 장점과 단점을 각각 언급하고, 선호하는 방식과 그 이유를 일관된 관점으로 제시합니다.', '二つの方式の長所と短所をそれぞれ述べ、好む方式と理由を一貫した観点で示します。', 'Mention an advantage and disadvantage of each method, then state a preference and support it with a consistent reason.'),
  ),

  choice(5, 'vocab', 1,
    t('목표의 충돌', '目標の衝突', 'Conflicting goals'),
    t('두 목표나 가치가 서로 맞지 않아 동시에 이루기 어려운 상태를 나타내는 말은 무엇입니까?', '二つの目標や価値が合わず、同時に実現しにくい状態を表す言葉は何ですか。', 'Which word describes two goals or values that conflict and are difficult to achieve together?'),
    t('상충하다', '相反する', 'conflict'),
    [t('수렴하다', '収束する', 'converge'), t('보존하다', '保存する', 'preserve'), t('확산하다', '拡散する', 'spread')],
    0,
    t('상충하다는 둘 이상의 목표나 이해관계가 서로 맞지 않는다는 뜻입니다.', '「상충하다」は二つ以上の目標や利害が互いに合わないという意味です。', '상충하다 means that two or more goals or interests are incompatible.'),
  ),
  choice(5, 'vocab', 2,
    t('정책의 효과', '政策の効果', 'Policy effectiveness'),
    t('정책이나 제도가 실제 상황에서 목적한 효과를 내는 정도를 무엇이라고 합니까?', '政策や制度が実際の状況で意図した効果を生む程度を何といいますか。', 'What do you call the degree to which a policy produces its intended effect in practice?'),
    t('실효성', '実効性', 'practical effectiveness'),
    [t('우연성', '偶然性', 'randomness'), t('상징성', '象徴性', 'symbolism'), t('일시성', '一時性', 'temporariness')],
    1,
    t('실효성은 계획이나 제도가 현실에서 실제로 효과를 거두는 성질입니다.', '「실효성」は計画や制度が現実に効果を上げる性質です。', '실효성 is the quality of producing real effects in practice.'),
  ),
  choice(5, 'grammar', 1,
    t('기 마련이다', '〜ものだ', 'Inevitably tends to'),
    t('일반적으로 피하기 어려운 결과를 나타내도록 고르세요. 충분한 논의 없이 제도를 바꾸면 현장에서 혼란이 생기___ .', '一般に避けにくい結果を表すよう選んでください。충분한 논의 없이 제도를 바꾸면 현장에서 혼란이 생기___ .', 'Choose the expression for a generally inevitable result: 충분한 논의 없이 제도를 바꾸면 현장에서 혼란이 생기___ .'),
    t('기 마련입니다', '〜ものです', 'inevitably tends to'),
    [t('는 척합니다', '〜するふりをします', 'pretends to'), t('기 나름입니다', '〜次第です', 'depends on how'), t('는 둥 맙니다', '〜するかと思えばやめます', 'does it half-heartedly and stops')],
    2,
    t('‘-기 마련이다’는 어떤 조건에서 자연스럽거나 피하기 어렵게 나타나는 결과를 말합니다.', '「-기 마련이다」はある条件で自然に、または避けにくく生じる結果を表します。', '-기 마련이다 expresses a result that naturally or inevitably follows under a condition.'),
  ),
  choice(5, 'grammar', 2,
    t('는 셈이다', '〜ことになる', 'Amounts to'),
    t('상황을 계산해 해석한 결론이 되도록 고르세요. 하루에 한 시간씩 이동한다면 일주일에 다섯 시간을 길에서 보내___ .', '状況を計算して解釈した結論になるよう選んでください。하루에 한 시간씩 이동한다면 일주일에 다섯 시간을 길에서 보내___ .', 'Choose the expression presenting the calculated interpretation: 하루에 한 시간씩 이동한다면 일주일에 다섯 시간을 길에서 보내___ .'),
    t('는 셈입니다', '〜ことになります', 'amounts to'),
    [t('는 길입니다', '〜する途中です', 'is on the way to'), t('는 중입니다', '〜しているところです', 'is in the middle of doing'), t('는 편입니다', '〜ほうです', 'tends to')],
    3,
    t('‘-는 셈이다’는 앞의 사실을 계산하거나 종합해 얻은 결론을 나타냅니다.', '「-는 셈이다」は前の事実を計算または総合して得た結論を表します。', '-는 셈이다 states a conclusion reached by calculating or summarizing the preceding facts.'),
  ),
  choice(5, 'reading', 1,
    t('정책 평가의 기준', '政策評価の基準', 'Criteria for policy evaluation'),
    t('한 지방정부는 무료 셔틀버스를 운행한 뒤 이용자 수가 늘었다는 이유로 사업이 성공했다고 발표했다. 그러나 연구진은 기존 대중교통 이용자가 셔틀버스로 옮겨 간 것인지, 이동을 포기했던 주민이 새롭게 외출하게 된 것인지 구분해야 한다고 지적했다. 연구진이 추가로 확인하려는 것은 무엇입니까?', 'ある自治体は無料シャトルバスの運行後、利用者数が増えたため事業が成功したと発表しました。しかし研究陣は、既存の公共交通利用者がシャトルへ移ったのか、移動を諦めていた住民が新たに外出するようになったのかを区別すべきだと指摘しました。研究陣が追加で確認しようとしていることは何ですか。', 'A local government called a free shuttle successful because ridership rose. Researchers say it matters whether riders switched from existing transit or previously isolated residents began traveling. What do they want to verify?'),
    t('증가한 이용자가 원래 어떤 이동 행동을 했는지', '増えた利用者が以前どのような移動行動をしていたか', 'how the additional riders traveled before the shuttle'),
    [t('이용자 증가가 무료 운행이 끝난 뒤에도 유지되는지', '利用者増加が無料運行終了後も続くか', 'whether ridership remains higher after free service ends'), t('셔틀 운행으로 기존 대중교통의 혼잡이 줄었는지', 'シャトル運行で既存公共交通の混雑が減ったか', 'whether the shuttle reduced crowding on existing transit'), t('셔틀 이용자의 평균 이동 시간이 짧아졌는지', 'シャトル利用者の平均移動時間が短くなったか', 'whether shuttle users’ average travel time became shorter')],
    0,
    t('사업의 순효과를 판단하려면 늘어난 이용자가 기존 교통수단에서 옮겨 왔는지 새 이동 수요인지 확인해야 합니다.', '事業の純効果を判断するには、増加した利用者が既存交通から移ったのか新しい移動需要なのかを確認する必要があります。', 'To judge the program’s net effect, researchers must distinguish diverted riders from newly enabled trips.'),
  ),
  choice(5, 'reading', 2,
    t('조직의 질문 문화', '組織の質問文化', 'A culture of asking questions'),
    t('어떤 조직은 실수를 줄이기 위해 절차를 자세히 만들었지만, 직원들은 규정을 잘못 이해했을 때도 질문하면 능력이 부족해 보일까 걱정해 침묵했다. 그 결과 작은 오해가 반복되었다. 전문가는 절차를 늘리는 것보다 질문을 환영하고 문제를 일찍 공유하는 분위기가 중요하다고 말했다. 전문가가 강조한 것은 무엇입니까?', 'ある組織はミスを減らすため手順を詳しくしましたが、職員は規定を誤解しても質問すると能力不足に見えることを心配し沈黙しました。その結果、小さな誤解が繰り返されました。専門家は手順を増やすより、質問を歓迎し問題を早く共有する雰囲気が重要だと述べました。専門家が強調したことは何ですか。', 'An organization added detailed procedures, but staff stayed silent when unsure because they feared appearing incapable. What does the expert emphasize?'),
    t('질문과 초기 문제 공유를 안전하게 만드는 분위기', '質問と早期の問題共有を安全にする雰囲気', 'a climate where questions and early problem sharing feel safe'),
    [t('규정을 더 세분화해 해석의 차이를 없애는 것', '規定をさらに細分化して解釈の差をなくすこと', 'eliminating interpretation gaps by adding more detailed rules'), t('질문하기 전에 관리자의 승인을 받게 하는 것', '質問前に管理者の承認を受けさせること', 'requiring managerial approval before asking questions'), t('오해가 생긴 뒤 책임자를 명확히 지정하는 것', '誤解が生じた後に責任者を明確に指定すること', 'assigning responsibility clearly after a misunderstanding occurs')],
    1,
    t('전문가는 규정의 양보다 질문과 문제 제기를 안전하게 받아들이는 조직 문화를 강조했습니다.', '専門家は規定の量より、質問や問題提起を安全に受け入れる組織文化を強調しました。', 'The expert stresses a culture that safely welcomes questions and early concerns, not simply more rules.'),
  ),
  choice(5, 'listening', 1,
    t('조사 설계 검토', '調査設計の検討', 'Reviewing survey design'),
    t('연구자는 설문 조사 전에 무엇을 하자고 제안합니까?', '研究者はアンケート調査の前に何をしようと提案していますか。', 'What does the researcher propose doing before the survey?'),
    t('소수 참여자에게 질문을 시험한다', '少数の参加者で質問を試す', 'test the questions with a small group'),
    [t('본조사의 표본 수를 먼저 늘린다', '本調査の標本数を先に増やす', 'increase the main survey sample first'), t('질문의 순서를 응답자마다 무작위로 바꾼다', '質問順を回答者ごとに無作為化する', 'randomize question order for each respondent'), t('예상 결과를 응답자에게 먼저 설명한다', '予想結果を回答者に先に説明する', 'explain the expected findings to respondents first')],
    2,
    t('질문의 의미가 사람마다 다르게 해석되는지 확인하려고 소규모 예비 조사를 제안했습니다.', '質問の意味が人によって異ならないか確認するため、小規模な予備調査を提案しました。', 'The researcher proposes a small pilot to see whether people interpret the questions differently.'),
    '본조사에 들어가기 전에 질문을 열 명 정도에게 먼저 보여 주면 어떨까요? 같은 문장을 서로 다르게 이해하는지 확인한 뒤 표현을 고치면 결과의 신뢰도를 높일 수 있습니다.',
  ),
  choice(5, 'listening', 2,
    t('전시 기획 조정', '展示企画の調整', 'Adjusting an exhibition plan'),
    t('기획자는 전시 설명문을 어떻게 바꾸기로 했습니까?', '企画者は展示解説文をどのように変えることにしましたか。', 'How will the planner change the exhibition labels?'),
    t('핵심 설명은 짧게 하고 자세한 내용은 별도로 제공한다', '要点は短くし、詳しい内容は別に提供する', 'keep the main text short and provide details separately'),
    [t('벽면 설명은 그대로 두고 글자 크기만 줄인다', '壁面解説はそのままにして文字だけ小さくする', 'keep the wall text unchanged but reduce its font size'), t('핵심 설명 없이 전문 용어의 정의만 덧붙인다', '要点を示さず専門用語の定義だけを加える', 'add definitions of technical terms without a concise overview'), t('모든 설명을 정보 화면으로 옮기고 벽면 글은 없앤다', 'すべての解説を情報画面へ移し壁面の文章をなくす', 'move all explanations to the information screen and remove wall text')],
    3,
    t('관람 흐름과 상세 정보 요구를 함께 충족하려고 짧은 핵심 설명과 별도 상세 자료를 제공하기로 했습니다.', '観覧の流れと詳細情報への需要を両立するため、短い要点と別の詳細資料を提供することにしました。', 'To balance visitor flow with demand for detail, the main labels will be brief and extended information will be separate.'),
    '설명문이 길어서 관람 흐름이 끊긴다는 의견이 많았습니다. 벽에는 핵심만 두세 문장으로 쓰고, 더 알고 싶은 사람은 옆의 정보 화면에서 자세한 내용을 볼 수 있게 합시다.',
  ),
  writing(5, 1,
    t('정책 효과 평가', '政策効果の評価', 'Evaluating policy effects'),
    t('공공 도서관의 운영 시간을 늘리는 정책을 평가할 지표 두 가지와 그 이유를 다섯 문장으로 쓰세요.', '公共図書館の開館時間を延長する政策を評価する指標二つと、その理由を五文で書いてください。', 'In five sentences, propose two indicators for evaluating longer public-library hours and explain why they matter.'),
    t('예: 첫째, 연장 시간대의 실제 이용자 수를 확인해야 합니다. 이는 추가 운영이 필요한 수요가 있는지 보여 줍니다. 둘째, 기존 이용이 어려웠던 직장인과 학생의 이용 비율을 조사할 필요가 있습니다. 전체 이용자 수만 늘어도 접근성 격차가 줄지 않을 수 있기 때문입니다. 두 지표를 함께 보면 정책의 규모와 형평성을 모두 평가할 수 있습니다.', '例：第一に延長時間帯の実利用者数を確認すべきです。これは追加運営を必要とする需要を示します。第二に、これまで利用しにくかった会社員と学生の利用割合を調べる必要があります。総利用者数が増えてもアクセス格差が縮まらない場合があるためです。二つの指標を合わせれば政策の規模と公平性を評価できます。', 'Example: First, measure actual visits during the added hours. This shows whether there is demand for longer operation. Second, measure use by workers and students who previously faced access barriers. Total visits alone may not show whether access gaps narrowed. Together the indicators cover both scale and equity.'),
    t('서로 다른 측면을 측정하는 지표 두 가지를 제시하고, 각 지표의 필요성을 설명한 뒤 두 지표를 함께 해석하는 결론을 포함합니다.', '異なる側面を測る指標二つを示し、それぞれの必要性を説明し、二つを合わせて解釈する結論を含めます。', 'Provide two indicators measuring different dimensions, justify each one, and conclude by explaining how they should be interpreted together.'),
  ),
  writing(5, 2,
    t('상반된 의견 조정', '相反する意見の調整', 'Reconciling opposing views'),
    t('도심 차량 운행을 줄이자는 의견과 상인의 접근성 우려를 함께 고려한 해결책을 다섯 문장으로 제안하세요.', '都心の車両通行を減らす意見と商店主のアクセスへの懸念をともに考慮した解決策を五文で提案してください。', 'In five sentences, propose a solution that considers both reducing downtown traffic and merchants’ concerns about access.'),
    t('예: 도심의 일반 차량은 혼잡 시간에 단계적으로 제한할 수 있습니다. 대신 배송 차량은 정해진 시간대에 진입하도록 허용해야 합니다. 외곽 주차장과 상점가를 잇는 순환버스도 운영할 필요가 있습니다. 정책 시행 전후의 매출과 보행자 수를 공개해 영향을 점검해야 합니다. 결과가 좋지 않은 구간은 상인과 협의해 운영 시간을 조정할 수 있습니다.', '例：都心の一般車両は混雑時間帯に段階的に制限できます。一方、配送車両は指定時間に進入できるようにすべきです。郊外駐車場と商店街を結ぶ循環バスも必要です。実施前後の売上と歩行者数を公開して影響を検証すべきです。結果がよくない区間は商店主と協議して運用時間を調整できます。', 'Example: General traffic can be restricted gradually during peak times. Delivery vehicles should instead be allowed in designated windows. A shuttle should connect peripheral parking with the shopping district. Before-and-after sales and pedestrian data should be published to assess the impact. Operating hours can be adjusted with merchants where results are poor.'),
    t('교통 감축과 상점 접근성 양쪽의 이해관계를 명시하고, 예외 또는 대체 수단, 측정 지표, 사후 조정 방법을 포함한 실행 가능한 제안을 씁니다.', '交通削減と店舗アクセス双方の利害を明示し、例外または代替手段、測定指標、事後調整方法を含む実行可能な提案を書きます。', 'Acknowledge both interests and give an actionable proposal including an exception or alternative, measurement indicators, and a method for later adjustment.'),
  ),

  choice(6, 'vocab', 1,
    t('핵심 요소의 누락', '核心要素の見落とし', 'Overlooking a key factor'),
    t('중요한 사실이나 요소를 제대로 살피지 않고 지나치는 것을 나타내는 말은 무엇입니까?', '重要な事実や要素を十分に検討せず見過ごすことを表す言葉は何ですか。', 'Which word means failing to notice or properly consider an important fact or factor?'),
    t('간과하다', '看過する', 'overlook'),
    [t('숙고하다', '熟考する', 'deliberate'), t('규명하다', '究明する', 'clarify'), t('포괄하다', '包括する', 'encompass')],
    0,
    t('간과하다는 중요성을 알아차리지 못하거나 충분히 고려하지 않고 넘긴다는 뜻입니다.', '「간과하다」は重要性に気づかない、または十分考慮せず見過ごすという意味です。', '간과하다 means overlooking something by failing to recognize or sufficiently consider its importance.'),
  ),
  choice(6, 'vocab', 2,
    t('논의의 결과', '議論の帰結', 'Outcome of an argument'),
    t('여러 원인이나 논리적 과정이 결국 어떤 결과에 이르는 것을 나타내는 말은 무엇입니까?', '複数の原因や論理的過程が最終的にある結果へ至ることを表す言葉は何ですか。', 'Which word describes causes or a line of reasoning ultimately leading to a result?'),
    t('귀결되다', '帰結する', 'result in'),
    [t('유보되다', '留保される', 'be withheld'), t('분산되다', '分散する', 'be dispersed'), t('상쇄되다', '相殺される', 'be offset')],
    1,
    t('귀결되다는 논의나 상황이 마지막에 특정한 결론이나 결과로 이어진다는 뜻입니다.', '「귀결되다」は議論や状況が最終的に特定の結論や結果へ至るという意味です。', '귀결되다 means that an argument or situation ultimately leads to a particular conclusion or result.'),
  ),
  choice(6, 'grammar', 1,
    t('을지언정', '〜ことはあっても', 'Even if ... still'),
    t('앞의 불리한 상황은 받아들여도 뒤의 원칙은 포기하지 않겠다는 뜻이 되도록 고르세요. 시간이 더 걸릴___ 검증 절차를 생략하지는 않겠습니다.', '前の不利な状況は受け入れても後ろの原則は譲らない意味になるよう選んでください。시간이 더 걸릴___ 검증 절차를 생략하지는 않겠습니다.', 'Choose the ending meaning that even if more time is accepted, verification will not be abandoned: 시간이 더 걸릴___ 검증 절차를 생략하지는 않겠습니다.'),
    t('지언정', '〜ことはあっても', 'even if it means'),
    [t('뿐더러', '〜だけでなく', 'not only'), t('수록', '〜すればするほど', 'the more'), t('따름이며', '〜だけであり', 'merely')],
    2,
    t('‘-을지언정’은 앞의 상황을 인정하거나 감수하더라도 뒤의 원칙은 양보하지 않음을 강조합니다.', '「-을지언정」は前の状況を認めたり甘受したりしても、後ろの原則は譲らないことを強調します。', '-을지언정 concedes the preceding disadvantage while strongly refusing to compromise the following principle.'),
  ),
  choice(6, 'grammar', 2,
    t('기에 망정이지', '〜からよかったものの', 'It was fortunate that'),
    t('다행인 조건이 없었다면 나쁜 결과가 생겼을 것이라는 뜻이 되도록 고르세요. 자료를 미리 복사해 두었___ 서버 장애 중에도 회의를 계속할 수 있었습니다.', '幸いな条件がなければ悪い結果になった意味になるよう選んでください。자료를 미리 복사해 두었___ 서버 장애 중에도 회의를 계속할 수 있었습니다.', 'Choose the expression meaning a fortunate condition prevented a bad result: 자료를 미리 복사해 두었___ 서버 장애 중에도 회의를 계속할 수 있었습니다.'),
    t('기에 망정이지', '〜からよかったものの', 'it was fortunate that'),
    [t('으면 몰라도', '〜ならともかく', 'if that were the case, perhaps'), t('는 한편', '〜する一方で', 'while also'), t('는 탓에', '〜したせいで', 'because of, with blame')],
    3,
    t('‘-기에 망정이지’는 앞의 일이 다행히 이루어져 예상할 수 있던 나쁜 결과를 피했음을 나타냅니다.', '「-기에 망정이지」は前のことが幸い実現し、起こり得た悪い結果を避けられたことを表します。', '-기에 망정이지 says that a fortunate preceding circumstance prevented a potentially bad outcome.'),
  ),
  choice(6, 'reading', 1,
    t('알고리즘 설명 책임', 'アルゴリズムの説明責任', 'Algorithmic accountability'),
    t('공공기관이 자동 심사 시스템을 도입하면서 정확도가 높다는 점만 공개했다. 그러나 시민단체는 잘못된 판정에 이의를 제기하는 절차와 어떤 정보가 판단에 영향을 주었는지 설명하는 기준도 필요하다고 주장했다. 기관은 영업 비밀 보호를 이유로 세부 공개가 어렵다고 답했다. 시민단체의 핵심 요구는 무엇입니까?', '公共機関が自動審査システムを導入し、精度が高い点だけを公開しました。しかし市民団体は誤判定への異議申立手続きと、どの情報が判断に影響したかを説明する基準も必要だと主張しました。機関は営業秘密保護を理由に詳細公開が難しいと答えました。市民団体の核心的要求は何ですか。', 'A public agency disclosed only the accuracy of an automated screening system. A civic group also wants a way to appeal errors and standards explaining what influenced decisions. What is its central demand?'),
    t('판정에 이의를 제기하고 판단 근거를 이해할 수 있는 장치', '判定に異議を申し立て、判断根拠を理解できる仕組み', 'mechanisms to appeal decisions and understand their basis'),
    [t('집단별 정확도 수치를 정기적으로 다시 공개하는 장치', '集団別の精度を定期的に再公開する仕組み', 'a mechanism for regularly republishing accuracy by demographic group'), t('영업 비밀에 해당하는 원천 코드를 전면 공개하는 원칙', '営業秘密に当たるソースコードを全面公開する原則', 'a rule requiring full disclosure of trade-secret source code'), t('담당자가 최종 승인했는지만 표시하는 절차', '担当者が最終承認したかだけを表示する手続き', 'a process showing only whether a staff member gave final approval')],
    0,
    t('시민단체는 정확도만이 아니라 잘못된 판정을 다툴 절차와 판단에 사용된 근거를 이해할 수 있는 설명 책임을 요구합니다.', '市民団体は精度だけでなく、誤判定を争う手続きと判断根拠を理解できる説明責任を求めています。', 'The group seeks accountability through an appeal process and understandable reasons for decisions, not accuracy alone.'),
  ),
  choice(6, 'reading', 2,
    t('기후 적응 정책', '気候適応政策', 'Climate adaptation policy'),
    t('한 도시는 폭염 대책으로 도심 전체의 나무 수를 늘리기로 했다. 전문가는 평균 기온을 낮추는 효과도 중요하지만, 그늘이 부족한 지역에는 노인과 야외 노동자가 많이 산다는 점을 고려해 식재 위치를 정해야 한다고 말했다. 전문가는 무엇을 강조하고 있습니까?', 'ある都市は猛暑対策として都心全体の樹木を増やすことにしました。専門家は平均気温を下げる効果も重要だが、日陰の少ない地域には高齢者や屋外労働者が多く住む点を考慮して植樹場所を決めるべきだと述べました。専門家は何を強調していますか。', 'A city plans more trees to address extreme heat. An expert says locations should account for neighborhoods with little shade and many elderly residents or outdoor workers. What is emphasized?'),
    t('취약한 주민의 노출 정도를 고려한 식재 우선순위', '脆弱な住民の曝露度を考慮した植樹の優先順位', 'planting priorities based on vulnerable residents’ exposure'),
    [t('도시 평균 기온을 가장 크게 낮추는 식재 효율', '都市平均気温を最も下げる植樹効率', 'planting efficiency that maximizes citywide average cooling'), t('지역별 인구수에 비례한 동일 기준의 나무 배분', '地域人口に比例した一律基準の樹木配分', 'uniform tree allocation proportional to neighborhood population'), t('식재 뒤 도심 평균 기온만으로 성과를 평가하는 방식', '植樹後に都心平均気温だけで成果を評価する方式', 'evaluating the program only through citywide average temperature')],
    1,
    t('전문가는 도시 평균뿐 아니라 폭염에 더 취약한 사람이 사는 지역을 우선해야 한다고 말합니다.', '専門家は都市平均だけでなく、猛暑により脆弱な人が住む地域を優先すべきだと述べています。', 'The expert argues that planting should prioritize areas where heat-vulnerable people are most exposed.'),
  ),
  choice(6, 'listening', 1,
    t('위원회 의사 결정', '委員会の意思決定', 'Committee decision-making'),
    t('발언자는 제안에 대한 결정을 미루자고 하는 이유가 무엇입니까?', '発言者が提案についての決定を延期しようとする理由は何ですか。', 'Why does the speaker want to postpone the decision on the proposal?'),
    t('영향을 받는 집단의 의견이 충분히 반영되지 않았기 때문에', '影響を受ける集団の意見が十分反映されていないため', 'because affected groups have not been adequately heard'),
    [t('통계 분석이 아직 끝나지 않았기 때문에', '統計分析がまだ終わっていないため', 'because the statistical analysis is not yet complete'), t('두 집단이 이미 서로 다른 요구를 제출했기 때문에', '二つの集団がすでに異なる要求を提出したため', 'because the two groups have already submitted conflicting requests'), t('위원회가 일정 지연을 허용하지 않았기 때문에', '委員会が日程延期を認めていないため', 'because the committee has not permitted a delay')],
    2,
    t('발언자는 통계 검토와 별개로 정책의 영향을 직접 받는 집단의 의견 수렴이 부족하다고 지적했습니다.', '発言者は統計の検討とは別に、政策の影響を直接受ける集団への意見聴取が不足していると指摘しました。', 'The speaker says the committee reviewed statistics but has not sufficiently consulted groups directly affected by the policy.'),
    '통계 자료는 충분히 검토했지만 이 정책의 영향을 직접 받는 소규모 사업자와 장애인 단체의 의견은 아직 듣지 못했습니다. 일정이 조금 늦어지더라도 두 집단의 의견을 들은 뒤 결정해야 합니다.',
  ),
  choice(6, 'listening', 2,
    t('연구 결과 해석', '研究結果の解釈', 'Interpreting research findings'),
    t('연구자가 결과의 일반화에 신중해야 한다고 말하는 이유는 무엇입니까?', '研究者が結果の一般化に慎重であるべきだという理由は何ですか。', 'Why does the researcher urge caution in generalizing the findings?'),
    t('특정 연령과 지역의 참여자가 지나치게 많기 때문에', '特定の年齢と地域の参加者が多すぎるため', 'because participants are overly concentrated in one age group and region'),
    [t('전체 응답자 수가 결론을 내리기에 너무 적기 때문에', '全回答者数が結論を出すには少なすぎるため', 'because the total number of respondents is too small'), t('한 가지 분석 방법만 사용했기 때문에', '一つの分析方法しか使っていないため', 'because only one analytical method was used'), t('조사 기간이 짧아 계절 차이를 비교하지 못했기 때문에', '調査期間が短く季節差を比較できなかったため', 'because the survey period was too short to compare seasons')],
    3,
    t('표본이 특정 연령대와 지역에 치우쳐 있어 결과를 전체 인구로 확대해 해석하기 어렵습니다.', '標本が特定の年齢層と地域に偏っているため、結果を人口全体へ拡張して解釈するのは難しいです。', 'The sample is concentrated in a particular age group and region, limiting generalization to the wider population.'),
    '응답 수 자체는 많지만 참여자의 대부분이 이십 대이고 수도권에 살고 있습니다. 따라서 이 결과를 모든 연령과 지역의 경향이라고 해석하기 전에 표본의 편향을 고려해야 합니다.',
  ),
  writing(6, 1,
    t('근거 종합 논증', '根拠を統合した論証', 'Evidence synthesis argument'),
    t('온라인 공공서비스를 기본 방식으로 전환하자는 주장에 대해 효율성과 접근성의 근거를 종합하여 여섯 문장으로 논평하세요.', 'オンライン公共サービスを基本方式に転換する主張について、効率性とアクセシビリティの根拠を統合し六文で論評してください。', 'In six sentences, evaluate making online delivery the default for public services by synthesizing evidence about efficiency and accessibility.'),
    t('예: 온라인 전환은 반복 업무를 줄여 처리 시간을 단축할 수 있습니다. 이용자는 장소에 구애받지 않고 신청할 수 있다는 장점도 있습니다. 그러나 디지털 기기나 보조 기술을 쓰기 어려운 사람에게는 새로운 장벽이 됩니다. 따라서 온라인을 기본으로 하되 대면 창구와 전화 지원을 함께 유지해야 합니다. 처리 시간뿐 아니라 연령과 장애 여부에 따른 이용 성공률을 공개해야 합니다. 이 지표를 바탕으로 지원 수단을 조정할 때 효율성과 접근성을 함께 높일 수 있습니다.', '例：オンライン化は反復業務を減らし処理時間を短縮できます。利用者が場所に縛られず申請できる長所もあります。しかしデジタル機器や支援技術を使いにくい人には新たな障壁となります。そのためオンラインを基本としつつ対面窓口と電話支援も維持すべきです。処理時間だけでなく年齢や障害の有無別の利用成功率を公開すべきです。この指標に基づき支援手段を調整すれば効率性とアクセス性をともに高められます。', 'Example: Online delivery can reduce repetitive work and processing time. Users can also apply without being limited by location. However, this creates new barriers for people who struggle with devices or assistive technology. Face-to-face and telephone support should therefore remain alongside an online default. Success rates by age and disability should be published together with processing time. Support can then be adjusted using those indicators to improve both efficiency and access.'),
    t('효율성의 근거와 접근성의 반론을 각각 제시하고, 두 관점을 연결한 조건부 결론, 보완 수단, 측정 가능한 평가 지표를 포함합니다.', '効率性の根拠とアクセス性の反論をそれぞれ示し、両観点を結ぶ条件付き結論、補完手段、測定可能な評価指標を含めます。', 'Present evidence for efficiency and a counterargument about access, then give a conditional conclusion with safeguards and measurable evaluation indicators.'),
  ),
  writing(6, 2,
    t('인과 관계 분석', '因果関係の分析', 'Causal analysis'),
    t('청년층의 지역 문화행사 참여가 감소한 현상에 대해 가능한 원인 두 가지, 이를 구분할 자료, 대응책을 여섯 문장으로 쓰세요.', '若年層の地域文化行事参加が減少した現象について、考えられる原因二つ、それらを区別する資料、対応策を六文で書いてください。', 'In six sentences, analyze two possible causes of declining youth participation in local cultural events, identify data that would distinguish them, and propose responses.'),
    t('예: 참여 감소는 행사 정보가 청년층에게 도달하지 않기 때문일 수 있습니다. 다른 가능성은 행사 시간과 청년층의 근무 시간이 겹치는 것입니다. 두 원인을 구분하려면 정보 노출 경로와 불참 이유를 함께 조사해야 합니다. 홍보 게시물의 조회 수만으로는 실제 일정 장벽을 알 수 없습니다. 정보 부족이 크다면 청년층이 사용하는 채널을 확대하고, 시간 문제가 크다면 야간이나 주말 프로그램을 시험할 수 있습니다. 시범 운영 전후의 인지도와 참석률을 비교해 대응책을 조정해야 합니다.', '例：参加減少は行事情報が若年層に届かないためかもしれません。別の可能性は行事時間と若年層の勤務時間が重なることです。二つの原因を区別するには情報接触経路と不参加理由をともに調査すべきです。広報投稿の閲覧数だけでは実際の時間的障壁は分かりません。情報不足が大きければ若者が使う媒体を増やし、時間問題が大きければ夜間や週末のプログラムを試せます。試行前後の認知度と参加率を比べて対応策を調整すべきです。', 'Example: Participation may be falling because event information does not reach young people. Another possibility is that event times conflict with their work schedules. Survey both exposure channels and reasons for nonattendance to distinguish these causes. Counts of promotional views alone cannot reveal scheduling barriers. Expand youth-facing channels if awareness is low, or pilot evenings and weekends if timing is the issue. Compare awareness and attendance before and after the pilot to adjust the response.'),
    t('서로 경쟁할 수 있는 원인 두 가지를 분리해 제시하고, 원인을 판별할 자료, 각 원인에 대응하는 조치, 전후 비교를 통한 재평가 방법을 포함합니다.', '競合し得る原因二つを分けて示し、原因を判別する資料、各原因への対応、前後比較による再評価方法を含めます。', 'Separate two competing causes and include data that can distinguish them, a response matched to each cause, and a before-and-after reassessment method.'),
  ),
] as const;

function stableRef(item: TopikOwnerBatch6Draft): string {
  return `topik:owner:batch6:grade${item.grade}:${item.section}:${item.sequence}`;
}

function unitId(item: TopikOwnerBatch6Draft): string {
  return `${item.id}-unit`;
}

function answerJson(item: TopikOwnerBatch6Draft): string {
  if (!item.choices) {
    if (!item.rubric) throw new Error(`Constructed-response item is missing a multilingual rubric: ${item.id}`);
    return JSON.stringify({
      sample_answer_ko: item.explanation.ko.replace(/^예: /u, ''),
      sample_answer_ja: item.explanation.ja.replace(/^例：/u, ''),
      sample_answer_en: item.explanation.en.replace(/^Example: /u, ''),
      rubric_ko: item.rubric.ko,
      rubric_ja: item.rubric.ja,
      rubric_en: item.rubric.en,
    });
  }
  return JSON.stringify({
    choices: item.choices.map((candidate) => candidate.ko),
    choices_ko: item.choices.map((candidate) => candidate.ko),
    choices_ja: item.choices.map((candidate) => candidate.ja),
    choices_en: item.choices.map((candidate) => candidate.en),
    answer_index: item.answer_index,
  });
}

export function buildTopikOwnerBatch6Statements(ledger: IndependentReviewLedger): string[] {
  for (const item of TOPIK_OWNER_BATCH_6) {
    requireIndependentReview(item.id, item.answer_index ?? null, ledger);
  }
  return [
    [
      'INSERT INTO `sources` (`code`, `title`, `file_path`, `version`)',
      `VALUES (${esc(TOPIK_OWNER_BATCH_6_SOURCE_CODE)}, 'JLPT N2/N1 Practice v1 · TOPIK Owner Batch 6 자체 저작', ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourcePath)}, 'source-v1-${NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.intakeArtifactSha256.slice(0, 16)}')`,
      'ON CONFLICT(`code`) DO UPDATE SET `title` = excluded.`title`, `file_path` = excluded.`file_path`, `version` = excluded.`version`, `updated_at` = unixepoch();',
    ].join('\n'),
    [
      'INSERT OR IGNORE INTO `content_source_assets`',
      '  (`id`, `asset_kind`, `source_url`, `license_id`, `license_url`, `attribution_text`, `allowed_use`, `source_sha256`, `generated_at`, `selection_reason`)',
      `VALUES (${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)}, 'self-authored-fixture', ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourceUrl)}, ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.licenseId)}, ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.licenseUrl)},`,
      `  ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.attribution)},`,
      `  ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.allowedUse)},`,
      `  ${esc(NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourceSha256)}, ${NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.generatedAt}, 'Draft TOPIK grade 3-6 owner curriculum for independent review; Korean listening uses Google browser speech only; R2 pronunciation prohibited.');`,
    ].join('\n'),
    ...TOPIK_OWNER_BATCH_6.flatMap((item) => [
      [
        'INSERT OR IGNORE INTO `topik_owner_authored_curriculum_units`',
        '  (`id`, `target_grade`, `stable_ref`, `section`, `title_ko`, `title_ja`, `title_en`, `source_asset_id`)',
        `VALUES (${esc(unitId(item))}, ${item.grade}, ${esc(`${stableRef(item)}:unit`)}, ${esc(item.section)}, ${esc(item.title.ko)}, ${esc(item.title.ja)}, ${esc(item.title.en)}, ${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)});`,
      ].join('\n'),
      [
        'INSERT OR IGNORE INTO `topik_owner_authored_curriculum_items`',
        '  (`id`, `unit_id`, `target_grade`, `stable_ref`, `item_type`, `prompt_ko`, `prompt_ja`, `prompt_en`, `answer_json`, `explanation_ko`, `explanation_ja`, `explanation_en`, `audio_required`, `audio_text_ko`, `source_asset_id`)',
        `VALUES (${esc(item.id)}, ${esc(unitId(item))}, ${item.grade}, ${esc(stableRef(item))}, ${esc(item.section)}, ${esc(item.prompt.ko)}, ${esc(item.prompt.ja)}, ${esc(item.prompt.en)}, ${esc(answerJson(item))}, ${esc(item.explanation.ko)}, ${esc(item.explanation.ja)}, ${esc(item.explanation.en)}, ${item.section === 'listening' ? 1 : 0}, ${item.audio_text_ko ? esc(item.audio_text_ko) : 'NULL'}, ${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)});`,
      ].join('\n'),
      [
        'INSERT OR IGNORE INTO `learning_content_stable_refs`',
        '  (`stable_ref`, `learning_track`, `item_type`, `item_id`, `level_tag`, `source_asset_id`)',
        `VALUES (${esc(stableRef(item))}, 'topik-ko', 'topik-owner-item', ${esc(item.id)}, ${esc(`TOPIK-${item.grade}`)}, ${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)});`,
      ].join('\n'),
      ...(item.section === 'listening' ? [[
        'INSERT OR IGNORE INTO `content_speech_bindings`',
        '  (`id`, `stable_ref`, `item_type`, `item_id`, `language`, `speech_role`, `provider`, `binding_state`, `text_source`, `unavailable_reason`)',
        `VALUES (${esc(`speech-binding:${stableRef(item)}`)}, ${esc(stableRef(item))}, 'topik-owner-item', ${esc(item.id)}, 'ko', 'listening', 'google-browser', 'ready', 'audio-script', NULL);`,
      ].join('\n')] : []),
    ]),
  ];
}

export function buildTopikOwnerBatch6Plan(ledger: IndependentReviewLedger) {
  const statements = buildTopikOwnerBatch6Statements(ledger);
  return {
    statements,
    manifest: {
      sourceCode: TOPIK_OWNER_BATCH_6_SOURCE_CODE,
      sourceAssetId: TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID,
      sourcePath: NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourcePath,
      sourceSha256: NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.sourceSha256,
      sourceEvidenceSha256: NEXT_CONTENT_EXPANSION_SOURCE_EVIDENCE.intakeArtifactSha256,
      counts: {
        units: 40,
        items: 40,
        stableRefs: 40,
        speechBindings: 8,
        contentRows: 80,
      },
      releaseState: 'draft' as const,
      reviewerState: 'pending' as const,
    },
  };
}

export function topikOwnerBatch6ContentRowsSql(): string {
  return `SELECT (SELECT count(*) FROM topik_owner_authored_curriculum_units WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)}) + (SELECT count(*) FROM topik_owner_authored_curriculum_items WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_6_SOURCE_ASSET_ID)}) AS count;`;
}
