import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { REPO_ROOT } from './constants.js';
import { esc } from './utils.js';

export const TOPIK_OWNER_BATCH_4_SOURCE_CODE = 'TOPIK-A4';
export const TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID = 'source-asset:topik-owner-authored-grades-1-6-batch-4-2026-08-09';
export const TOPIK_OWNER_BATCH_4_PATH = path.join(REPO_ROOT, 'docs/07_topik/05_owner_authored_grades_1_6_batch_4.md');

const REPOSITORY_URL = 'https://github.com/kordokrip/JLPT/blob/main/docs/07_topik/05_owner_authored_grades_1_6_batch_4.md';
const LICENSE_URL = 'https://github.com/kordokrip/JLPT/blob/main/docs/ATTRIBUTIONS.md#학습-콘텐츠와-provenance';

type Section = 'vocab' | 'grammar' | 'reading' | 'listening' | 'writing';
type ItemSeed = { grade: number; section: Section; titleKo: string; titleJa: string; titleEn: string; promptKo: string; promptJa: string; promptEn: string; choices?: readonly string[]; answerIndex?: number; explanationKo: string; explanationJa: string; explanationEn: string; audioTextKo: string; };

function choice(grade: number, section: Exclude<Section, 'writing'>, titleKo: string, titleJa: string, titleEn: string, promptKo: string, promptJa: string, promptEn: string, choices: readonly string[], answerIndex: number, explanationKo: string, explanationJa: string, explanationEn: string, audioTextKo: string): ItemSeed {
  return { grade, section, titleKo, titleJa, titleEn, promptKo, promptJa, promptEn, choices, answerIndex, explanationKo, explanationJa, explanationEn, audioTextKo };
}

function writing(grade: number, titleKo: string, titleJa: string, titleEn: string, promptKo: string, promptJa: string, promptEn: string, exampleKo: string, exampleJa: string, exampleEn: string): ItemSeed {
  return { grade, section: 'writing', titleKo, titleJa, titleEn, promptKo, promptJa, promptEn, explanationKo: `예: ${exampleKo}`, explanationJa: `例：${exampleJa}`, explanationEn: `Example: ${exampleEn}`, audioTextKo: exampleKo };
}

const ITEMS: readonly ItemSeed[] = [
  choice(1, 'vocab', '시장 물건', '市場の品物', 'Market items', '과일이나 채소를 담아 가는 것은 무엇입니까?', '果物や野菜を入れて持ち帰るものは何ですか。', 'What do you use to carry fruit or vegetables home?', ['봉지', '지하철', '교실', '약속'], 0, '봉지는 물건을 담아 가는 데 사용합니다.', '袋は物を入れて持ち帰るときに使います。', 'A bag is used to carry items.', '봉지'),
  choice(1, 'grammar', '으세요', '〜してください', 'Please do', '여기에서 이름을 쓰___ .', 'ここに名前を書い___。', 'Please write your name here.', ['으세요', '고 싶어요', '에서', '지만'], 0, '상대에게 공손하게 부탁할 때 으세요를 씁니다.', '相手に丁寧に頼むとき「으세요」を使います。', 'Use 으세요 for a polite request.', '여기에서 이름을 쓰세요.'),
  choice(1, 'reading', '분실물 안내', '忘れ物案内', 'Lost-property notice', '지문: 파란 우산을 잃어버린 사람은 안내 데스크에 와서 이름을 말해 주세요.\n질문: 우산을 잃어버린 사람은 어디에 가야 합니까?', '本文：青い傘をなくした人は案内デスクに来て名前を言ってください。\n質問：傘をなくした人はどこへ行きますか。', 'Text: If you lost a blue umbrella, go to the information desk. Where should you go?', ['안내 데스크', '시장 입구', '교실', '버스 정류장'], 0, '안내 데스크에 오라고 했습니다.', '案内デスクに来るよう書いてあります。', 'The notice says to go to the information desk.', '파란 우산을 잃어버린 사람은 안내 데스크에 와서 이름을 말해 주세요.'),
  choice(1, 'listening', '시장 방송', '市場の案内放送', 'Market announcement', '방송에서 사람들은 무엇을 조심해야 합니까?', '放送で人々は何に気をつけるべきですか。', 'What should people be careful about?', ['바닥이 미끄러운 것', '문이 닫힌 것', '비가 오는 것', '버스 시간'], 0, '바닥이 젖어 미끄러우니 조심하라고 합니다.', '床がぬれて滑りやすいので注意するよう言っています。', 'The announcement warns that the floor is slippery.', '시장 안 바닥이 젖어 있습니다. 미끄러우니 조심하세요.'),
  writing(1, '가게에서 묻기', '店で質問する', 'Asking in a shop', '가게에서 물건의 가격을 묻는 한 문장을 써 보세요.', '店で品物の値段を尋ねる一文を書いてみましょう。', 'Write one sentence asking the price of an item in a shop.', '이 사과는 얼마예요?', 'このりんごはいくらですか。', 'How much is this apple?'),

  choice(2, 'vocab', '대중교통', '公共交通', 'Public transport', '많은 사람이 함께 타고 다니는 버스나 지하철을 무엇이라고 합니까?', '多くの人が一緒に利用するバスや地下鉄を何といいますか。', 'What do you call buses and subways used by many people?', ['대중교통', '음식점', '운동장', '숙제'], 0, '버스와 지하철은 대중교통에 속합니다.', 'バスや地下鉄は公共交通に入ります。', 'Buses and subways are public transport.', '대중교통'),
  choice(2, 'grammar', '으려고 하다', '〜しようとする', 'Intend to', '저는 내일 일찍 출발하___ 합니다.', '私は明日早く出発しようとし___。', 'I intend to leave early tomorrow.', ['려고', '지만', '에서', '고 싶어'], 0, '어떤 계획이나 의도를 말할 때 으려고 하다를 씁니다.', '計画や意図を言うとき「으려고 하다」を使います。', 'Use 으려고 하다 to state an intention.', '저는 내일 일찍 출발하려고 합니다.'),
  choice(2, 'reading', '버스 안내', 'バス案内', 'Bus notice', '지문: 12번 버스는 공사 때문에 오늘 학교 앞 정류장에 서지 않습니다. 도서관 앞에서 타세요.\n질문: 오늘 12번 버스는 어디에서 타야 합니까?', '本文：12番バスは工事のため今日学校前の停留所には止まりません。図書館前で乗ってください。\n質問：今日12番バスはどこで乗りますか。', 'Text: Bus 12 will not stop at the school today. Where should you board?', ['도서관 앞', '학교 앞', '시장 안', '역 안'], 0, '학교 앞이 아니라 도서관 앞에서 타야 합니다.', '学校前ではなく図書館前で乗る必要があります。', 'You must board in front of the library.', '12번 버스는 오늘 도서관 앞에서 타세요.'),
  choice(2, 'listening', '환승 약속', '乗り換えの約束', 'Transfer plan', '두 사람은 어디에서 만나기로 합니까?', '二人はどこで会うことにしますか。', 'Where do the two people decide to meet?', ['2호선 환승역', '학교 앞', '영화관 안', '시장 입구'], 0, '2호선으로 갈아타는 역에서 만나기로 합니다.', '2号線に乗り換える駅で会うことにします。', 'They decide to meet at the Line 2 transfer station.', '저는 2호선으로 갈아탈 거예요. 그럼 환승역에서 만나요.'),
  writing(2, '주말 계획', '週末の計画', 'Weekend plan', '주말에 하려는 일을 두 문장으로 써 보세요.', '週末にするつもりのことを二文で書いてみましょう。', 'Write two sentences about what you intend to do this weekend.', '토요일에는 친구를 만나려고 해요. 일요일에는 집에서 쉴 거예요.', '土曜日は友だちに会うつもりです。日曜日は家で休みます。', 'I plan to meet a friend on Saturday. I will rest at home on Sunday.'),

  choice(3, 'vocab', '직장 전화', '職場の電話', 'Workplace call', '회사에서 일을 맡은 사람에게 전화를 연결해 주는 일을 무엇이라고 합니까?', '会社で担当者に電話をつなぐことを何といいますか。', 'What do you call connecting a call to the person in charge?', ['연결하다', '예약하다', '출발하다', '운동하다'], 0, '전화를 다른 사람에게 이어 주는 것을 연결한다고 합니다.', '電話を別の人につなぐことを「連結する」といいます。', 'Connecting a call means putting it through to another person.', '연결하다'),
  choice(3, 'grammar', '아/어서', '〜ので', 'Because', '회의가 있어서 지금 통화하기 어렵___ .', '会議があるので今電話するのは難し___。', 'Because there is a meeting, it is hard to talk now.', ['아서', '려고', '지만', '세요'], 0, '이유를 자연스럽게 이어 말할 때 아/어서를 씁니다.', '理由を自然につなげるとき「아/어서」を使います。', 'Use 아/어서 to connect a reason.', '회의가 있어서 지금 통화하기 어려워요.'),
  choice(3, 'reading', '회의 일정', '会議日程', 'Meeting schedule', '지문: 부서 회의는 수요일 오전 열 시에 시작합니다. 자료는 화요일 오후까지 이메일로 보내 주세요.\n질문: 자료는 언제까지 보내야 합니까?', '本文：部署会議は水曜日午前十時に始まります。資料は火曜日午後までにメールで送ってください。\n質問：資料はいつまでに送るべきですか。', 'Text: Send the materials by when?', ['화요일 오후', '수요일 오전', '월요일 아침', '금요일 저녁'], 0, '자료는 화요일 오후까지 보내야 합니다.', '資料は火曜日の午後までに送る必要があります。', 'The materials must be sent by Tuesday afternoon.', '자료는 화요일 오후까지 이메일로 보내 주세요.'),
  choice(3, 'listening', '업무 요청', '業務依頼', 'Work request', '팀장은 무엇을 먼저 해 달라고 합니까?', 'チーム長は何を先にしてほしいと言っていますか。', 'What does the team leader ask to do first?', ['고객에게 답장하기', '회의를 취소하기', '문을 닫기', '점심 먹기'], 0, '고객의 질문에 먼저 답장해 달라고 요청합니다.', '顧客の質問に先に返信してほしいと頼んでいます。', 'The leader asks for a reply to the customer first.', '고객의 질문이 왔어요. 회의 전에 먼저 답장해 주세요.'),
  writing(3, '정중한 부탁', '丁寧な依頼', 'Polite request', '동료에게 자료를 보내 달라고 정중히 부탁하는 두 문장을 써 보세요.', '同僚に資料を送ってほしいと丁寧に頼む二文を書いてみましょう。', 'Write two polite sentences asking a colleague to send materials.', '시간이 되시면 자료를 보내 주실 수 있을까요? 내일 회의 전에 확인하고 싶습니다.', '時間があれば資料を送っていただけますか。明日の会議前に確認したいです。', 'If you have time, could you send the materials? I would like to check them before tomorrow’s meeting.'),

  choice(4, 'vocab', '지역 정책', '地域政策', 'Local policy', '지역 주민의 생활을 더 좋게 하기 위해 시청이 마련한 계획을 무엇이라고 합니까?', '地域住民の生活をより良くするために市役所が用意した計画を何といいますか。', 'What is a city plan designed to improve local residents’ lives called?', ['정책', '표정', '방학', '약속'], 0, '정책은 문제를 해결하거나 목표를 이루기 위한 공공 계획입니다.', '政策は問題を解決したり目標を達成したりするための公共の計画です。', 'A policy is a public plan for solving problems or reaching goals.', '정책'),
  choice(4, 'grammar', '는 대신에', '〜する代わりに', 'Instead of', '온라인으로 신청하___ 대신에 창구에서 기다릴 필요가 없습니다.', 'オンラインで申し込___代わりに窓口で待つ必要がありません。', 'Instead of applying online, you do not need to wait at the counter.', ['는', '아서', '려고', '지만'], 0, '한 방법을 선택하는 대신 다른 결과가 있음을 말할 때 는 대신에를 씁니다.', '一つの方法を選ぶ代わりに別の結果があることを言うとき「는 대신에」を使います。', 'Use 는 대신에 for an alternative and its result.', '온라인으로 신청하는 대신에 창구에서 기다릴 필요가 없습니다.'),
  choice(4, 'reading', '주민 설명회', '住民説明会', 'Residents’ briefing', '지문: 새 공원 계획 설명회는 금요일 저녁 일곱 시에 주민센터에서 열립니다. 의견은 설명회 뒤 일주일 동안 온라인으로 낼 수 있습니다.\n질문: 의견은 언제까지 낼 수 있습니까?', '本文：新しい公園計画の説明会は金曜日午後七時に住民センターで開かれます。意見は説明会後一週間オンラインで出せます。\n質問：意見はいつまで出せますか。', 'Text: Until when can opinions be submitted?', ['설명회 뒤 일주일 동안', '금요일 저녁까지', '오늘 오전까지', '다음 달까지'], 0, '설명회가 끝난 뒤 일주일 동안 의견을 낼 수 있습니다.', '説明会が終わった後一週間意見を出せます。', 'Opinions can be submitted for one week after the briefing.', '의견은 설명회 뒤 일주일 동안 온라인으로 낼 수 있습니다.'),
  choice(4, 'listening', '행사 조정', '行事の調整', 'Event coordination', '행사 시작 시간이 바뀐 이유는 무엇입니까?', '行事の開始時間が変わった理由は何ですか。', 'Why did the event start time change?', ['참가자의 퇴근 시간을 고려해서', '비가 많이 와서', '장소가 닫혀서', '표가 부족해서'], 0, '참가자들이 퇴근한 뒤 올 수 있도록 시간을 늦춥니다.', '参加者が退勤後に来られるよう時間を遅らせます。', 'The time moves later so participants can come after work.', '참가자들의 퇴근 시간을 고려해서 시작을 한 시간 늦추겠습니다.'),
  writing(4, '제안 이메일', '提案メール', 'Proposal email', '지역 행사에 대한 제안을 이메일 형식의 두 문장으로 써 보세요.', '地域行事への提案をメール形式の二文で書いてみましょう。', 'Write a two-sentence email proposal about a local event.', '안녕하세요. 설명회 자료를 미리 올려 주시면 더 많은 주민이 의견을 낼 수 있을 것 같습니다.', 'こんにちは。説明会の資料を前もって掲載していただければ、より多くの住民が意見を出せると思います。', 'Hello. If the briefing materials are posted in advance, more residents may be able to share their views.'),

  choice(5, 'vocab', '디지털 접근성', 'デジタル・アクセシビリティ', 'Digital accessibility', '나이, 장애, 기기와 관계없이 서비스를 이용할 수 있게 하는 성질은 무엇입니까?', '年齢・障害・機器に関係なくサービスを利用できるようにする性質は何ですか。', 'What property lets people use a service regardless of age, disability, or device?', ['접근성', '속도', '계절', '표정'], 0, '접근성은 다양한 사람이 서비스에 접근하고 이용할 수 있는 정도입니다.', 'アクセシビリティは多様な人がサービスにアクセスし利用できる程度です。', 'Accessibility is the degree to which diverse people can access and use a service.', '접근성'),
  choice(5, 'grammar', '을 뿐만 아니라', '〜するだけでなく', 'Not only … but also', '이 안내는 글자가 클 뿐만 아니라 음성으로도 들을 수 있___ .', 'この案内は文字が大きいだけでなく音声でも聞くことができ___。', 'This guide has large text and can also be heard as audio.', ['습니다', '려고', '지만', '세요'], 0, '앞의 사실에 더하여 다른 사실도 있음을 말할 때 을 뿐만 아니라를 씁니다.', '前の事実に加えて別の事実もあることを言うとき「을 뿐만 아니라」を使います。', 'Use 을 뿐만 아니라 to add another fact.', '이 안내는 글자가 클 뿐만 아니라 음성으로도 들을 수 있습니다.'),
  choice(5, 'reading', '이용자 조사', '利用者調査', 'User survey', '지문: 시청은 온라인 신청 서비스의 이용자 조사를 했다. 응답자들은 처리 속도에는 만족했지만, 처음 이용하는 사람을 위한 설명이 부족하다고 답했다. 시청은 다음 달에 쉬운 안내 화면을 추가할 예정이다.\n질문: 시청이 추가하려는 것은 무엇입니까?', '本文：市役所はオンライン申請サービスの利用者調査を行いました。回答者は処理速度には満足したが、初めて使う人向けの説明が足りないと答えました。市役所は来月やさしい案内画面を追加する予定です。\n質問：市役所が追加しようとしているものは何ですか。', 'Text: What does the city plan to add?', ['쉬운 안내 화면', '새로운 버스 노선', '처리 수수료', '회의 시간'], 0, '처음 이용하는 사람을 위한 쉬운 안내 화면을 추가할 예정입니다.', '初めて使う人のためのやさしい案内画面を追加する予定です。', 'The city plans to add an easy guidance screen for first-time users.', '처음 이용하는 사람을 위한 쉬운 안내 화면을 다음 달에 추가할 예정입니다.'),
  choice(5, 'listening', '토론 요약', '討論の要約', 'Discussion summary', '발표자는 다음 단계로 무엇을 하자고 말합니까?', '発表者は次の段階として何をしようと言っていますか。', 'What does the speaker propose as the next step?', ['다양한 이용자에게 시험해 보기', '서비스를 바로 없애기', '설문을 숨기기', '회의를 중단하기'], 0, '서로 다른 이용 환경의 사람들에게 안내 화면을 시험해 보자고 합니다.', '異なる利用環境の人々に案内画面を試してみようと言っています。', 'The speaker proposes testing the screen with people in different situations.', '속도만 볼 뿐만 아니라, 다양한 이용자에게 새 안내 화면을 시험해 봅시다.'),
  writing(5, '근거 있는 의견', '根拠のある意見', 'Evidence-based opinion', '디지털 서비스 개선안에 대해 근거를 포함한 두 문장을 써 보세요.', 'デジタルサービス改善案について根拠を含む二文を書いてみましょう。', 'Write two evidence-based sentences about improving a digital service.', '처리 속도는 좋지만 처음 이용하는 사람은 안내를 어려워합니다. 쉬운 설명과 음성 안내를 함께 제공해야 합니다.', '処理速度は良いですが、初めて使う人は案内を難しく感じます。やさしい説明と音声案内を一緒に提供すべきです。', 'Processing is fast, but first-time users find the guidance difficult. Clear explanations and audio guidance should be provided together.'),

  choice(6, 'vocab', '자료 해석', '資料の解釈', 'Interpreting data', '여러 수치와 기록이 무엇을 뜻하는지 근거와 맥락에 따라 판단하는 일을 무엇이라고 합니까?', '複数の数値や記録が何を意味するかを根拠と文脈に沿って判断することを何といいますか。', 'What do you call judging what figures and records mean based on evidence and context?', ['자료 해석', '관광 안내', '운동 계획', '계절 변화'], 0, '자료 해석은 수치와 기록의 의미를 근거와 맥락에 따라 살피는 일입니다.', '資料の解釈は数値や記録の意味を根拠と文脈に沿って考えることです。', 'Data interpretation examines the meaning of figures and records using evidence and context.', '자료 해석'),
  choice(6, 'grammar', '에 비추어', '〜に照らして', 'In light of', '조사 결과의 한계___ 결론의 범위를 정해야 합니다.', '調査結果の限界___結論の範囲を決めるべきです。', 'The scope of a conclusion should be set in light of a survey’s limitations.', ['에 비추어', '고 싶어서', '는 동안', '기 전에'], 0, '기준이나 사실을 바탕으로 판단할 때 에 비추어를 씁니다.', '基準や事実をもとに判断するとき「에 비추어」を使います。', 'Use 에 비추어 when judging based on a standard or fact.', '조사 결과의 한계에 비추어 결론의 범위를 정해야 합니다.'),
  choice(6, 'reading', '조사 결과 해석', '調査結果の解釈', 'Interpreting survey results', '지문: 한 조사에서 특정 지역의 만족도가 낮게 나타났다. 그러나 응답자가 적고 조사가 한 달 동안만 이루어졌기 때문에, 결과를 모든 주민의 의견으로 일반화하기는 어렵다. 연구팀은 다음 조사에서 표본을 넓히고 계절별 차이도 확인하기로 했다.\n질문: 연구팀이 다음 조사에서 하기로 한 일은 무엇입니까?', '本文：ある調査で特定地域の満足度が低く出ました。しかし回答者が少なく調査が一か月だけだったため、結果をすべての住民の意見に一般化するのは難しいです。研究チームは次の調査で標本を広げ季節別の違いも確認することにしました。\n質問：研究チームは次の調査で何をすることにしましたか。', 'Text: What will the research team do next?', ['표본을 넓히고 계절 차이를 확인한다', '결과를 즉시 일반화한다', '조사를 중단한다', '응답을 삭제한다'], 0, '응답자 수와 조사 기간의 한계를 보완하기 위해 표본과 계절 차이를 확인합니다.', '回答者数と調査期間の限界を補うため標本と季節差を確認します。', 'They will expand the sample and check seasonal differences.', '다음 조사에서는 표본을 넓히고 계절별 차이도 확인하기로 했습니다.'),
  choice(6, 'listening', '공청회 발언', '公聴会での発言', 'Public-hearing statement', '발언자는 정책을 평가할 때 무엇이 필요하다고 말합니까?', '発言者は政策を評価するとき何が必要だと言っていますか。', 'What does the speaker say is needed to evaluate a policy?', ['수치와 이용자 경험을 함께 보기', '수치만 보기', '의견을 숨기기', '평가를 미루기'], 0, '수치뿐 아니라 실제 이용자의 경험도 함께 보아야 한다고 합니다.', '数値だけでなく実際の利用者の経験も一緒に見るべきだと言っています。', 'The speaker says to consider users’ lived experience alongside numbers.', '정책의 효과는 수치에 비추어 보되, 실제 이용자의 경험도 함께 살펴야 합니다.'),
  writing(6, '비판적 논평', '批判的コメント', 'Critical commentary', '한 조사 결과의 장점과 한계를 각각 한 문장으로 써 보세요.', 'ある調査結果の長所と限界をそれぞれ一文で書いてみましょう。', 'Write one sentence each about a survey result’s strength and limitation.', '이 조사는 이용자의 불편을 구체적으로 보여 준다는 장점이 있습니다. 다만 응답자가 적어서 모든 사람의 의견으로 일반화하기는 어렵습니다.', 'この調査は利用者の不便を具体的に示す長所があります。ただし回答者が少ないため、すべての人の意見として一般化するのは難しいです。', 'This survey clearly shows user difficulties, but its small respondent group makes broad generalisation difficult.'),
];

export interface TopikOwnerBatch4Manifest { sourceCode: string; sourceAssetId: string; sourcePath: string; sourceSha256: string; counts: { units: number; items: number; stableRefs: number; audioBindings: number; contentRows: number }; }
function slug(item: Pick<ItemSeed, 'grade' | 'section'>): string { return `${item.grade}-${item.section}`; }
function unitId(item: ItemSeed): string { return `topik-owner-batch4-unit-${slug(item)}`; }
function itemId(item: ItemSeed): string { return `topik-owner-batch4-item-${slug(item)}`; }
function stableRef(item: ItemSeed): string { return `topik:owner:batch4:grade${item.grade}:${item.section}`; }
function answerJson(item: ItemSeed): string { return JSON.stringify(item.choices ? { choices: item.choices, answer_index: item.answerIndex } : { sample_answer_ko: item.explanationKo.replace(/^예: /, '') }); }
function unitStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `topik_owner_authored_curriculum_units`', '  (`id`, `target_grade`, `stable_ref`, `section`, `title_ko`, `title_ja`, `title_en`, `source_asset_id`)', `VALUES (${esc(unitId(item))}, ${item.grade}, ${esc(`topik:owner:batch4:grade${item.grade}:unit:${item.section}`)}, ${esc(item.section)}, ${esc(item.titleKo)}, ${esc(item.titleJa)}, ${esc(item.titleEn)}, ${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)});`].join('\n'); }
function itemStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `topik_owner_authored_curriculum_items`', '  (`id`, `unit_id`, `target_grade`, `stable_ref`, `item_type`, `prompt_ko`, `prompt_ja`, `prompt_en`, `answer_json`, `explanation_ko`, `explanation_ja`, `explanation_en`, `audio_required`, `audio_text_ko`, `source_asset_id`)', `VALUES (${esc(itemId(item))}, ${esc(unitId(item))}, ${item.grade}, ${esc(stableRef(item))}, ${esc(item.section)}, ${esc(item.promptKo)}, ${esc(item.promptJa)}, ${esc(item.promptEn)}, ${esc(answerJson(item))}, ${esc(item.explanationKo)}, ${esc(item.explanationJa)}, ${esc(item.explanationEn)}, 1, ${esc(item.audioTextKo)}, ${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)});`].join('\n'); }
function stableRefStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `learning_content_stable_refs`', '  (`stable_ref`, `learning_track`, `item_type`, `item_id`, `level_tag`, `source_asset_id`)', `VALUES (${esc(stableRef(item))}, 'topik-ko', 'topik-owner-item', ${esc(itemId(item))}, ${esc(`TOPIK-${item.grade}`)}, ${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)});`].join('\n'); }
function audioBindingStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `content_speech_bindings`', '  (`id`, `stable_ref`, `item_type`, `item_id`, `language`, `speech_role`, `provider`, `binding_state`, `text_source`, `unavailable_reason`)', `VALUES (${esc(`speech-binding:${stableRef(item)}`)}, ${esc(stableRef(item))}, 'topik-owner-item', ${esc(itemId(item))}, 'ko', ${esc(item.section === 'listening' ? 'listening' : 'pronunciation')}, 'google-browser', 'ready', 'audio-script', NULL);`].join('\n'); }

export function topikOwnerBatch4ContentRowsSql(): string { return `SELECT (SELECT count(*) FROM topik_owner_authored_curriculum_units WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)}) + (SELECT count(*) FROM topik_owner_authored_curriculum_items WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)}) AS count;`; }
export function buildTopikOwnerBatch4Plan() {
  const sourceSha256 = createHash('sha256').update(fs.readFileSync(TOPIK_OWNER_BATCH_4_PATH)).digest('hex');
  const statements = [
    ['INSERT INTO `sources` (`code`, `title`, `file_path`, `version`)', `VALUES (${esc(TOPIK_OWNER_BATCH_4_SOURCE_CODE)}, 'TOPIK 1~6급 자체 저작 Batch 4', 'docs/07_topik/05_owner_authored_grades_1_6_batch_4.md', ${esc(`source-v3-${sourceSha256.slice(0, 16)}`)})`, 'ON CONFLICT(`code`) DO UPDATE SET `title` = excluded.`title`, `file_path` = excluded.`file_path`, `version` = excluded.`version`, `updated_at` = unixepoch();'].join('\n'),
    ['INSERT OR IGNORE INTO `content_source_assets`', '  (`id`, `asset_kind`, `source_url`, `license_id`, `license_url`, `attribution_text`, `allowed_use`, `source_sha256`, `generated_at`, `selection_reason`)', `VALUES (${esc(TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID)}, 'self-authored-fixture', ${esc(REPOSITORY_URL)}, 'LicenseRef-nihongo-n3-self-authored', ${esc(LICENSE_URL)},`, "  '© Nihongo N3 contributors; self-authored TOPIK learning content.',", "  'Personal learning content; self-authored Korean prompts, scripts, questions, answers, and explanations; not official TOPIK material.',", `  ${esc(sourceSha256)}, 1786233600, 'Fourth operating TOPIK 1–6 self-authored curriculum batch with Google browser speech only; R2 pronunciation storage and fallback are disabled.');`].join('\n'),
    ...ITEMS.map(unitStatement), ...ITEMS.map(itemStatement), ...ITEMS.map(stableRefStatement), ...ITEMS.map(audioBindingStatement),
  ];
  const counts = { units: ITEMS.length, items: ITEMS.length, stableRefs: ITEMS.length, audioBindings: ITEMS.length, contentRows: ITEMS.length * 2 } as const;
  return { statements, manifest: { sourceCode: TOPIK_OWNER_BATCH_4_SOURCE_CODE, sourceAssetId: TOPIK_OWNER_BATCH_4_SOURCE_ASSET_ID, sourcePath: path.relative(REPO_ROOT, TOPIK_OWNER_BATCH_4_PATH).split(path.sep).join('/'), sourceSha256, counts } satisfies TopikOwnerBatch4Manifest };
}
