import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { REPO_ROOT } from './constants.js';
import { esc } from './utils.js';

export const TOPIK_OWNER_BATCH_2_SOURCE_CODE = 'TOPIK-A2';
export const TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID = 'source-asset:topik-owner-authored-grades-1-6-batch-2-2026-07-30';
export const TOPIK_OWNER_BATCH_2_PATH = path.join(REPO_ROOT, 'docs/07_topik/03_owner_authored_grades_1_6_batch_2.md');
const REPOSITORY_URL = 'https://github.com/kordokrip/JLPT/blob/main/docs/07_topik/03_owner_authored_grades_1_6_batch_2.md';
const LICENSE_URL = 'https://github.com/kordokrip/JLPT/blob/main/docs/ATTRIBUTIONS.md#학습-콘텐츠와-provenance';
const AUDIO_PREPARING_REASON = 'A durable R2 recording has not been generated yet; this self-authored Korean text is available through the browser Korean voice.';

type Section = 'vocab' | 'grammar' | 'reading' | 'listening' | 'writing';
interface ItemSeed { grade: number; section: Section; titleKo: string; titleJa: string; titleEn: string; promptKo: string; promptJa: string; promptEn: string; choices?: readonly string[]; answerIndex?: number; explanationKo: string; explanationJa: string; explanationEn: string; audioTextKo: string; }

const ITEMS: readonly ItemSeed[] = [
  { grade: 1, section: 'vocab', titleKo: '가족', titleJa: '家族', titleEn: 'Family', promptKo: '아버지와 어머니를 함께 부르는 말은 무엇입니까?', promptJa: '父と母を一緒に呼ぶ言葉は何ですか。', promptEn: 'What word refers to father and mother together?', choices: ['부모님', '친구', '선생님', '학생'], answerIndex: 0, explanationKo: '부모님은 아버지와 어머니를 높여 함께 부르는 말입니다.', explanationJa: '「부모님」は父と母を敬って一緒に呼ぶ言葉です。', explanationEn: '부모님 is a respectful word for one’s parents.', audioTextKo: '부모님' },
  { grade: 1, section: 'grammar', titleKo: '에 있어요', titleJa: '〜にあります', titleEn: 'Located at', promptKo: '책은 책상 위___ .', promptJa: '本は机の上___。', promptEn: 'The book is on the desk.', choices: ['에 있어요', '을 좋아해요', '와 가요', '부터예요'], answerIndex: 0, explanationKo: '사람이나 물건이 있는 장소를 말할 때 에 있어요를 씁니다.', explanationJa: '人や物がある場所を言うときに「에 있어요」を使います。', explanationEn: 'Use 에 있어요 to say where a person or thing is located.', audioTextKo: '책은 책상 위에 있어요.' },
  { grade: 1, section: 'reading', titleKo: '가게 시간', titleJa: '店の営業時間', titleEn: 'Shop hours', promptKo: '지문: 이 가게는 오전 열 시에 문을 열고 오후 일곱 시에 닫습니다. 일요일에는 쉽니다.\n질문: 가게는 언제 쉽니까?', promptJa: '本文：この店は午前十時に開き、午後七時に閉まります。日曜日は休みです。\n質問：店はいつ休みですか。', promptEn: 'Text: This shop opens at 10 a.m. and closes at 7 p.m. It is closed on Sunday. When is the shop closed?', choices: ['일요일', '월요일', '오전 열 시', '오후 일곱 시'], answerIndex: 0, explanationKo: '지문에 일요일에는 쉰다고 나옵니다.', explanationJa: '本文に日曜日は休みだとあります。', explanationEn: 'The text says the shop is closed on Sunday.', audioTextKo: '이 가게는 오전 열 시에 문을 열고 오후 일곱 시에 닫습니다. 일요일에는 쉽니다.' },
  { grade: 1, section: 'listening', titleKo: '카페 주문 듣기', titleJa: 'カフェでの注文を聞く', titleEn: 'Listening to a cafe order', promptKo: '손님은 무엇을 주문합니까?', promptJa: '客は何を注文しますか。', promptEn: 'What does the customer order?', choices: ['따뜻한 커피', '차가운 물', '비빔밥', '버스표'], answerIndex: 0, explanationKo: '손님이 따뜻한 커피 한 잔을 달라고 말합니다.', explanationJa: '客は温かいコーヒーを一杯くださいと言っています。', explanationEn: 'The customer asks for one hot coffee.', audioTextKo: '안녕하세요. 따뜻한 커피 한 잔 주세요.' },
  { grade: 1, section: 'writing', titleKo: '오늘 일정', titleJa: '今日の予定', titleEn: 'Today’s schedule', promptKo: '오늘 할 일을 한 문장으로 써 보세요.', promptJa: '今日することを一文で書いてください。', promptEn: 'Write one sentence about what you will do today.', explanationKo: '예: 오늘 오후에 도서관에 가요.', explanationJa: '例：今日の午後、図書館に行きます。', explanationEn: 'Example: 오늘 오후에 도서관에 가요.', audioTextKo: '오늘 오후에 도서관에 가요.' },

  { grade: 2, section: 'vocab', titleKo: '날씨와 계획', titleJa: '天気と予定', titleEn: 'Weather and plans', promptKo: '비가 오지 않고 하늘이 맑은 날씨는 무엇입니까?', promptJa: '雨が降らず空が晴れている天気は何ですか。', promptEn: 'What weather is clear with no rain?', choices: ['맑음', '눈', '바람', '구름'], answerIndex: 0, explanationKo: '맑음은 구름이나 비가 거의 없이 하늘이 깨끗한 상태입니다.', explanationJa: '「맑음」は雲や雨がほとんどなく空が澄んだ状態です。', explanationEn: '맑음 means clear weather with little cloud or rain.', audioTextKo: '맑음' },
  { grade: 2, section: 'grammar', titleKo: '았어요와 었어요', titleJa: '過去形', titleEn: 'Past tense', promptKo: '어제 친구를 만나___ .', promptJa: '昨日友達に会い___。', promptEn: 'I met a friend yesterday.', choices: ['았어요', '고 싶어요', '에서', '지만'], answerIndex: 0, explanationKo: '만나다는 과거에 만났어요로 바꿉니다.', explanationJa: '「만나다」は過去形で「만났어요」になります。', explanationEn: 'The past form of 만나다 is 만났어요.', audioTextKo: '어제 친구를 만났어요.' },
  { grade: 2, section: 'reading', titleKo: '초대 메시지', titleJa: '招待メッセージ', titleEn: 'Invitation message', promptKo: '지문: 토요일 오후 다섯 시에 우리 집에서 생일 파티를 해요. 시간이 되면 꼭 오세요.\n질문: 파티는 어디에서 합니까?', promptJa: '本文：土曜日の午後五時に私の家で誕生日パーティーをします。時間があればぜひ来てください。\n質問：パーティーはどこでしますか。', promptEn: 'Text: I am having a birthday party at my house at 5 p.m. Saturday. Please come if you can. Where is the party?', choices: ['우리 집', '학교', '공원', '역 앞'], answerIndex: 0, explanationKo: '파티를 우리 집에서 한다고 했습니다.', explanationJa: 'パーティーは私の家ですると書かれています。', explanationEn: 'The message says the party is at the speaker’s home.', audioTextKo: '토요일 오후 다섯 시에 우리 집에서 생일 파티를 해요. 시간이 되면 꼭 오세요.' },
  { grade: 2, section: 'listening', titleKo: '버스 안내 듣기', titleJa: 'バス案内を聞く', titleEn: 'Listening to a bus announcement', promptKo: '안내에 따르면 버스는 어디에 섭니까?', promptJa: '案内によると、バスはどこに停まりますか。', promptEn: 'According to the announcement, where does the bus stop?', choices: ['시청 앞', '병원 안', '학교 교실', '카페 안'], answerIndex: 0, explanationKo: '다음 정류장이 시청 앞이라고 안내합니다.', explanationJa: '次の停留所は市庁前だと案内しています。', explanationEn: 'The announcement says the next stop is in front of city hall.', audioTextKo: '다음 정류장은 시청 앞입니다. 내리실 분은 미리 준비해 주세요.' },
  { grade: 2, section: 'writing', titleKo: '주말 기록', titleJa: '週末の記録', titleEn: 'Weekend note', promptKo: '지난 주말에 한 일을 두 문장으로 써 보세요.', promptJa: '先週末にしたことを二文で書いてください。', promptEn: 'Write two sentences about what you did last weekend.', explanationKo: '예: 토요일에 영화를 봤어요. 일요일에는 집에서 쉬었어요.', explanationJa: '例：土曜日に映画を見ました。日曜日は家で休みました。', explanationEn: 'Example: 토요일에 영화를 봤어요. 일요일에는 집에서 쉬었어요.', audioTextKo: '토요일에 영화를 봤어요. 일요일에는 집에서 쉬었어요.' },

  { grade: 3, section: 'vocab', titleKo: '신청과 문의', titleJa: '申請と問い合わせ', titleEn: 'Applications and inquiries', promptKo: '필요한 정보를 물어보거나 도움을 요청하는 것은 무엇입니까?', promptJa: '必要な情報を尋ねたり助けを求めたりすることは何ですか。', promptEn: 'What is asking for necessary information or help?', choices: ['문의', '취소', '출발', '발표'], answerIndex: 0, explanationKo: '문의는 궁금한 점을 물어보는 일입니다.', explanationJa: '「문의」は知りたいことを尋ねることです。', explanationEn: '문의 means making an inquiry about something.', audioTextKo: '문의' },
  { grade: 3, section: 'grammar', titleKo: '는데', titleJa: '〜ですが／ので', titleEn: '는데', promptKo: '제가 처음이라서 길을 잘 모르___ 도와주실 수 있어요?', promptJa: '私は初めてで道をよく分からない___、手伝っていただけますか。', promptEn: 'It is my first time and I do not know the way well. Could you help me?', choices: ['는데', '까지', '거나', '부터'], answerIndex: 0, explanationKo: '는데는 배경을 말한 뒤 부탁이나 다음 내용을 이어 갈 때 쓸 수 있습니다.', explanationJa: '「는데」は背景を述べた後、依頼や次の内容につなげられます。', explanationEn: 'Use 는데 to give context before a request or the next statement.', audioTextKo: '제가 처음이라서 길을 잘 모르는데 도와주실 수 있어요?' },
  { grade: 3, section: 'reading', titleKo: '시설 이용 안내', titleJa: '施設利用の案内', titleEn: 'Facility-use notice', promptKo: '지문: 체육관은 안전 점검 때문에 금요일 저녁에는 사용할 수 없습니다. 토요일 오전부터 정상적으로 이용할 수 있습니다.\n질문: 체육관은 언제부터 이용할 수 있습니까?', promptJa: '本文：体育館は安全点検のため金曜日の夕方は利用できません。土曜日の午前から通常どおり利用できます。\n質問：体育館はいつから利用できますか。', promptEn: 'Text: The gym cannot be used Friday evening due to a safety inspection. It may be used normally from Saturday morning. From when can it be used?', choices: ['토요일 오전부터', '금요일 저녁부터', '목요일 오전부터', '일요일 밤부터'], answerIndex: 0, explanationKo: '토요일 오전부터 정상적으로 이용할 수 있다고 했습니다.', explanationJa: '土曜日の午前から通常どおり利用できるとあります。', explanationEn: 'The notice says it can be used normally from Saturday morning.', audioTextKo: '체육관은 안전 점검 때문에 금요일 저녁에는 사용할 수 없습니다. 토요일 오전부터 정상적으로 이용할 수 있습니다.' },
  { grade: 3, section: 'listening', titleKo: '회사 일정 듣기', titleJa: '会社の予定を聞く', titleEn: 'Listening to a work schedule', promptKo: '회의는 왜 다음 주로 미루어졌습니까?', promptJa: '会議はなぜ来週に延期されましたか。', promptEn: 'Why was the meeting postponed until next week?', choices: ['담당자가 출장을 가서', '회의실이 커서', '점심 시간이어서', '비가 오지 않아서'], answerIndex: 0, explanationKo: '담당자가 이번 주에 출장이라 다음 주로 미룬다고 말합니다.', explanationJa: '担当者が今週は出張のため、来週に延ばすと言っています。', explanationEn: 'The person in charge is on a business trip this week, so it is postponed.', audioTextKo: '담당자님이 이번 주에 출장을 가세요. 그래서 회의는 다음 주 화요일로 미루겠습니다.' },
  { grade: 3, section: 'writing', titleKo: '정중한 이메일', titleJa: '丁寧なメール', titleEn: 'Polite email', promptKo: '답장이 늦어진 것을 사과하는 짧은 이메일을 써 보세요.', promptJa: '返信が遅れたことを謝る短いメールを書いてください。', promptEn: 'Write a short email apologizing for a late reply.', explanationKo: '예: 답장이 늦어서 죄송합니다. 문의하신 내용은 내일까지 확인해서 알려 드리겠습니다.', explanationJa: '例：返信が遅くなり申し訳ありません。お問い合わせの内容は明日までに確認してお知らせします。', explanationEn: 'Example: 답장이 늦어서 죄송합니다. 문의하신 내용은 내일까지 확인해서 알려 드리겠습니다.', audioTextKo: '답장이 늦어서 죄송합니다. 문의하신 내용은 내일까지 확인해서 알려 드리겠습니다.' },

  { grade: 4, section: 'vocab', titleKo: '환경과 분리배출', titleJa: '環境と分別排出', titleEn: 'Environment and sorting waste', promptKo: '쓰레기를 종류에 따라 나누어 버리는 것은 무엇입니까?', promptJa: 'ごみを種類ごとに分けて捨てることは何ですか。', promptEn: 'What is separating waste by type before disposal?', choices: ['분리배출', '재출발', '예약', '접수'], answerIndex: 0, explanationKo: '분리배출은 재활용 등을 위해 쓰레기를 종류별로 나누어 버리는 일입니다.', explanationJa: '「분리배출」はリサイクルなどのため、ごみを種類別に分けて捨てることです。', explanationEn: '분리배출 is separating waste by type for recycling and disposal.', audioTextKo: '분리배출' },
  { grade: 4, section: 'grammar', titleKo: '도록', titleJa: '〜するように', titleEn: 'So that', promptKo: '모두가 볼 수 있___ 안내문을 입구에 붙였습니다.', promptJa: '誰もが見られる___案内文を入口に貼りました。', promptEn: 'The notice was posted at the entrance so everyone could see it.', choices: ['도록', '는 대신', '더니', '마저'], answerIndex: 0, explanationKo: '목적이나 결과를 나타낼 때 도록을 씁니다.', explanationJa: '目的や結果を表すときに「도록」を使います。', explanationEn: 'Use 도록 to express a purpose or intended result.', audioTextKo: '모두가 볼 수 있도록 안내문을 입구에 붙였습니다.' },
  { grade: 4, section: 'reading', titleKo: '재활용 공지', titleJa: 'リサイクルのお知らせ', titleEn: 'Recycling notice', promptKo: '지문: 다음 달부터 플라스틱은 깨끗이 씻은 뒤 투명 봉투에 넣어 배출해 주세요. 음식물이 묻어 있으면 재활용할 수 없습니다.\n질문: 재활용할 수 없는 경우는 언제입니까?', promptJa: '本文：来月からプラスチックはきれいに洗ってから透明な袋に入れて出してください。食べ物が付いているとリサイクルできません。\n質問：リサイクルできないのはいつですか。', promptEn: 'Text: Starting next month, wash plastic and put it in a transparent bag. It cannot be recycled if food is stuck to it. When can it not be recycled?', choices: ['음식물이 묻어 있을 때', '깨끗이 씻었을 때', '봉투에 넣었을 때', '다음 달일 때'], answerIndex: 0, explanationKo: '음식물이 묻어 있으면 재활용할 수 없다고 안내합니다.', explanationJa: '食べ物が付いているとリサイクルできないと案内しています。', explanationEn: 'The notice says plastic cannot be recycled if food remains on it.', audioTextKo: '다음 달부터 플라스틱은 깨끗이 씻은 뒤 투명 봉투에 넣어 배출해 주세요. 음식물이 묻어 있으면 재활용할 수 없습니다.' },
  { grade: 4, section: 'listening', titleKo: '기차 안내 듣기', titleJa: '列車案内を聞く', titleEn: 'Listening to a train announcement', promptKo: '승객은 왜 다른 승강장으로 가야 합니까?', promptJa: '乗客はなぜ別のホームへ行く必要がありますか。', promptEn: 'Why must passengers go to another platform?', choices: ['기차가 다른 승강장에서 출발해서', '표를 잃어버려서', '비가 와서', '음식을 사야 해서'], answerIndex: 0, explanationKo: '열차가 삼 번 승강장에서 출발한다고 안내합니다.', explanationJa: '列車は三番ホームから出発すると案内しています。', explanationEn: 'The announcement says the train departs from platform three.', audioTextKo: '부산행 열차는 이 번 승강장이 아니라 삼 번 승강장에서 출발합니다. 승객 여러분께서는 이동해 주세요.' },
  { grade: 4, section: 'writing', titleKo: '제안서 문장', titleJa: '提案書の文', titleEn: 'Proposal sentence', promptKo: '공공장소를 더 편리하게 만드는 제안을 두 문장으로 써 보세요.', promptJa: '公共の場所をより便利にする提案を二文で書いてください。', promptEn: 'Write two sentences proposing how to make a public place more convenient.', explanationKo: '예: 안내 표지판을 더 크게 만들어야 합니다. 처음 방문하는 사람도 길을 쉽게 찾을 수 있기 때문입니다.', explanationJa: '例：案内標識をもっと大きくするべきです。初めて訪れる人も道を簡単に見つけられるからです。', explanationEn: 'Example: 안내 표지판을 더 크게 만들어야 합니다. 처음 방문하는 사람도 길을 쉽게 찾을 수 있기 때문입니다.', audioTextKo: '안내 표지판을 더 크게 만들어야 합니다. 처음 방문하는 사람도 길을 쉽게 찾을 수 있기 때문입니다.' },

  { grade: 5, section: 'vocab', titleKo: '비교와 평가', titleJa: '比較と評価', titleEn: 'Comparison and evaluation', promptKo: '두 대상의 공통점과 차이점을 살펴보는 것은 무엇입니까?', promptJa: '二つの対象の共通点と違いを調べることは何ですか。', promptEn: 'What is examining similarities and differences between two subjects?', choices: ['비교', '반복', '소개', '예측'], answerIndex: 0, explanationKo: '비교는 둘 이상의 대상이 어떻게 같은지 다른지 살피는 일입니다.', explanationJa: '「비교」は二つ以上の対象がどのように同じか違うか調べることです。', explanationEn: '비교 is comparing two or more things for similarities and differences.', audioTextKo: '비교' },
  { grade: 5, section: 'grammar', titleKo: '기는 하지만', titleJa: '〜ではあるが', titleEn: 'Although', promptKo: '이 방법은 비용이 적게 들___ 시간이 오래 걸립니다.', promptJa: 'この方法は費用が少なくかかる___時間がかかります。', promptEn: 'Although this method costs little, it takes a long time.', choices: ['기는 하지만', '더라도', '도록', '기에'], answerIndex: 0, explanationKo: '앞의 사실을 인정하면서 뒤에 대조되는 내용을 말할 때 기는 하지만을 씁니다.', explanationJa: '前の事実を認めながら後に対照的な内容を述べるときに「기는 하지만」を使います。', explanationEn: 'Use 기는 하지만 to acknowledge one fact before adding a contrast.', audioTextKo: '이 방법은 비용이 적게 들기는 하지만 시간이 오래 걸립니다.' },
  { grade: 5, section: 'reading', titleKo: '지역 행사 평가', titleJa: '地域行事の評価', titleEn: 'Evaluating a local event', promptKo: '지문: 올해 행사는 참가자 수가 늘어 성공적이라는 평가를 받았다. 그러나 안내가 충분하지 않아 처음 온 사람들은 프로그램을 찾기 어려웠다. 다음 행사에서는 참여 인원뿐 아니라 이용 경험도 함께 평가할 필요가 있다.\n질문: 글쓴이가 다음 행사에서 함께 평가해야 한다고 한 것은 무엇입니까?', promptJa: '本文：今年の行事は参加者数が増え成功したと評価された。しかし案内が十分でなく、初めて来た人はプログラムを見つけにくかった。次の行事では参加人数だけでなく利用経験も一緒に評価する必要がある。\n質問：筆者が次の行事で一緒に評価すべきだと述べたものは何ですか。', promptEn: 'Text: This year’s event was considered successful because attendance grew. However, first-time visitors had difficulty finding programs due to insufficient guidance. What should also be evaluated next time?', choices: ['이용 경험', '날씨만', '행사 이름만', '참가비만'], answerIndex: 0, explanationKo: '참여 인원뿐 아니라 이용 경험도 평가해야 한다고 했습니다.', explanationJa: '参加人数だけでなく利用経験も評価すべきだと述べています。', explanationEn: 'The writer says user experience should be evaluated along with attendance.', audioTextKo: '올해 행사는 참가자 수가 늘어 성공적이라는 평가를 받았다. 그러나 안내가 충분하지 않아 처음 온 사람들은 프로그램을 찾기 어려웠다.' },
  { grade: 5, section: 'listening', titleKo: '회의 보고 듣기', titleJa: '会議報告を聞く', titleEn: 'Listening to a meeting report', promptKo: '화자는 다음 단계로 무엇을 하자고 말합니까?', promptJa: '話者は次の段階として何をしようと言っていますか。', promptEn: 'What does the speaker say to do next?', choices: ['참가자 의견을 더 수집한다', '결과를 숨긴다', '회의를 취소한다', '자료를 버린다'], answerIndex: 0, explanationKo: '현재 결과를 바탕으로 참가자 의견을 더 모으자고 제안합니다.', explanationJa: '現在の結果をもとに参加者の意見をさらに集めようと提案しています。', explanationEn: 'The speaker proposes gathering more participant feedback based on the current results.', audioTextKo: '현재 결과만으로 결론을 내리기보다는 참가자 의견을 조금 더 수집한 뒤에 개선안을 정하는 것이 좋겠습니다.' },
  { grade: 5, section: 'writing', titleKo: '근거 있는 의견', titleJa: '根拠のある意見', titleEn: 'Evidence-based opinion', promptKo: '한 가지 불편을 고르고 근거를 들어 개선 의견을 두 문장으로 써 보세요.', promptJa: '一つの不便を選び、根拠を添えて改善意見を二文で書いてください。', promptEn: 'Choose one inconvenience and write a two-sentence improvement opinion with a reason.', explanationKo: '예: 버스 도착 정보를 더 자주 알려야 합니다. 기다리는 시간이 길어도 계획을 세우기 쉬워지기 때문입니다.', explanationJa: '例：バス到着情報をもっと頻繁に知らせるべきです。待ち時間が長くても予定を立てやすくなるからです。', explanationEn: 'Example: 버스 도착 정보를 더 자주 알려야 합니다. 기다리는 시간이 길어도 계획을 세우기 쉬워지기 때문입니다.', audioTextKo: '버스 도착 정보를 더 자주 알려야 합니다. 기다리는 시간이 길어도 계획을 세우기 쉬워지기 때문입니다.' },

  { grade: 6, section: 'vocab', titleKo: '연구와 해석', titleJa: '研究と解釈', titleEn: 'Research and interpretation', promptKo: '자료의 뜻이나 의미를 맥락에 따라 설명하는 것은 무엇입니까?', promptJa: '資料の意味を文脈に応じて説明することは何ですか。', promptEn: 'What is explaining the meaning of material according to its context?', choices: ['해석', '예약', '등록', '반복'], answerIndex: 0, explanationKo: '해석은 글·자료·현상의 뜻을 이해하고 설명하는 일입니다.', explanationJa: '「해석」は文・資料・現象の意味を理解して説明することです。', explanationEn: '해석 is interpreting and explaining the meaning of text, data, or phenomena.', audioTextKo: '해석' },
  { grade: 6, section: 'grammar', titleKo: '기에', titleJa: '〜なので', titleEn: 'Because', promptKo: '자료가 충분하지 않___ 지금 결론을 내리기는 이릅니다.', promptJa: '資料が十分でない___、今結論を出すのは早いです。', promptEn: 'Because the data is insufficient, it is too early to reach a conclusion now.', choices: ['기에', '기는 하지만', '도록', '마저'], answerIndex: 0, explanationKo: '기에는 이유나 판단의 근거를 비교적 격식 있게 나타낼 수 있습니다.', explanationJa: '「기에」は理由や判断の根拠を比較的硬い表現で示せます。', explanationEn: '기에 can express a reason or basis for a judgment in a formal style.', audioTextKo: '자료가 충분하지 않기에 지금 결론을 내리기는 이릅니다.' },
  { grade: 6, section: 'reading', titleKo: '자료 공개 원칙', titleJa: '資料公開の原則', titleEn: 'Principles for releasing data', promptKo: '지문: 연구 결과를 공개할 때에는 결론만 제시해서는 안 된다. 자료를 선택한 기준과 분석 과정도 함께 설명해야 다른 사람이 해석의 타당성을 검토할 수 있다.\n질문: 글쓴이가 함께 설명해야 한다고 한 것은 무엇입니까?', promptJa: '本文：研究結果を公開するとき、結論だけを示してはいけない。資料を選んだ基準と分析過程も一緒に説明してこそ、他の人が解釈の妥当性を検討できる。\n質問：筆者が一緒に説明すべきだと述べたものは何ですか。', promptEn: 'Text: When publishing research results, do not present only conclusions. Explain the criteria for choosing data and the analysis process so others can assess the validity of the interpretation. What should also be explained?', choices: ['자료 선택 기준과 분석 과정', '결론만', '연구자 이름만', '발표 장소만'], answerIndex: 0, explanationKo: '다른 사람이 해석의 타당성을 검토할 수 있도록 자료 선택 기준과 분석 과정을 설명해야 합니다.', explanationJa: '他者が解釈の妥当性を検討できるよう、資料選択の基準と分析過程を説明すべきです。', explanationEn: 'The criteria for selecting data and the analysis process must be explained.', audioTextKo: '연구 결과를 공개할 때에는 결론만 제시해서는 안 된다. 자료를 선택한 기준과 분석 과정도 함께 설명해야 한다.' },
  { grade: 6, section: 'listening', titleKo: '발표 결론 듣기', titleJa: '発表の結論を聞く', titleEn: 'Listening to a presentation conclusion', promptKo: '화자는 어떤 태도로 결과를 받아들여야 한다고 말합니까?', promptJa: '話者はどのような態度で結果を受け止めるべきだと言っていますか。', promptEn: 'With what attitude should the results be received?', choices: ['한계도 함께 고려한다', '무조건 사실로 믿는다', '바로 폐기한다', '다른 의견을 막는다'], answerIndex: 0, explanationKo: '결과가 의미 있어도 자료의 한계와 다른 가능성을 함께 고려해야 한다고 말합니다.', explanationJa: '結果に意味があっても、資料の限界と他の可能性を一緒に考慮すべきだと言っています。', explanationEn: 'The speaker says to consider data limitations and other possibilities along with the results.', audioTextKo: '이번 결과는 의미가 있지만, 자료의 한계와 다른 가능성도 함께 고려해야 합니다. 앞으로 더 넓은 범위에서 확인할 필요가 있습니다.' },
  { grade: 6, section: 'writing', titleKo: '균형 있는 비평', titleJa: 'バランスの取れた批評', titleEn: 'Balanced critique', promptKo: '한 주장에 동의하는 점과 보완할 점을 각각 한 문장으로 써 보세요.', promptJa: '一つの主張について同意する点と補う点をそれぞれ一文で書いてください。', promptEn: 'Write one sentence supporting a claim and one sentence describing what should be improved.', explanationKo: '예: 이 주장은 이용자 경험을 중요하게 본다는 점에서 설득력이 있습니다. 다만 지역별 자료도 더 제시하면 결론을 더 신뢰할 수 있습니다.', explanationJa: '例：この主張は利用者の経験を重視する点で説得力があります。ただし地域別の資料もさらに示せば、結論をより信頼できます。', explanationEn: 'Example: 이 주장은 이용자 경험을 중요하게 본다는 점에서 설득력이 있습니다. 다만 지역별 자료도 더 제시하면 결론을 더 신뢰할 수 있습니다.', audioTextKo: '이 주장은 이용자 경험을 중요하게 본다는 점에서 설득력이 있습니다. 다만 지역별 자료도 더 제시하면 결론을 더 신뢰할 수 있습니다.' },
];

export interface TopikOwnerBatch2Manifest { sourceCode: string; sourceAssetId: string; sourcePath: string; sourceSha256: string; counts: { units: number; items: number; stableRefs: number; audioBindings: number; contentRows: number }; }
export interface TopikOwnerBatch2Plan { statements: string[]; manifest: TopikOwnerBatch2Manifest; }
function slug(item: Pick<ItemSeed, 'grade' | 'section'>): string { return `${item.grade}-${item.section}`; }
function unitId(item: ItemSeed): string { return `topik-owner-batch2-unit-${slug(item)}`; }
function itemId(item: ItemSeed): string { return `topik-owner-batch2-item-${slug(item)}`; }
function stableRef(item: ItemSeed): string { return `topik:owner:batch2:grade${item.grade}:${item.section}`; }
function answerJson(item: ItemSeed): string { return JSON.stringify(item.choices ? { choices: item.choices, answer_index: item.answerIndex } : { sample_answer_ko: item.explanationKo.replace(/^예: /, '') }); }
function unitStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `topik_owner_authored_curriculum_units`', '  (`id`, `target_grade`, `stable_ref`, `section`, `title_ko`, `title_ja`, `title_en`, `source_asset_id`)', `VALUES (${esc(unitId(item))}, ${item.grade}, ${esc(`topik:owner:batch2:grade${item.grade}:unit:${item.section}`)}, ${esc(item.section)}, ${esc(item.titleKo)}, ${esc(item.titleJa)}, ${esc(item.titleEn)}, ${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)});`].join('\n'); }
function itemStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `topik_owner_authored_curriculum_items`', '  (`id`, `unit_id`, `target_grade`, `stable_ref`, `item_type`, `prompt_ko`, `prompt_ja`, `prompt_en`, `answer_json`, `explanation_ko`, `explanation_ja`, `explanation_en`, `audio_required`, `audio_text_ko`, `source_asset_id`)', `VALUES (${esc(itemId(item))}, ${esc(unitId(item))}, ${item.grade}, ${esc(stableRef(item))}, ${esc(item.section)}, ${esc(item.promptKo)}, ${esc(item.promptJa)}, ${esc(item.promptEn)}, ${esc(answerJson(item))}, ${esc(item.explanationKo)}, ${esc(item.explanationJa)}, ${esc(item.explanationEn)}, 1, ${esc(item.audioTextKo)}, ${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)});`].join('\n'); }
function stableRefStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `learning_content_stable_refs`', '  (`stable_ref`, `learning_track`, `item_type`, `item_id`, `level_tag`, `source_asset_id`)', `VALUES (${esc(stableRef(item))}, 'topik-ko', 'topik-owner-item', ${esc(itemId(item))}, ${esc(`TOPIK-${item.grade}`)}, ${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)});`].join('\n'); }
function audioBindingStatement(item: ItemSeed): string { return ['INSERT OR IGNORE INTO `content_audio_bindings`', '  (`id`, `stable_ref`, `item_type`, `item_id`, `language`, `audio_role`, `binding_state`, `asset_id`, `unavailable_reason`)', `VALUES (${esc(`audio-binding:${stableRef(item)}`)}, ${esc(stableRef(item))}, 'topik-owner-item', ${esc(itemId(item))}, 'ko', ${esc(item.section === 'listening' ? 'listening' : 'pronunciation')}, 'preparing', NULL, ${esc(AUDIO_PREPARING_REASON)});`].join('\n'); }
export function topikOwnerBatch2ContentRowsSql(): string { return `SELECT (SELECT count(*) FROM topik_owner_authored_curriculum_units WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)}) + (SELECT count(*) FROM topik_owner_authored_curriculum_items WHERE source_asset_id = ${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)}) AS count;`; }
export function buildTopikOwnerBatch2Plan(): TopikOwnerBatch2Plan {
  const sourceSha256 = createHash('sha256').update(fs.readFileSync(TOPIK_OWNER_BATCH_2_PATH)).digest('hex');
  const statements = [
    ['INSERT INTO `sources` (`code`, `title`, `file_path`, `version`)', `VALUES (${esc(TOPIK_OWNER_BATCH_2_SOURCE_CODE)}, 'TOPIK 1~6급 자체 저작 Batch 2', 'docs/07_topik/03_owner_authored_grades_1_6_batch_2.md', ${esc(`source-v3-${sourceSha256.slice(0, 16)}`)})`, 'ON CONFLICT(`code`) DO UPDATE SET `title` = excluded.`title`, `file_path` = excluded.`file_path`, `version` = excluded.`version`, `updated_at` = unixepoch();'].join('\n'),
    ['INSERT OR IGNORE INTO `content_source_assets`', '  (`id`, `asset_kind`, `source_url`, `license_id`, `license_url`, `attribution_text`, `allowed_use`, `source_sha256`, `generated_at`, `selection_reason`)', `VALUES (${esc(TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID)}, 'self-authored-fixture', ${esc(REPOSITORY_URL)}, 'LicenseRef-nihongo-n3-self-authored', ${esc(LICENSE_URL)},`, "  '© Nihongo N3 contributors; self-authored TOPIK learning content.',", "  'Personal learning content; self-authored Korean prompts, scripts, questions, answers, and explanations; not official TOPIK material.',", `  ${esc(sourceSha256)}, 1785379200, 'Second operating TOPIK 1–6 self-authored curriculum batch with browser Korean voice while R2 audio is prepared.');`].join('\n'),
    ...ITEMS.map(unitStatement), ...ITEMS.map(itemStatement), ...ITEMS.map(stableRefStatement), ...ITEMS.map(audioBindingStatement),
  ];
  const counts = { units: ITEMS.length, items: ITEMS.length, stableRefs: ITEMS.length, audioBindings: ITEMS.length, contentRows: ITEMS.length * 2 } as const;
  return { statements, manifest: { sourceCode: TOPIK_OWNER_BATCH_2_SOURCE_CODE, sourceAssetId: TOPIK_OWNER_BATCH_2_SOURCE_ASSET_ID, sourcePath: path.relative(REPO_ROOT, TOPIK_OWNER_BATCH_2_PATH).split(path.sep).join('/'), sourceSha256, counts } };
}
